// Generated by grafana-k6 on 2026-09-05T07:52:37Z
/** The orders screen of the fixture store while (or after) shopper scripts fill it. */
import { sleep } from 'k6';
import { build, scenario } from '../../config/profiles.js';
import { withFixtures } from '../../lib/fixtures/provision.js';
import { ordersList } from '../../lib/journeys/admin/ordersList.js';

export const options = build({ layer: 'admin', script: 'admin-orders-list', needs: ['store'], scenarios: { merchants: scenario('vus', 'merchants', { peak: 5 }) } });
export const { setup, teardown } = withFixtures(options);
export { handleSummary } from '../../lib/core/metrics.js';

export function merchants(data) {
  ordersList(data.fixtures.store.session, data.fixtures.store);
  sleep(2 + Math.random() * 3);
}
