// Generated by grafana-k6 on 2026-09-05T07:52:37Z
/** Super-admin platform screens: pods, users, roles, plans, subscriptions, statistics. */
import { sleep } from 'k6';
import execution from 'k6/execution';
import { build, scenario } from '../../config/profiles.js';
import { withFixtures } from '../../lib/fixtures/provision.js';
import { sessionFor } from '../../lib/core/session.js';
import { platformReads } from '../../lib/journeys/admin/platformReads.js';

export const options = build({ layer: 'admin', script: 'admin-platform-reads', needs: ['sessions'], scenarios: { operators: scenario('vus', 'operators', { peak: 5 }) } });
export const { setup, teardown } = withFixtures(options);
export { handleSummary } from '../../lib/core/metrics.js';

export function operators(data) {
  const supers = data.fixtures.sessions.filter((s) => s.role === 'SUPER_ADMIN');
  const session = supers.length > 0 ? sessionFor(supers, execution.vu.idInTest) : sessionFor(data.fixtures.sessions, execution.vu.idInTest);
  platformReads(session);
  sleep(3 + Math.random() * 3);
}
