// Generated by grafana-k6 on 2026-09-05T07:52:37Z
/** Org admins reading their store screens through the gateway, with a shared session pool. */
import { sleep } from 'k6';
import execution from 'k6/execution';
import { storeFor } from '../../lib/core/env.js';
import { build, scenario } from '../../config/profiles.js';
import { withFixtures } from '../../lib/fixtures/provision.js';
import { sessionWithRole } from '../../lib/core/session.js';
import { storeReads } from '../../lib/journeys/admin/storeReads.js';

export const options = build({ layer: 'admin', script: 'admin-store-reads', needs: ['sessions'], scenarios: { admins: scenario('vus', 'admins', { peak: 10 }) } });
export const { setup, teardown } = withFixtures(options);
export { handleSummary } from '../../lib/core/metrics.js';

export function admins(data) {
  const session = sessionWithRole(data.fixtures.sessions, execution.vu.idInTest, ['ORG_ADMIN']);
  storeReads(session, storeFor(execution.vu.idInTest));
  sleep(2 + Math.random() * 3);
}
