// Generated by grafana-k6 on 2026-09-05T07:50:12Z
/**
 * A merchant editing the catalogue in the console: a category, a product, its price and stock, an inline
 * toggle, the listing the screen refreshes, then the product is removed so the store stays bounded.
 */
import { sellerEdge } from '../../core/edges.js';
import { journey, productsCreated, planLimitHits } from '../../core/metrics.js';
import { CatalogClient, InventoryClient } from '../../clients/index.js';
import { slug, productDefinition, categoryDefinition, inventoryEntry } from '../../../data/faker.js';

export function catalogEdit(session, store, opts) {
  const o = Object.assign({ keep: false, categoryId: null }, opts || {});
  return journey('catalog-edit', () => {
    const edge = sellerEdge(session, store);
    const catalog = new CatalogClient(edge);
    const inventory = new InventoryClient(edge);
    const code = slug('k6-cat');
    const sku = slug('K6-EDIT').toUpperCase();

    let categoryId = o.categoryId;
    if (!categoryId) {
      const cat = catalog.createCategory(categoryDefinition(code, `K6 ${code}`, 99));
      categoryId = cat.body ? cat.body.id : null;
      if (!cat.ok) return false;
    }
    let ok = catalog.skuExists(sku).ok;
    // 422 at MAX_PRODUCTS is the plan doing its job, not the platform failing: counted, not failed
    const created = catalog.createProduct(productDefinition(sku, `K6 edit ${sku}`, sku.toLowerCase()), [201, 422]);
    if (created.status === 422) {
      planLimitHits.add(1, { limit: 'MAX_PRODUCTS' });
      return ok;
    }
    ok = created.ok && ok;
    const productId = created.body ? created.body.id : null;
    if (!productId) return false;
    productsCreated.add(1);

    ok = catalog.attachCategory(productId, categoryId).ok && ok;
    ok = inventory.set(sku, inventoryEntry(productId, 100, 42)).ok && ok;
    ok = catalog.patchProduct(productId, true, true).ok && ok;
    ok = catalog.getProductDefinition(productId).ok && ok;
    ok = catalog.updateProduct(productId, productDefinition(sku, `K6 edit ${sku} renamed`, sku.toLowerCase())).ok && ok;
    ok = catalog.listing({ sku: 'K6-EDIT', count: 20 }).ok && ok;
    ok = catalog.privateCategoryHierarchy(50).ok && ok;
    ok = inventory.availability([sku]).ok && ok;
    if (!o.keep) {
      ok = inventory.deleteBySku(sku).ok && ok;
      ok = catalog.deleteProduct(productId).ok && ok;
      if (!o.categoryId) ok = catalog.deleteCategory(categoryId).ok && ok;
    }
    return ok;
  });
}
