// Generated by grafana-k6 on 2026-09-05T07:50:12Z
/**
 * The content editor: pages (create, list, update with its version, publish) and the HOME layout's
 * read → write → publish cycle, which is optimistic — a concurrent editor gets 409 and that is correct.
 */
import { sellerEdge } from '../../core/edges.js';
import { journey } from '../../core/metrics.js';
import { ContentClient } from '../../clients/index.js';
import { slug, contentPageDefinition } from '../../../data/faker.js';

export function contentEdit(session, store) {
  return journey('content-edit', () => {
    const content = new ContentClient(sellerEdge(session, store));
    const pageSlug = slug('k6-page');
    const created = content.createPage(contentPageDefinition(pageSlug, `K6 ${pageSlug}`));
    let ok = created.ok;
    const id = created.body ? created.body.id : null;
    const version = created.body ? created.body.version : 1;
    ok = content.listPages(0, 25).ok && ok;
    if (id) {
      const body = Object.assign(contentPageDefinition(pageSlug, `K6 ${pageSlug} v2`), { version });
      ok = content.updatePage(id, body).ok && ok;
      ok = content.publishPage(id, {}).ok && ok;
      ok = content.deletePage(id, true).ok && ok;
    }

    const layout = content.getLayout('HOME');
    ok = layout.ok && ok;
    if (layout.body && layout.body.document) {
      const base = layout.body.version !== undefined ? layout.body.version : layout.body.baseVersion;
      const saved = content.putLayout('HOME', base, layout.body.document);
      ok = saved.ok && ok;
      if (saved.status === 200) {
        const next = saved.body && saved.body.version !== undefined ? saved.body.version : base + 1;
        ok = content.publishLayout('HOME', next).ok && ok;
      }
    }
    ok = content.summary().ok && ok;
    return ok;
  });
}
