// Generated by grafana-k6 on 2026-09-05T07:50:12Z
/** The merchant's orders screen: the list, a filtered list, one order, its history, the payment ledger. */
import { sellerEdge } from '../../core/edges.js';
import { journey } from '../../core/metrics.js';
import { CheckoutClient, PaymentClient } from '../../clients/index.js';

export function ordersList(session, store) {
  return journey('orders-list', () => {
    const edge = sellerEdge(session, store);
    const checkout = new CheckoutClient(edge);
    const list = checkout.orders({ page: 0, count: 20 });
    let ok = list.ok;
    ok = checkout.orders({ page: 0, count: 20, email: 'load.test' }).ok && ok;
    const orders = list.body ? (list.body.orders || list.body.content || []) : [];
    if (orders.length > 0) {
      const id = orders[Math.floor(Math.random() * orders.length)].id;
      ok = checkout.order(id).ok && ok;
      ok = checkout.orderHistory(id).ok && ok;
    }
    ok = new PaymentClient(edge).transactions().ok && ok;
    return ok;
  });
}
