// Generated by grafana-k6 on 2026-09-05T07:50:12Z
/** Platform screens a super-admin opens: pods, users and roles, plans, subscriptions, statistics. */
import { platformEdge } from '../../core/edges.js';
import { journey } from '../../core/metrics.js';
import { config } from '../../core/env.js';
import { TenancyClient, BillingClient, PodRegistryClient, UaaClient } from '../../clients/index.js';

export function platformReads(session) {
  return journey('platform-reads', () => {
    const edge = platformEdge(session);
    const tenancy = new TenancyClient(edge);
    const billing = new BillingClient(edge);
    const pods = new PodRegistryClient(edge);
    const uaa = new UaaClient(edge);
    let ok = pods.list().ok;
    ok = pods.get(config.podId).ok && ok;
    ok = uaa.me().ok && ok;
    ok = uaa.adminUsers({ page: 0, count: 20 }).ok && ok;
    ok = uaa.adminRoles().ok && ok;
    ok = uaa.adminDashboard('7d').ok && ok;
    ok = billing.plans().ok && ok;
    ok = billing.platformSubscriptions().ok && ok;
    ok = billing.health().ok && ok;
    ok = tenancy.orgs().ok && ok;
    ok = tenancy.storesPerPod().ok && ok;
    ok = tenancy.storeStatistic('2020-01-01T00:00:00Z', '2030-01-01T00:00:00Z').ok && ok;
    return ok;
  });
}
