// Generated by grafana-k6 on 2026-09-13T07:20:45Z
/**
 * The console's store settings screen (/store-management/domain, its first section): the shell, then the reads
 * StoreSettingsApi.loadSettings makes (cvhome console-ui features/store-management). Every section shares them.
 */
import { gatewayEdge, platformEdge, sellerEdge } from '../../core/edges.js';
import { journey } from '../../core/metrics.js';
import { GatewayClient, TenancyClient, MerchantClient, PaymentClient } from '../../clients/index.js';

export function storeSettings(session, store) {
  return journey('store-settings', () => {
    const tenancy = new TenancyClient(platformEdge(session));
    const merchant = new MerchantClient(sellerEdge(session, store));
    const payment = new PaymentClient(sellerEdge(session, store));
    let ok = new GatewayClient(gatewayEdge(session)).storeManagement().ok;
    ok = merchant.privateStore().ok && ok;
    ok = tenancy.themes().ok && ok;
    ok = tenancy.colorThemes().ok && ok;
    ok = tenancy.socialLinkProviders().ok && ok;
    ok = merchant.languages().ok && ok;
    ok = merchant.allocates().ok && ok;
    ok = tenancy.saasProperties().ok && ok;
    ok = tenancy.storePod(store.id).ok && ok;
    ok = payment.privateSupportedPaymentTypes().ok && ok;
    ok = payment.configurations().ok && ok;
    return ok;
  });
}
