// Generated by grafana-k6 on 2026-09-05T07:50:12Z
/** The console's store screens: list, detail, info, billing state — what an org admin sees after sign-in. */
import { platformEdge, sellerEdge } from '../../core/edges.js';
import { journey } from '../../core/metrics.js';
import { TenancyClient, BillingClient, MerchantClient } from '../../clients/index.js';

export function storeReads(session, store) {
  return journey('store-reads', () => {
    const tenancy = new TenancyClient(platformEdge(session));
    const billing = new BillingClient(platformEdge(session));
    let ok = tenancy.currentUser().ok;
    ok = tenancy.listStores({}, 0, 20).ok && ok;
    ok = tenancy.stores().ok && ok;
    ok = tenancy.storeInfo(store.id).ok && ok;
    ok = tenancy.store(store.id).ok && ok;
    ok = tenancy.storeNameExists(store.name).ok && ok;
    ok = tenancy.themes().ok && ok;
    ok = tenancy.colorThemes().ok && ok;
    ok = billing.currentSubscription(store.id).ok && ok;
    ok = billing.invoices(store.id).ok && ok;
    ok = billing.entitlement(store.id).ok && ok;
    ok = new MerchantClient(sellerEdge(session, store)).privateStore().ok && ok;
    return ok;
  });
}
