// Generated by grafana-k6 on 2026-09-05T07:50:12Z
/**
 * The onboarding funnel end to end: a new org signs up, its admin signs in, creates a store, waits for it to
 * be provisioned on a pod, updates it, suspends/resumes it, archives and deletes it. One org per iteration so
 * the 3-pending-stores quota never bites; the sign-in step is what the deployed rate limiter meters.
 */
import { env, storeUrl } from '../../core/env.js';
import { login } from '../../core/session.js';
import { platformEdge, sellerEdge } from '../../core/edges.js';
import { pollUntil } from '../../core/wait.js';
import { journey, storesCreated } from '../../core/metrics.js';
import { TenancyClient, MerchantClient } from '../../clients/index.js';
import { slug, signupUser, storeDefinition } from '../../../data/faker.js';

/**
 * opts.operator — a SUPER_ADMIN session: suspend/resume are platform actions (an org admin gets 403), so without
 * one those two steps are skipped.
 */
export function onboardOrgAndStore(opts) {
  const o = Object.assign({ provisionTimeout: 120, keep: false, operator: null }, opts || {});
  return journey('store-lifecycle', () => {
    const name = slug(`k6-${env.RUN_ID}-lc`);
    const email = `${name}@load.test`;
    const password = env.FIXTURE_PASSWORD;
    const anonymous = new TenancyClient(platformEdge(null));
    let ok = anonymous.signup(signupUser(name, email, password)).ok;
    const session = login({ username: email, password, role: 'ORG_ADMIN' });
    if (!session) return false;

    const tenancy = new TenancyClient(platformEdge(session));
    const created = tenancy.createStore(storeDefinition(name, email));
    ok = created.ok && ok;
    if (!created.storeId) return false;
    storesCreated.add(1);
    const storeId = String(created.storeId);
    const store = { id: storeId, name, url: storeUrl(name), podId: env.POD_ID || undefined, fixture: true };

    const operable = pollUntil(() => tenancy.storePod(storeId, [200, 422, 404]).status === 200, { timeout: o.provisionTimeout, interval: 3, label: 'store operable' });
    ok = !!operable && ok;
    ok = tenancy.storeInfo(storeId).ok && ok;

    // the pod side of the store appears a moment after tenancy reports it operable
    const merchant = new MerchantClient(sellerEdge(session, Object.assign({}, store, { podId: undefined })));
    const current = pollUntil(() => { const r = merchant.privateStore([200, 403, 404]); return r.status === 200 ? r : null; }, { timeout: 60, interval: 3, label: 'merchant store on the pod' });
    ok = !!current && ok;
    if (current && current.body) {
      const body = Object.assign({}, current.body, { name, email, phone: '+10000000001' });
      ok = merchant.updateStore(body).ok && ok;
    }

    if (o.operator) {
      const platform = new TenancyClient(platformEdge(o.operator));
      ok = platform.suspendStore(storeId).ok && ok;
      ok = platform.resumeStore(storeId).ok && ok;
    }
    if (!o.keep) {
      ok = tenancy.archiveStore(storeId).ok && ok;
      ok = tenancy.deleteStore(storeId).ok && ok;
    }
    return ok;
  });
}
