// Generated by grafana-k6 on 2026-09-05T08:00:25Z
/** Read-only browsing of the seeded store in Chromium: LCP, CLS, INP per page. */
import execution from 'k6/execution';
import { storeFor } from '../../lib/core/env.js';
import { build, browserScenario } from '../../config/profiles.js';
import { catalogFor } from '../../lib/journeys/shopper/data.js';
import { browserBrowse } from '../../lib/journeys/browser/browse.js';

export const options = build({ layer: 'browser', script: 'browser-browse', scenarios: { ui: browserScenario('ui') } });
export { handleSummary } from '../../lib/core/metrics.js';

export async function ui() {
  const store = storeFor(execution.vu.idInTest);
  await browserBrowse(store, catalogFor(store));
}
