// Generated by grafana-k6 on 2026-09-05T08:00:25Z
/** Registration and sign-in in a real browser on a seeded store: cua's hand-off pages and redirect chain. */
import execution from 'k6/execution';
import { env, storeFor } from '../../lib/core/env.js';
import { build, browserScenario } from '../../config/profiles.js';
import { browserRegisterAndLogin } from '../../lib/journeys/browser/shopperAuth.js';

export const options = build({ layer: 'browser', script: 'browser-shopper-auth', scenarios: { ui: browserScenario('ui') } });
export { handleSummary } from '../../lib/core/metrics.js';

export async function ui() {
  // unique across runs: a username is taken forever once registered
  const username = `k6-ui-${env.RUN_ID}-${Date.now().toString(36)}-${execution.vu.idInTest}`.toLowerCase();
  await browserRegisterAndLogin(storeFor(execution.vu.idInTest), {
    username, email: `${username}@load.test`, password: env.FIXTURE_PASSWORD, firstName: 'K6', lastName: 'Browser',
  });
}
