// Generated by grafana-k6 on 2026-09-14T06:36:37Z
/**
 * The storefront spike, seen from a browser. HTTP shoppers make the load, storefront-browse's spike: a quarter of
 * PEAK_VUS for 30 s, ten times PEAK_VUS for a minute, then back. Chromium shoppers are measured through it in three
 * windows: before the spike, the minute at 10×, and from 20 s after it (profiles.js browserPhases). Each visit is one
 * page of the page mix in a fresh context, a first visit. The summary and Prometheus split every browser metric by
 * window (`scenario`), by kind of page (`journey`: visit-home, visit-category, visit-product, visit-search) and every
 * request by what it is (the browser's `resource_type`: Document, Script, Fetch, ...). Always the spike, whatever
 * PROFILE says, but smoke.
 *   make browser-storefront-spike PROFILE=spike STORES=org1-store2 PEAK_VUS=10     10 → 100 shoppers, perf-suite's spike
 */
import execution from 'k6/execution';
import { env, storeFor } from '../../lib/core/env.js';
import { build, scenario, browserPhases } from '../../config/profiles.js';
import { browserSpike } from '../../config/thresholds.js';
import { pageMix } from '../../config/mix.js';
import { catalogFor } from '../../lib/journeys/shopper/data.js';
import { browseVisit } from '../../lib/journeys/shopper/browse.js';
import { pickPage } from '../../lib/journeys/shopper/pages.js';
import { browserVisit } from '../../lib/journeys/browser/visit.js';

const profile = env.PROFILE === 'smoke' ? 'smoke' : 'spike';
export const options = build({ layer: 'browser', script: 'browser-storefront-spike', profile,
  scenarios: Object.assign({ shoppers: scenario('vus', 'shoppers', { profile }) }, browserPhases('visit')),
  thresholds: browserSpike(profile) });
export { handleSummary } from '../../lib/core/metrics.js';

export function shoppers() {
  const store = storeFor(execution.vu.idInTest);
  browseVisit(store, catalogFor(store));
}

export async function visit() {
  const store = storeFor(execution.vu.idInTest);
  await browserVisit(store, catalogFor(store), pickPage(pageMix));
}
