// Generated by grafana-k6 on 2026-09-14T06:36:37Z
/**
 * The storefront spike, seen from a browser. HTTP shoppers make the load: a quarter of PEAK_VUS for 30 s, ten times
 * PEAK_VUS for a minute, then back (SPIKE_MODEL=vus), or the same shape as an arrival rate from RATE (SPIKE_MODEL=rate:
 * the offered load stays what was asked whatever the pages cost, where shoppers in a closed model loop faster as pages
 * get faster and slower as they queue). What each shopper sends is SHOPPER_TRAFFIC: what a browser fetches
 * (`browser`, pages.js browserLikeVisit) or every read landing-ui makes beside each page (`api`, browse.js
 * browseVisit). Chromium shoppers are measured through it in three windows: before the spike, the minute at 10×, and
 * from 20 s after it (profiles.js browserPhases). Each visit is one page of the page mix in a fresh context, a first
 * visit. The summary and Prometheus split every browser metric by window (`scenario`), by kind of page (`journey`:
 * visit-home, visit-category, visit-product, visit-search) and every request by what it is (the browser's
 * `resource_type`: Document, Script, Fetch, ...). Always the spike, whatever PROFILE says, but smoke.
 *   make browser-storefront-spike PROFILE=spike STORES=org1-store2 PEAK_VUS=10     10 → 100 shoppers, perf-suite's spike
 *   make browser-storefront-spike PROFILE=spike STORES=org1-store2 SPIKE_MODEL=rate RATE=60     60 → 600 visits a minute
 */
import execution from 'k6/execution';
import { env, storeFor } from '../../lib/core/env.js';
import { build, scenario, browserPhases } from '../../config/profiles.js';
import { browserSpike } from '../../config/thresholds.js';
import { pageMix } from '../../config/mix.js';
import { catalogFor } from '../../lib/journeys/shopper/data.js';
import { browseVisit } from '../../lib/journeys/shopper/browse.js';
import { browserLikeVisit, pickPage } from '../../lib/journeys/shopper/pages.js';
import { browserVisit } from '../../lib/journeys/browser/visit.js';

const profile = env.PROFILE === 'smoke' ? 'smoke' : 'spike';
if (!['vus', 'rate'].includes(env.SPIKE_MODEL)) throw new Error(`SPIKE_MODEL=${env.SPIKE_MODEL}: vus | rate`);
if (!['browser', 'api'].includes(env.SHOPPER_TRAFFIC)) throw new Error(`SHOPPER_TRAFFIC=${env.SHOPPER_TRAFFIC}: browser | api`);
export const options = build({ layer: 'browser', script: 'browser-storefront-spike', profile,
  scenarios: Object.assign({ shoppers: scenario(env.SPIKE_MODEL, 'shoppers', { profile }) }, browserPhases('visit')),
  thresholds: browserSpike(profile) });
export { handleSummary } from '../../lib/core/metrics.js';

export function shoppers() {
  const store = storeFor(execution.vu.idInTest);
  if (env.SHOPPER_TRAFFIC === 'api') browseVisit(store, catalogFor(store));
  else browserLikeVisit(store, catalogFor(store));
}

export async function visit() {
  const store = storeFor(execution.vu.idInTest);
  await browserVisit(store, catalogFor(store), pickPage(pageMix));
}
