// Generated by grafana-k6 on 2026-09-05T07:41:35Z
/**
 * An edge is *where* a request enters the platform and what every request through it must carry.
 * Clients are edge-agnostic: the same CatalogClient reads the storefront through spg or the console through
 * store-core-gateway depending only on the edge it was built with.
 *
 *   storefrontEdge(store)          http://<store>.<pod>/<service>/...?store=&lang=          shopper, no auth
 *   sellerEdge(session, store)     http://<gateway>/spg/<service>/...?store=&pod=&lang=     console → pod, session cookie
 *   platformEdge(session)          http://<gateway>/<service>/...                           console → tenancy/billing/pod-registry/uaa
 *   gatewayEdge(session?)          http://<gateway>/...                                     the gateway itself (login, SSR console)
 *   uaaEdge()                      http://<uaa>/...                                         uaa on its own origin, public
 */
import { config } from './env.js';

const SESSION_COOKIE = 'STORE-CORE-GATEWAY-JSESSIONID';

function sessionHeaders(session) {
  return session && session.cookie ? { Cookie: `${SESSION_COOKIE}=${session.cookie}` } : {};
}

export function storefrontEdge(store) {
  return {
    kind: 'storefront',
    layer: 'storefront',
    store,
    params: { store: store.id, lang: config.lang },
    headers: {},
    url: (service, path) => (service ? `${store.url}/${service}${path}` : `${store.url}${path}`),
  };
}

export function sellerEdge(session, store) {
  return {
    kind: 'seller',
    layer: 'admin',
    store,
    session,
    params: { store: store.id, pod: store.podId || config.podId, lang: config.lang },
    headers: sessionHeaders(session),
    url: (service, path) => (service ? `${config.gatewayUrl}/spg/${service}${path}` : `${config.gatewayUrl}/spg${path}`),
  };
}

export function platformEdge(session) {
  return {
    kind: 'platform',
    layer: 'admin',
    store: null,
    session,
    params: { lang: config.lang },
    headers: sessionHeaders(session),
    url: (service, path) => (service ? `${config.gatewayUrl}/${service}${path}` : `${config.gatewayUrl}${path}`),
  };
}

export function gatewayEdge(session) {
  return {
    kind: 'gateway',
    layer: 'platform',
    store: null,
    session,
    params: {},
    headers: sessionHeaders(session),
    url: (service, path) => `${config.gatewayUrl}${path}`,
  };
}

export function uaaEdge() {
  return {
    kind: 'uaa',
    layer: 'platform',
    store: null,
    params: {},
    headers: {},
    url: (service, path) => `${config.uaaUrl}${path}`,
  };
}

/** A copy of an edge with extra headers (a shopper bearer token, for instance). */
export function withHeaders(edge, headers) {
  return Object.assign({}, edge, { headers: Object.assign({}, edge.headers, headers) });
}

export { SESSION_COOKIE };
