// Generated by grafana-k6 on 2026-09-05T07:41:35Z
/**
 * The one declared configuration surface of the suite.
 *
 * Two sources, one precedence: `k6/config/env/<TARGET>.json` describes a deployment (hosts, ids, seeded
 * accounts); `__ENV` variables listed in SCHEMA tune a run and may override any deployment field. Nothing else
 * in the suite reads `__ENV` directly, so `make help` can print this table and a new knob is one line here.
 */

export const SCHEMA = {
  TARGET:            { default: 'lcl',        doc: 'deployment file: k6/config/env/<TARGET>.json' },
  PROFILE:           { default: 'smoke',      doc: 'load shape: smoke | load | stress | spike | soak | breakpoint' },
  RUN_ID:            { default: 'local',      doc: 'fixture namespace k6-<RUN_ID>, reused run after run; RUN_ID=fresh makes a new one' },
  STORES:            { default: 'org1-store1',doc: 'seeded stores a read test spreads over: names, comma-separated, or all' },
  LANG_CODE:         { default: '',           doc: 'language for every ?lang= (default: the deployment file)' },
  PEAK_VUS:          { default: 20,  type: 'number', doc: 'closed-model peak VUs (load); stress/spike scale from it' },
  RATE:              { default: 30,  type: 'number', doc: 'open-model iterations per RATE_UNIT' },
  RATE_UNIT:         { default: '1m',         doc: 'time unit of RATE' },
  DURATION:          { default: '5m',         doc: 'hold duration for load/soak' },
  MAX_RPS:           { default: 200, type: 'number', doc: 'breakpoint: final iterations per second' },
  RAMP:              { default: '10m',        doc: 'breakpoint: ramp length' },
  BROWSER_VUS:       { default: 3,   type: 'number', doc: 'Chromium VUs in browser scripts' },
  BROWSER_ITERATIONS:{ default: 0,   type: 'number', doc: 'browser iterations total (0 = derived from profile)' },
  BROWSER_BLOCK_IMAGES:{ default: false, type: 'boolean', doc: 'abort image requests in the browser (MinIO 404s locally)' },
  SESSION_POOL:      { default: 4,   type: 'number', doc: 'seller sessions logged in at setup and shared by VUs' },
  SHOPPERS:          { default: 5,   type: 'number', doc: 'shopper accounts registered at setup for authenticated flows' },
  FIXTURE_CATEGORIES:{ default: 5,   type: 'number', doc: 'categories created in the k6- fixture store' },
  FIXTURE_PRODUCTS:  { default: 25,  type: 'number', doc: 'products (with inventory) in the k6- fixture store (a trial store allows 25)' },
  FIXTURE_STOCK:     { default: 10000000, type: 'number', doc: 'stock per fixture sku (never runs out)' },
  FIXTURE_PASSWORD:  { default: 'K6-load-test-1', doc: 'password of the fixture org admin and shoppers' },
  KEEP_FIXTURES:     { default: true, type: 'boolean', doc: 'keep the k6- store (reused next run); false deletes it and burns its name until make clean' },
  LOG_FAILURES:      { default: false, type: 'boolean', doc: 'console.warn every unexpected status with its X-Trace-Id' },
  GATEWAY_URL:       { default: '',           doc: 'override deployment gatewayUrl' },
  UAA_URL:           { default: '',           doc: 'override deployment uaaUrl' },
  POD_ID:            { default: '',           doc: 'override deployment podId' },
  POD_DOMAIN:        { default: '',           doc: 'override deployment podDomain' },
  PROMETHEUS_URL:    { default: '',           doc: 'override deployment prometheusUrl (remote-write endpoint)' },
  SELLER_PASSWORD:   { default: '',           doc: 'password for every seeded seller account (deployed targets)' },
  SHOPPER_PASSWORD:  { default: '',           doc: 'password of the seeded shopper (deployed targets)' },
};

function coerce(spec, raw) {
  if (raw === undefined || raw === '') return spec.default;
  if (spec.type === 'number') {
    const n = Number(raw);
    if (Number.isNaN(n)) throw new Error(`env: expected a number, got ${raw}`);
    return n;
  }
  if (spec.type === 'boolean') return raw === '1' || raw === 'true';
  return raw;
}

/** Every declared variable, resolved. */
export const env = Object.keys(SCHEMA).reduce((out, key) => {
  out[key] = coerce(SCHEMA[key], __ENV[key]);
  return out;
}, {});

function selectStores(all) {
  const wanted = env.STORES.split(',').map((s) => s.trim()).filter(Boolean);
  const picked = wanted[0] === 'all' ? all : all.filter((s) => wanted.includes(s.name));
  if (picked.length === 0) throw new Error(`STORES=${env.STORES} matched nothing in k6/config/env/${env.TARGET}.json`);
  return picked;
}

function withPassword(account, override) {
  if (!account) return account;
  return Object.assign({}, account, { password: override || account.password });
}

function load() {
  const file = JSON.parse(open(`../../config/env/${env.TARGET}.json`));
  const podDomain = env.POD_DOMAIN || file.podDomain;
  const stores = file.stores.map((s) => Object.assign({}, s, {
    podId: file.podId,
    url: s.url || `http://${s.name}.${podDomain}`,
  }));
  const accounts = {};
  for (const key of Object.keys(file.accounts || {})) {
    accounts[key] = withPassword(file.accounts[key], key === 'shopper' ? env.SHOPPER_PASSWORD : env.SELLER_PASSWORD);
  }
  return {
    target: file.name || env.TARGET,
    gatewayUrl: env.GATEWAY_URL || file.gatewayUrl,
    uaaUrl: env.UAA_URL || file.uaaUrl,
    podId: env.POD_ID || file.podId,
    podDomain,
    lang: env.LANG_CODE || file.lang || 'en',
    prometheusUrl: env.PROMETHEUS_URL || file.prometheusUrl,
    rateLimitProfile: file.rateLimitProfile || 'default',
    hosts: file.hosts || {},
    allStores: stores,
    stores: selectStores(stores),
    accounts,
  };
}

/** The resolved deployment. Loaded once per VU at init. */
export const config = load();

/** Storefront URL of a store that is not in the deployment file (a fixture store). */
export function storeUrl(name) {
  return `http://${name}.${config.podDomain}`;
}

/** Round-robin a VU over the selected seeded stores. */
export function storeFor(vuId) {
  return config.stores[(vuId - 1) % config.stores.length];
}
