// Generated by grafana-k6 on 2026-09-05T07:41:35Z
/**
 * The single HTTP entry point of the suite. Every client method is one call to request().
 *
 * Contract: never throws on an HTTP status; returns { res, ok, status, body }. `expect` lists the statuses the
 * caller considers correct — they are registered with k6 as expected (so http_req_failed stays honest and the
 * request carries expected_response:true) and asserted by one check named after the request's `name` tag.
 * The `name` tag is mandatory and stable per endpoint (never contains ids), so metrics stay per-endpoint.
 */
import http from 'k6/http';
import { check } from 'k6';
import { env } from './env.js';
import { traceFailure } from './metrics.js';

const JSON_HEADERS = { 'Content-Type': 'application/json', Accept: 'application/json' };
const FORM_HEADERS = { 'Content-Type': 'application/x-www-form-urlencoded' };

export function withQuery(url, params) {
  const q = Object.keys(params || {})
    .filter((k) => params[k] !== undefined && params[k] !== null && params[k] !== '')
    .map((k) => `${encodeURIComponent(k)}=${encodeURIComponent(params[k])}`)
    .join('&');
  return q ? `${url}?${q}` : url;
}

export function jsonOrNull(res) {
  try {
    return res.json();
  } catch (e) {
    return null;
  }
}

function encodeBody(opts) {
  if (opts.body === undefined || opts.body === null) return { body: null, headers: {} };
  if (opts.form) return { body: opts.body, headers: FORM_HEADERS };
  return { body: JSON.stringify(opts.body), headers: JSON_HEADERS };
}

/**
 * @param edge     from core/edges.js
 * @param method   'GET' | 'POST' | ...
 * @param service  path prefix the edge maps ('catalog', 'tenancy', ...; ignored by uaaEdge/gatewayEdge)
 * @param path     '/api/v1/...'
 * @param opts     { name, expect: [200], params, body, form, headers, tags, redirects, timeout }
 */
export function request(edge, method, service, path, opts) {
  const o = opts || {};
  if (!o.name) throw new Error(`request ${method} ${path}: a name tag is required`);
  const expect = o.expect || [200];
  const url = withQuery(edge.url(service, path), Object.assign({}, edge.params, o.params));
  const encoded = encodeBody(o);
  const params = {
    headers: Object.assign({}, encoded.headers, edge.headers, o.headers),
    tags: Object.assign({ name: o.name, layer: edge.layer, store: edge.store ? edge.store.name : 'none' }, o.tags),
    responseCallback: http.expectedStatuses(...expect),
  };
  if (o.redirects !== undefined) params.redirects = o.redirects;
  if (o.timeout) params.timeout = o.timeout;

  const res = http.request(method, url, encoded.body, params);
  const ok = check(res, { [`${o.name} ${expect.join('|')}`]: (r) => expect.includes(r.status) });
  if (!ok) {
    traceFailure(o.name, res);
    if (env.LOG_FAILURES) {
      console.warn(`${o.name} ${method} ${url} -> ${res.status} trace=${res.headers['X-Trace-Id'] || '-'} ${String(res.body).slice(0, 200)}`);
    }
  }
  return { res, ok, status: res.status, body: jsonOrNull(res) };
}

export const get = (edge, service, path, opts) => request(edge, 'GET', service, path, opts);
export const post = (edge, service, path, opts) => request(edge, 'POST', service, path, opts);
export const put = (edge, service, path, opts) => request(edge, 'PUT', service, path, opts);
export const patch = (edge, service, path, opts) => request(edge, 'PATCH', service, path, opts);
export const del = (edge, service, path, opts) => request(edge, 'DELETE', service, path, opts);
