// Generated by grafana-k6 on 2026-09-05T07:42:23Z
/**
 * Every custom metric of the suite, plus the summary writer. Built-in per-endpoint latency comes from the
 * `name` tag on each request; the Trends here are per *journey* — the unit an SLO is written against.
 */
import { Counter, Rate, Trend } from 'k6/metrics';
import { textSummary } from 'https://jslib.k6.io/k6-summary/0.1.0/index.js';

export const journeyDuration = new Trend('journey_duration_ms', true);
export const journeyErrors = new Rate('journey_errors');
export const unexpectedStatus = new Counter('unexpected_status');
export const rateLimited = new Counter('rate_limited');
export const ordersPlaced = new Counter('orders_placed');
export const shoppersRegistered = new Counter('shoppers_registered');
export const shopperAuthDuration = new Trend('shopper_auth_ms', true);
export const sellerLogins = new Counter('seller_logins');
export const sellerLoginDuration = new Trend('seller_login_ms', true);
export const sellerSessionLost = new Counter('seller_session_lost');
export const fixtureProvisionDuration = new Trend('fixture_provision_ms', true);
export const storesCreated = new Counter('stores_created');
export const productsCreated = new Counter('products_created');
export const domainLookups = new Counter('domain_lookups');
export const browserErrors = new Counter('browser_errors');
export const planLimitHits = new Counter('plan_limit_hits');

/** Time and grade one journey. `ok` is the AND of every step. */
export function recordJourney(name, startedAt, ok) {
  journeyDuration.add(Date.now() - startedAt, { journey: name });
  journeyErrors.add(!ok, { journey: name });
}

/** Called by core/http.js on every unexpected status. Low cardinality: name + status only. */
export function traceFailure(name, res) {
  unexpectedStatus.add(1, { name, status: String(res.status) });
  if (res.status === 429) rateLimited.add(1, { name });
}

/** Run a journey body and record it; the body returns true when every step passed. */
export function journey(name, body) {
  const t0 = Date.now();
  let ok = false;
  try {
    ok = body() === true;
  } finally {
    recordJourney(name, t0, ok);
  }
  return ok;
}

/** Standard handleSummary: text to stdout, JSON to results/<testid>.json. Scripts re-export it. */
export function handleSummary(data) {
  const testid = (__ENV.TESTID || `k6-${Date.now()}`).replace(/[^A-Za-z0-9_.-]/g, '-');
  const out = { stdout: textSummary(data, { indent: '  ', enableColors: true }) };
  out[`results/${testid}.json`] = JSON.stringify(data, null, 2);
  return out;
}
