// Generated by grafana-k6 on 2026-09-05T07:42:23Z
/**
 * Shopper authentication against cua: authorization code + PKCE, the only grant the storefront client has.
 *
 *   GET  /cua/oauth2/authorize?...code_challenge=S256   → 302 to /<lang>/login?auth=1, sets SESSION (Path=/cua/) + XSRF-TOKEN
 *   POST /cua/login  username,password,client_id,lang,_csrf → 302 to /<lang>/callback?code=
 *   POST /cua/oauth2/token  authorization_code + code_verifier → access_token (15 min), refresh_token
 *
 * Everything is on the store host through spg, with this VU's cookie jar. The three hops are timed as one
 * `shopper_auth_ms`.
 */
import http from 'k6/http';
import crypto from 'k6/crypto';
import encoding from 'k6/encoding';
import { check } from 'k6';
import { config } from './env.js';
import { shopperAuthDuration } from './metrics.js';
import { jsonOrNull, withQuery } from './http.js';

function tag(name, store) {
  return { name, layer: 'shopper', store: store.name };
}

export function verifier() {
  return encoding.b64encode(crypto.randomBytes(48), 'rawurl');
}

export function challenge(v) {
  return crypto.sha256(v, 'base64rawurl');
}

function cookie(jar, url, name) {
  const all = jar.cookiesForURL(url);
  return all[name] ? all[name][0] : null;
}

/** Returns { accessToken, refreshToken, expiresIn } or null. */
export function loginShopper(store, username, password) {
  const started = Date.now();
  const lang = config.lang;
  const redirectUri = `${store.url}/${lang}/callback`;
  const jar = http.cookieJar();
  jar.clear(store.url);
  const v = verifier();

  const authorize = http.get(withQuery(`${store.url}/cua/oauth2/authorize`, {
    response_type: 'code', client_id: store.id, redirect_uri: redirectUri, scope: 'openid',
    code_challenge: challenge(v), code_challenge_method: 'S256', prompt: 'login', store: store.id, lang,
  }), { redirects: 0, tags: tag('cua:authorize', store) });
  let xsrf = cookie(jar, `${store.url}/`, 'XSRF-TOKEN');
  if (!xsrf) {
    // the token cookie is planted when the sign-in page is served; fetch it the way a browser would
    http.get(`${store.url}/${lang}/login?auth=1`, { tags: tag('page:login', store) });
    xsrf = cookie(jar, `${store.url}/`, 'XSRF-TOKEN');
  }
  const authorizeOk = check(authorize, {
    'cua:authorize 302': (r) => r.status === 302,
    'cua:authorize xsrf': () => xsrf !== null,
  });
  if (!authorizeOk) {
    shopperAuthDuration.add(Date.now() - started);
    return null;
  }

  // POST /cua/login → 302 authorize?…&continue (the saved request resumes) → 302 /<lang>/callback?code=
  const login = http.post(`${store.url}/cua/login`, {
    username, password, client_id: store.id, lang, _csrf: xsrf,
  }, { redirects: 0, tags: tag('cua:login', store) });
  let location = login.headers['Location'] || '';
  if (login.status === 302 && location.indexOf('/cua/oauth2/authorize') !== -1) {
    const resume = http.get(location, { redirects: 0, tags: tag('cua:authorize-continue', store) });
    location = resume.headers['Location'] || '';
  }
  const codeMatch = /[?&]code=([^&]+)/.exec(location);
  const loginOk = check(login, {
    'cua:login 302': (r) => r.status === 302,
    'cua:login code': () => codeMatch !== null,
  });
  if (!loginOk) {
    shopperAuthDuration.add(Date.now() - started);
    return null;
  }

  const token = http.post(`${store.url}/cua/oauth2/token`, {
    grant_type: 'authorization_code', code: decodeURIComponent(codeMatch[1]), redirect_uri: redirectUri,
    client_id: store.id, code_verifier: v,
  }, { tags: tag('cua:token', store) });
  const body = jsonOrNull(token);
  const tokenOk = check(token, {
    'cua:token 200': (r) => r.status === 200,
    'cua:token access_token': () => body !== null && !!body.access_token,
  });
  shopperAuthDuration.add(Date.now() - started);
  if (!tokenOk) return null;
  return { accessToken: body.access_token, refreshToken: body.refresh_token, expiresIn: body.expires_in };
}

export function refreshShopper(store, refreshToken) {
  const token = http.post(`${store.url}/cua/oauth2/token`, {
    grant_type: 'refresh_token', refresh_token: refreshToken, client_id: store.id,
  }, { tags: tag('cua:refresh', store) });
  const body = jsonOrNull(token);
  const ok = check(token, { 'cua:refresh 200': (r) => r.status === 200 });
  return ok && body ? { accessToken: body.access_token, refreshToken: body.refresh_token || refreshToken } : null;
}

export function bearer(tokens) {
  return { Authorization: `Bearer ${tokens.accessToken}` };
}
