// Generated by grafana-k6 on 2026-09-05T07:42:23Z
/**
 * Seller (console) sessions. The gateway is an OAuth2 client of uaa and holds the session in memory:
 *   GET  /oauth2/authorization/uaa   → redirects through /uaa/oauth2/authorize, plants XSRF-TOKEN, lands on the console sign-in
 *   POST /uaa/login  username,password,_csrf   → uaa resumes the authorize request → gateway sets STORE-CORE-GATEWAY-JSESSIONID
 *
 * The login endpoint is rate-limited on deployed targets (10/min per realm and address), so load scripts log a
 * small pool in at setup() and VUs share the cookie values; a VU never logs in on its own inside a load loop.
 */
import http from 'k6/http';
import { check } from 'k6';
import { config } from './env.js';
import { SESSION_COOKIE } from './edges.js';
import { sellerLogins, sellerLoginDuration, sellerSessionLost } from './metrics.js';

const TAG = (name) => ({ tags: { name, layer: 'platform', store: 'none' } });

function cookie(jar, name) {
  const all = jar.cookiesForURL(`${config.gatewayUrl}/`);
  return all[name] ? all[name][0] : null;
}

/** Logs in through the gateway. Returns { username, role, cookie } or null. Uses this VU's cookie jar. */
export function login(account) {
  const started = Date.now();
  // a previous login in this VU left the gateway session (Path=/) and uaa's own session (Path=/uaa) behind;
  // with uaa's still there the authorize hop answers with a code and never shows the form
  const jar = http.cookieJar();
  jar.clear(config.gatewayUrl);
  jar.clear(`${config.gatewayUrl}/uaa`);
  jar.clear(`${config.gatewayUrl}/uaa/`);
  jar.clear(config.uaaUrl);

  // hop 1: the gateway starts the flow; hop 2: uaa saves the authorize request and plants XSRF-TOKEN.
  // Stop there — the third hop is the console's sign-in page, which is not part of authentication.
  const start = http.get(`${config.gatewayUrl}/oauth2/authorization/uaa`, Object.assign({ redirects: 1 }, TAG('seller:login-start')));
  const xsrf = cookie(jar, 'XSRF-TOKEN');
  const startOk = check(start, {
    'seller:login-start 302': (r) => r.status === 302,
    'seller:login-start xsrf': () => xsrf !== null,
  });
  if (!startOk) {
    sellerLoginDuration.add(Date.now() - started);
    return null;
  }

  // POST /uaa/login → 302 authorize?continue → 302 /login/oauth2/code/uaa?code= → the gateway sets the session
  // and 302s to the console. Two redirects land exactly on the gateway's callback response.
  const submit = http.post(`${config.gatewayUrl}/uaa/login`, {
    username: account.username, password: account.password, _csrf: xsrf,
  }, Object.assign({ redirects: 2 }, TAG('seller:login-submit')));
  const session = cookie(jar, SESSION_COOKIE);
  const ok = check(submit, {
    'seller:login-submit 302': (r) => r.status === 302 || r.status === 200,
    'seller:login session cookie': () => session !== null,
  });
  sellerLoginDuration.add(Date.now() - started);
  if (!ok) return null;
  sellerLogins.add(1);
  return { username: account.username, role: account.role, cookie: session };
}

/** Is this session still accepted by the gateway? (in-memory sessions die with a gateway restart) */
export function alive(session) {
  const res = http.get(`${config.gatewayUrl}/uaa/api/v1/auth/me`, {
    headers: { Cookie: `${SESSION_COOKIE}=${session.cookie}` },
    tags: { name: 'seller:me', layer: 'platform', store: 'none' },
    redirects: 0,
  });
  if (res.status !== 200) sellerSessionLost.add(1);
  return res.status === 200;
}

/**
 * Logs `count` sessions in for setup(). Accounts cycle through the list given (so two entries of the same
 * account produce two independent sessions). Throws when nothing could log in: every dependent script is
 * meaningless without a session.
 */
export function sessionPool(accounts, count) {
  const sessions = [];
  for (let i = 0; i < count; i += 1) {
    const s = login(accounts[i % accounts.length]);
    if (s) sessions.push(s);
  }
  if (sessions.length === 0) throw new Error('session pool: no seller account could log in');
  return sessions;
}

/** Pick this VU's session from the pool. */
export function sessionFor(sessions, vuId) {
  return sessions[(vuId - 1) % sessions.length];
}
