// Generated by grafana-k6 on 2026-09-05T07:42:23Z
/**
 * Global tags every sample carries, so one Prometheus/Grafana filter isolates a run, a layer or a target.
 * Keep the set small and low-cardinality: ids, urls and per-VU values never become tags.
 */
import { env, config } from './env.js';

export function globalTags(layer, script) {
  const testid = __ENV.TESTID || `${script || 'k6'}-${env.RUN_ID}`;
  return { testid, layer, target: config.target, profile: env.PROFILE };
}
