// Generated by grafana-k6 on 2026-09-05T07:42:23Z
/**
 * Polling for asynchronous platform work (store provisioning runs off an outbox, so "created" is not "ready").
 * Only for setup()/teardown() and admin journeys; never inside a hot loop.
 */
import { sleep } from 'k6';

/** Calls fn until it returns a truthy value or the timeout elapses. Returns the value or null. */
export function pollUntil(fn, opts) {
  const o = Object.assign({ timeout: 60, interval: 2, label: 'condition' }, opts || {});
  const deadline = Date.now() + o.timeout * 1000;
  let attempt = 0;
  while (Date.now() < deadline) {
    attempt += 1;
    const value = fn(attempt);
    if (value) return value;
    sleep(o.interval);
  }
  console.error(`pollUntil: ${o.label} not met within ${o.timeout}s`);
  return null;
}
