// The twelve dashboards, as data. `node build-dashboards.mjs` renders them to ../grafana/dashboards/<folder>/<uid>.json
// and `node dashboard-docs.mjs` documents every panel in ../docs/dashboards.md. Change a panel here, run both, commit
// all three. Queries use the series named in ../docs/signals.md and the rules in ../prometheus-rules.
import {
  custom, dashLink, dashboard, gauge, heatmap, logs, lokiLink, lokiSeries, lokiStat, lokiTable, row, serviceMap, stat, table,
  tagAnnotations, tempoLink, textbox, timeseries, traceql, variable,
} from './lib.mjs';

const SVC = 'service_name=~"$service"';
const NOISE = 'uri!~"/actuator.*|UNKNOWN|root"';
const RATE = '$__rate_interval';

const serviceVar = variable('service', 'Service', 'label_values(http_server_requests_seconds_count, service_name)');
const uriVar = variable('uri', 'Route', 'label_values(http_server_requests_seconds_count{service_name=~"$service"}, uri)');
const lokiSvcVar = variable('lsvc', 'Service', 'label_values({service_name=~".+"}, service_name)', {datasource: {type: 'loki', uid: 'loki'}});
const tempoSvcVar = variable('tsvc', 'Service', 'label_values(traces_span_metrics_calls_total, service_name)');

const toRed = (svc = '${__field.labels.service_name}') => dashLink('Service RED', 'cvhome-service-red', {service: svc});
const errorTraces = (svc = '${__field.labels.service_name}') =>
  tempoLink('Error traces', `{resource.service.name="${svc}" && span:kind=server && status=error}`);
const errorLogs = (svc = '${__field.labels.service_name}') =>
  lokiLink('Error logs', `{service_name="${svc}"} | detected_level=~"error|warn"`);

const statusStat = (code, label, what) => stat(`${label}`, what,
  `sum(increase(http_server_requests_seconds_count{${SVC},uri=~"$uri",status${code.includes('.') ? '=~' : '='}"${code}"}[$__range])) or vector(0)`,
  {w: 3, h: 4, unit: 'short', graph: false, thresholds: code.startsWith('5') ? [1, 10] : [50, 200],
    links: [tempoLink(`${label} traces`, `{resource.service.name=~"$service" && span:kind=server && span.http.response.status_code ${code.includes('.') ? '>= 500' : '= ' + code}}`),
      lokiLink(`${label} log lines`, `{service_name=~"$service"} |~ "${code.includes('.') ? '5[0-9][0-9]' : code} "`)]});

// ───────────────────────────────────────────────────────────── platform ──
const overview = dashboard('cvhome-platform-overview', 'Platform Overview', 'platform',
  'Is the platform healthy right now? One page: are we inside our SLOs, which service is burning its error budget, and what is firing.',
  [
    row('Service level'),
    stat('Availability (1h)', 'Share of requests answered without a 5xx over the last hour, all services together. SLO 99.9 %.',
      `1 - (sum(rate(http_server_requests_seconds_count{status=~"5..",${NOISE}}[1h])) or vector(0)) / sum(rate(http_server_requests_seconds_count{${NOISE}}[1h]))`,
      {unit: 'percentunit', decimals: 3, min: 0.99, max: 1, thresholds: [0.999, 0.995], graph: false, w: 4, h: 5,
        overrides: [{matcher: {id: 'byName', options: 'Value'}, properties: [{id: 'thresholds', value: {mode: 'absolute', steps: [{color: 'red', value: null}, {color: 'orange', value: 0.995}, {color: 'green', value: 0.999}]}}]}]}),
    stat('Storefront latency SLO', 'Share of storefront reads (catalog, content, merchant, inventory GETs) answered under 500 ms. SLO 95 %.',
      'min(cvhome:slo_latency_storefront:good_ratio_rate5m)',
      {unit: 'percentunit', min: 0.8, max: 1, graph: false, w: 4, h: 5,
        overrides: [{matcher: {id: 'byName', options: 'Value'}, properties: [{id: 'thresholds', value: {mode: 'absolute', steps: [{color: 'red', value: null}, {color: 'orange', value: 0.9}, {color: 'green', value: 0.95}]}}]}]}),
    stat('Checkout latency SLO', 'Share of checkout and payment writes answered under 2 s. SLO 95 %.',
      'min(cvhome:slo_latency_checkout:good_ratio_rate5m)',
      {unit: 'percentunit', min: 0.8, max: 1, graph: false, w: 4, h: 5,
        overrides: [{matcher: {id: 'byName', options: 'Value'}, properties: [{id: 'thresholds', value: {mode: 'absolute', steps: [{color: 'red', value: null}, {color: 'orange', value: 0.9}, {color: 'green', value: 0.95}]}}]}]}),
    stat('Services reporting', 'How many services sent metrics in the last 2 minutes. 12 Java services are expected.',
      'count(count by (service_name) (process_uptime_seconds))', {unit: 'short', graph: false, w: 4, h: 5,
        overrides: [{matcher: {id: 'byName', options: 'Value'}, properties: [{id: 'thresholds', value: {mode: 'absolute', steps: [{color: 'red', value: null}, {color: 'orange', value: 11}, {color: 'green', value: 12}]}}]}]}),
    stat('Firing alerts', 'Number of alert rules currently firing (see the table at the bottom).',
      'count(ALERTS{alertstate="firing"}) or vector(0)', {unit: 'short', graph: false, w: 4, h: 5, thresholds: [1, 3]}),
    stat('Requests / s', 'Total request rate across all services, health probes excluded.',
      `sum(rate(http_server_requests_seconds_count{${NOISE}}[${RATE}]))`, {unit: 'reqps', w: 4, h: 5}),

    row('Error budget'),
    timeseries('Availability burn rate (1h and 6h windows)', 'How fast each service is spending its 5xx error budget. 1 = exactly on budget; above 14.4 for an hour means the month\'s budget is gone in two days.',
      [['max by (service_name) (cvhome:slo_availability:burn_rate1h)', '{{service_name}} 1h'],
        ['max by (service_name) (cvhome:slo_availability:burn_rate6h)', '{{service_name}} 6h']],
      {unit: 'short', thresholds: [6, 14.4], links: [toRed()]}),
    timeseries('Storefront latency burn rate', 'Same idea for the latency SLO: how fast the "5 % may be slower than 500 ms" budget is spent.',
      [['cvhome:slo_latency_storefront:burn_rate1h', '{{service_name}}']], {unit: 'short', thresholds: [6, 14.4], links: [toRed()]}),

    row('Traffic and errors'),
    timeseries('Requests / s by service', 'Traffic per service. A drop to zero on one service while the others keep going is a dead service.',
      [[`sum by (service_name) (rate(http_server_requests_seconds_count{${NOISE}}[${RATE}]))`, '{{service_name}}']],
      {unit: 'reqps', stack: true, links: [toRed()]}),
    timeseries('Responses / s by status class', 'What the platform is answering: 2xx good, 4xx the caller\'s problem (or auth), 5xx ours.',
      [[`sum by (status) (rate(http_server_requests_seconds_count{status=~"5..",${NOISE}}[${RATE}]))`, '5xx {{status}}'],
        [`sum by (status) (rate(http_server_requests_seconds_count{status=~"4..",${NOISE}}[${RATE}]))`, '4xx {{status}}']],
      {unit: 'reqps', stack: true}),
    timeseries('p95 latency by service (server spans)', 'The slowest 5 % of requests per service, including spg and landing-ui. Compare against the SLO lines of the storefront (0.5 s) and checkout (2 s).',
      [['cvhome:span_server:p95_5m', '{{service_name}}']], {unit: 's', thresholds: [0.5, 2], links: [toRed()]}),
    timeseries('5xx ratio by service', 'Share of each service\'s requests that failed on our side.',
      [['cvhome:http_server_errors:ratio_rate5m', '{{service_name}}']], {unit: 'percentunit', thresholds: [0.001, 0.01], links: [toRed(), errorTraces(), errorLogs()]}),

    row('Per service'),
    table('Service table', 'Every service on one line: traffic, failure share, latency, pool and CPU. Click a service name for its RED dashboard.',
      [[`sum by (service_name) (rate(http_server_requests_seconds_count{${NOISE}}[5m]))`, 'req/s'],
        ['cvhome:http_server_errors:ratio_rate5m', '5xx ratio'],
        ['cvhome:span_server:p95_5m', 'p95 (s)'],
        ['cvhome:hikari_pool:utilisation', 'pool used'],
        ['cvhome:tomcat_threads:utilisation', 'threads busy'],
        ['cvhome:jvm_cpu:ratio', 'cpu'],
        ['cvhome:jvm_heap_after_gc:ratio', 'heap after gc']],
      {sortBy: '5xx ratio', h: 12, overrides: [
        {matcher: {id: 'byName', options: '5xx ratio'}, properties: [{id: 'unit', value: 'percentunit'}, {id: 'custom.cellOptions', value: {type: 'color-background'}}, {id: 'thresholds', value: {mode: 'absolute', steps: [{color: 'green', value: null}, {color: 'orange', value: 0.001}, {color: 'red', value: 0.01}]}}]},
        {matcher: {id: 'byName', options: 'p95 (s)'}, properties: [{id: 'unit', value: 's'}, {id: 'custom.cellOptions', value: {type: 'color-background'}}, {id: 'thresholds', value: {mode: 'absolute', steps: [{color: 'green', value: null}, {color: 'orange', value: 0.5}, {color: 'red', value: 2}]}}]},
        {matcher: {id: 'byName', options: 'pool used'}, properties: [{id: 'unit', value: 'percentunit'}, {id: 'custom.cellOptions', value: {type: 'color-background'}}, {id: 'thresholds', value: {mode: 'absolute', steps: [{color: 'green', value: null}, {color: 'orange', value: 0.6}, {color: 'red', value: 0.8}]}}]},
        {matcher: {id: 'byName', options: 'threads busy'}, properties: [{id: 'unit', value: 'percentunit'}, {id: 'custom.cellOptions', value: {type: 'color-background'}}, {id: 'thresholds', value: {mode: 'absolute', steps: [{color: 'green', value: null}, {color: 'orange', value: 0.6}, {color: 'red', value: 0.8}]}}]},
        {matcher: {id: 'byName', options: 'cpu'}, properties: [{id: 'unit', value: 'percentunit'}, {id: 'custom.cellOptions', value: {type: 'color-background'}}, {id: 'thresholds', value: {mode: 'absolute', steps: [{color: 'green', value: null}, {color: 'orange', value: 0.6}, {color: 'red', value: 0.8}]}}]},
        {matcher: {id: 'byName', options: 'heap after gc'}, properties: [{id: 'unit', value: 'percentunit'}, {id: 'custom.cellOptions', value: {type: 'color-background'}}, {id: 'thresholds', value: {mode: 'absolute', steps: [{color: 'green', value: null}, {color: 'orange', value: 0.7}, {color: 'red', value: 0.85}]}}]},
        {matcher: {id: 'byName', options: 'req/s'}, properties: [{id: 'unit', value: 'reqps'}, {id: 'decimals', value: 2}]},
        {matcher: {id: 'byName', options: 'service_name'}, properties: [{id: 'links', value: [dashLink('Service RED', 'cvhome-service-red', {service: '${__value.raw}'})]}]},
      ]}),
    serviceMap('Service map', 'Who calls whom, from the traces: every edge is a service-to-service or database call with its rate and failure count.'),
    row('Alerts'),
    table('Firing alerts', 'Alert rules in the firing state, with their labels. Meaning and first steps: docs/alerts.md.',
      [['ALERTS{alertstate="firing"}', 'firing']], {h: 8}),
  ],
  {links: [dashLink('Service RED', 'cvhome-service-red'), dashLink('Bottlenecks', 'cvhome-bottlenecks'), dashLink('Service-to-Service', 'cvhome-service-to-service'), dashLink('Database & SQL', 'cvhome-database-sql'), dashLink('Logs & Errors', 'cvhome-logs-errors')]});

const red = dashboard('cvhome-service-red', 'Service RED', 'platform',
  'Rate, Errors, Duration for one service (or several): what it is asked, how often it fails and with which status, how slow it is per route.',
  [
    row('Rate'),
    timeseries('Requests / s by route', 'Traffic per route of the selected service.',
      [[`sum by (method, uri) (rate(http_server_requests_seconds_count{${SVC},uri=~"$uri",${NOISE}}[${RATE}]))`, '{{method}} {{uri}}']], {unit: 'reqps', stack: true}),
    timeseries('Responses / s by status', 'Every status code the service answered with. A new colour appearing is a new failure mode.',
      [[`sum by (status) (rate(http_server_requests_seconds_count{${SVC},uri=~"$uri"}[${RATE}]))`, '{{status}}']], {unit: 'reqps', stack: true}),
    row('Errors by status (selected time range)'),
    statusStat('400', '400 Bad Request', 'Requests the service rejected as malformed or invalid (validation errors). Coming from our own frontends this is a bug in the caller.'),
    statusStat('401', '401 Unauthorized', 'Requests with no or an invalid token. A bare 401 from the JWT filter carries no body and no route (uri="UNKNOWN").'),
    statusStat('403', '403 Forbidden', 'Authenticated callers that lack the permission. A silent spike usually means a permission token with no case in CustomPermissionEvaluator.'),
    statusStat('404', '404 Not Found', 'Unknown resource or route.'),
    statusStat('409', '409 Conflict', 'Optimistic-locking and uniqueness conflicts (duplicate SKU, stale layout version).'),
    statusStat('422', '422 Unprocessable', 'Business-rule refusals, including provider rejections re-emitted as ours and plan-limit hits.'),
    statusStat('429', '429 Too Many', 'The rate limiter engaging (uaa/cua login and public POSTs).'),
    statusStat('5..', '5xx Server error', 'Failures on our side. Every one of these counts against the availability SLO.'),
    table('Failed routes', 'Which route fails with which status and exception, most frequent first. Click a row to open matching traces.',
      [[`sum by (service_name, method, uri, status, exception) (increase(http_server_requests_seconds_count{${SVC},uri=~"$uri",status=~"4..|5.."}[$__range])) > 0`, 'count']],
      {sortBy: 'count', h: 9, overrides: [{matcher: {id: 'byName', options: 'uri'}, properties: [{id: 'links', value: [tempoLink('Traces for this route', '{resource.service.name="${__data.fields.service_name}" && span.http.route="${__data.fields.uri}" && span.http.response.status_code=${__data.fields.status}}')]}]}]}),
    row('Duration'),
    timeseries('Latency p50 / p95 / p99', 'How slow requests are for most callers (p50), for the slow tail (p95) and for the worst (p99). Storefront SLO 0.5 s, checkout 2 s.',
      [[`histogram_quantile(0.50, sum by (le) (rate(http_server_requests_seconds_bucket{${SVC},uri=~"$uri",${NOISE}}[${RATE}])))`, 'p50'],
        [`histogram_quantile(0.95, sum by (le) (rate(http_server_requests_seconds_bucket{${SVC},uri=~"$uri",${NOISE}}[${RATE}])))`, 'p95'],
        [`histogram_quantile(0.99, sum by (le) (rate(http_server_requests_seconds_bucket{${SVC},uri=~"$uri",${NOISE}}[${RATE}])))`, 'p99']],
      {unit: 's', thresholds: [0.5, 2], links: [tempoLink('Slow traces', '{resource.service.name=~"$service" && span:kind=server && duration > 500ms}')]}),
    heatmap('Latency distribution', 'Where requests land in time: a band moving up is everything getting slower; a second band appearing is one route or one dependency getting slow.',
      `sum by (le) (rate(http_server_requests_seconds_bucket{${SVC},uri=~"$uri",${NOISE}}[${RATE}]))`),
    table('Slowest routes (p95)', 'Routes ordered by their p95 over the last 5 minutes.',
      [[`topk(15, cvhome:http_server_requests:p95_5m{${SVC},uri=~"$uri"})`, 'p95 (s)']],
      {sortBy: 'p95 (s)', h: 9, overrides: [{matcher: {id: 'byName', options: 'p95 (s)'}, properties: [{id: 'unit', value: 's'}, {id: 'custom.cellOptions', value: {type: 'color-background'}}, {id: 'thresholds', value: {mode: 'absolute', steps: [{color: 'green', value: null}, {color: 'orange', value: 0.5}, {color: 'red', value: 2}]}}]}]}),
    row('Why'),
    timeseries('Exceptions / s by class', 'Which exception classes the service is throwing to its callers.',
      [[`sum by (exception) (rate(http_server_requests_seconds_count{${SVC},exception!="none"}[${RATE}]))`, '{{exception}}']], {unit: 'reqps'}),
    timeseries('Server spans in error / s by name', 'The same failures seen from the traces, per span name; useful for non-HTTP work (scheduled tasks, outbox handlers).',
      [[`sum by (span_name) (rate(traces_span_metrics_calls_total{${SVC},span_kind="SPAN_KIND_SERVER",status_code="STATUS_CODE_ERROR"}[${RATE}]))`, '{{span_name}}']], {unit: 'reqps'}),
    timeseries('Auth rejections / s', '401 and 403 by reason, counted where they are decided (the JWT filter or the permission evaluator) — present once the cvhome_auth_rejections meter ships.',
      [[`sum by (status, reason) (rate(cvhome_auth_rejections_total{${SVC}}[${RATE}]))`, '{{status}} {{reason}}']], {unit: 'reqps'}),
    logs('Error and warning logs', 'The service\'s own error and warning lines for the time range; each line links to its trace.',
      '{service_name=~"$service"} | detected_level=~"error|warn"', {h: 12}),
  ],
  {variables: [serviceVar, uriVar], links: [dashLink('Overview', 'cvhome-platform-overview'), dashLink('Database & SQL', 'cvhome-database-sql', {service: '$service'}), dashLink('JVM & Runtime', 'cvhome-jvm-runtime', {service: '$service'}), dashLink('Bottlenecks', 'cvhome-bottlenecks', {service: '$service'})]});

const s2s = dashboard('cvhome-service-to-service', 'Service-to-Service', 'platform',
  'The calls between services: which edges exist, how often each fails, how slow it is from the caller\'s side. Built from the traces (service graph) and the HTTP client meters.',
  [
    serviceMap('Service map', 'Every caller → callee edge seen in the traces. Node colour follows the failure share; edge labels show rate and failures.'),
    table('Edges', 'One row per caller → callee edge with its call rate, failure share and p95 as the caller sees it.',
      [['cvhome:s2s:rate5m', 'calls/s'], ['cvhome:s2s_failed:ratio_rate5m', 'failed'], ['cvhome:s2s:p95_5m', 'p95 (s)']],
      {sortBy: 'failed', h: 10, overrides: [
        {matcher: {id: 'byName', options: 'failed'}, properties: [{id: 'unit', value: 'percentunit'}, {id: 'custom.cellOptions', value: {type: 'color-background'}}, {id: 'thresholds', value: {mode: 'absolute', steps: [{color: 'green', value: null}, {color: 'orange', value: 0.005}, {color: 'red', value: 0.05}]}}]},
        {matcher: {id: 'byName', options: 'p95 (s)'}, properties: [{id: 'unit', value: 's'}, {id: 'custom.cellOptions', value: {type: 'color-background'}}, {id: 'thresholds', value: {mode: 'absolute', steps: [{color: 'green', value: null}, {color: 'orange', value: 0.5}, {color: 'red', value: 2}]}}]},
        {matcher: {id: 'byName', options: 'calls/s'}, properties: [{id: 'unit', value: 'reqps'}]},
        {matcher: {id: 'byName', options: 'server'}, properties: [{id: 'links', value: [tempoLink('Failed calls on this edge', '{resource.service.name="${__data.fields.client}" && span:kind=client && status=error}')]}]},
      ]}),
    timeseries('Failure share by edge', 'Share of calls on each edge that failed. Anything above 0.5 % sustained is a broken dependency.',
      [['cvhome:s2s_failed:ratio_rate5m', '{{client}} → {{server}}']], {unit: 'percentunit', thresholds: [0.005, 0.05]}),
    timeseries('p95 by edge (caller side)', 'How long the caller waits for each callee, slow tail.',
      [['cvhome:s2s:p95_5m', '{{client}} → {{server}}']], {unit: 's', thresholds: [0.5, 2]}),
    timeseries('Calls / s by edge', 'Traffic on each edge.', [['cvhome:s2s:rate5m', '{{client}} → {{server}}']], {unit: 'reqps', stack: true}),
    timeseries('Outgoing HTTP errors by destination', 'From the caller\'s HTTP client: responses that came back 4xx/5xx, by destination host and status.',
      [[`sum by (service_name, server_address, http_response_status_code) (rate(http_client_request_duration_seconds_count{http_response_status_code=~"4..|5.."}[${RATE}]))`, '{{service_name}} → {{server_address}} {{http_response_status_code}}']], {unit: 'reqps'}),
    table('Outgoing transport failures', 'Calls that got no HTTP answer at all (connection refused, timeout), by exception type. These are the RemoteServiceException 502s.',
      [[`sum by (service_name, server_address, error_type) (increase(http_client_request_duration_seconds_count{error_type!=""}[$__range])) > 0`, 'count']], {sortBy: 'count', h: 8}),
    timeseries('Database edges: calls / s', 'Each service\'s traffic to the database as the service graph sees it.',
      [[`sum by (client) (rate(traces_service_graph_request_total{connection_type="database"}[${RATE}]))`, '{{client}}']], {unit: 'reqps', stack: true}),
    table('Unknown peers', 'Edges to or from something that sent no spans (a browser, k6, or a host without instrumentation). Useful to spot an uninstrumented dependency.',
      [[`sum by (client, server) (rate(traces_service_graph_request_total{connection_type="virtual_node"}[5m]))`, 'calls/s']], {h: 7}),
  ],
  {links: [dashLink('Overview', 'cvhome-platform-overview'), dashLink('Traces', 'cvhome-traces')]});

const jvm = dashboard('cvhome-jvm-runtime', 'JVM & Runtime', 'platform',
  'The Java runtime of each service: memory, garbage collection, threads, CPU, file handles. The place to look for leaks and undersized heaps during a soak.',
  [
    timeseries('Heap used by pool', 'Live heap per memory pool. A sawtooth is healthy; a floor that keeps rising across GCs is a leak.',
      [[`sum by (service_name, jvm_memory_pool_name) (jvm_memory_used_bytes{${SVC},jvm_memory_type="heap"})`, '{{service_name}} {{jvm_memory_pool_name}}']], {unit: 'bytes', stack: true}),
    timeseries('Heap after GC vs limit', 'Live data after the last collection as a share of the maximum heap. Above 85 % the JVM spends its time collecting instead of serving.',
      [['cvhome:jvm_heap_after_gc:ratio', '{{service_name}}']], {unit: 'percentunit', thresholds: [0.7, 0.85]}),
    timeseries('Non-heap used', 'Metaspace, code cache and compressed class space.',
      [[`sum by (service_name, jvm_memory_pool_name) (jvm_memory_used_bytes{${SVC},jvm_memory_type="non_heap"})`, '{{service_name}} {{jvm_memory_pool_name}}']], {unit: 'bytes'}),
    timeseries('GC pause share', 'Share of wall-clock time the JVM was paused for garbage collection.',
      [['cvhome:jvm_gc_pause:ratio5m', '{{service_name}}']], {unit: 'percentunit', thresholds: [0.02, 0.05]}),
    timeseries('GC pause p95', 'Slow tail of individual GC pauses, per collector.',
      [[`histogram_quantile(0.95, sum by (service_name, jvm_gc_name, le) (rate(jvm_gc_duration_seconds_bucket{${SVC}}[${RATE}])))`, '{{service_name}} {{jvm_gc_name}}']], {unit: 's', thresholds: [0.1, 0.5]}),
    timeseries('GC collections / s', 'How often each collector runs.',
      [[`sum by (service_name, jvm_gc_name, jvm_gc_action) (rate(jvm_gc_duration_seconds_count{${SVC}}[${RATE}]))`, '{{service_name}} {{jvm_gc_name}} {{jvm_gc_action}}']], {unit: 'ops'}),
    timeseries('Threads', 'Live JVM threads. Steadily climbing = a pool that is never bounded.',
      [[`max by (service_name) (jvm_thread_count{${SVC}})`, '{{service_name}}']], {unit: 'short'}),
    timeseries('CPU', 'CPU used by each JVM process, and the whole machine.',
      [[`max by (service_name) (jvm_cpu_recent_utilization_ratio{${SVC}})`, '{{service_name}} process'], ['max(system_cpu_usage)', 'system']], {unit: 'percentunit', thresholds: [0.6, 0.8], max: 1}),
    timeseries('Load average (1m)', 'Runnable threads on the machine; above the CPU count means queueing.',
      [['max(system_load_average_1m)', 'load 1m'], ['max(system_cpu_count)', 'cpus']], {unit: 'short'}),
    timeseries('Open file descriptors', 'Sockets and files held open, against the limit. Climbing towards the limit means connections are not being closed.',
      [[`max by (service_name) (process_files_open{${SVC}})`, '{{service_name}} open'], [`max by (service_name) (process_files_max{${SVC}})`, '{{service_name}} max']], {unit: 'short'}),
    timeseries('Loaded classes', 'Classes loaded in the JVM; growth after start-up hints at class-generation leaks (proxies, scripts).',
      [[`max by (service_name) (jvm_class_count{${SVC}})`, '{{service_name}}']], {unit: 'short'}),
    stat('Uptime', 'Time since the JVM started. A reset is a restart.',
      `max by (service_name) (process_uptime_seconds{${SVC}})`, {unit: 's', legend: '{{service_name}}', w: 12, h: 8, graph: false, links: [lokiLink('Start-up log', '{service_name=~"$service"} |= "Started"')]}),
  ],
  {variables: [serviceVar], links: [dashLink('Bottlenecks', 'cvhome-bottlenecks', {service: '$service'}), dashLink('Service RED', 'cvhome-service-red', {service: '$service'})]});

const bottlenecks = dashboard('cvhome-bottlenecks', 'Bottlenecks', 'platform',
  'Where is the system saturating? Every resource that can run out — request threads, database connections, CPU, GC, executor queues, caches — as a share of its limit, next to traffic and latency, so the first one to hit its ceiling under load is obvious.',
  [
    row('Saturation matrix'),
    table('Saturation by service', 'Each resource as a share of its limit, per service. Red is the bottleneck.',
      [['cvhome:tomcat_threads:utilisation', 'request threads'], ['cvhome:hikari_pool:utilisation', 'db pool'], ['cvhome:hikari_pending:max', 'db waiting'],
        ['cvhome:jvm_cpu:ratio', 'cpu'], ['cvhome:jvm_gc_pause:ratio5m', 'gc time'], ['cvhome:jvm_heap_after_gc:ratio', 'heap after gc'],
        ['cvhome:sql_per_request:ratio5m', 'sql / request']],
      {h: 12, sortBy: 'request threads', overrides: ['request threads', 'db pool', 'cpu', 'gc time', 'heap after gc'].map((c) => ({
        matcher: {id: 'byName', options: c}, properties: [{id: 'unit', value: 'percentunit'}, {id: 'custom.cellOptions', value: {type: 'color-background'}},
          {id: 'thresholds', value: {mode: 'absolute', steps: [{color: 'green', value: null}, {color: 'orange', value: c === 'gc time' ? 0.02 : 0.6}, {color: 'red', value: c === 'gc time' ? 0.05 : 0.8}]}}]}))
        .concat([{matcher: {id: 'byName', options: 'db waiting'}, properties: [{id: 'custom.cellOptions', value: {type: 'color-background'}}, {id: 'thresholds', value: {mode: 'absolute', steps: [{color: 'green', value: null}, {color: 'red', value: 1}]}}]},
          {matcher: {id: 'byName', options: 'sql / request'}, properties: [{id: 'decimals', value: 1}, {id: 'custom.cellOptions', value: {type: 'color-background'}}, {id: 'thresholds', value: {mode: 'absolute', steps: [{color: 'green', value: null}, {color: 'orange', value: 5}, {color: 'red', value: 10}]}}]}])}),
    row('The knee'),
    timeseries('Traffic vs p95', 'Request rate (left axis) against p95 latency (right axis). The point where the rate flattens while p95 climbs is the capacity of the system as configured.',
      [[`sum(rate(http_server_requests_seconds_count{${SVC},${NOISE}}[${RATE}]))`, 'req/s'], [`max(cvhome:span_server:p95_5m{${SVC}})`, 'p95'], ['max(k6_vus)', 'k6 VUs']],
      {unit: 'reqps', w: 24, h: 9, overrides: [{matcher: {id: 'byName', options: 'p95'}, properties: [{id: 'unit', value: 's'}, {id: 'custom.axisPlacement', value: 'right'}, {id: 'color', value: {mode: 'fixed', fixedColor: 'red'}}]},
        {matcher: {id: 'byName', options: 'k6 VUs'}, properties: [{id: 'custom.axisPlacement', value: 'hidden'}, {id: 'custom.lineStyle', value: {fill: 'dash', dash: [4, 4]}}, {id: 'color', value: {mode: 'fixed', fixedColor: 'purple'}}]}]}),
    row('Request threads (Tomcat)'),
    timeseries('Request threads busy / max', 'Threads serving requests against the configured maximum. At the max, new requests queue in the connector.',
      [[`max by (service_name) (tomcat_threads_busy{${SVC}})`, '{{service_name}} busy'], [`max by (service_name) (tomcat_threads_config_max{${SVC}})`, '{{service_name}} max']], {unit: 'short'}),
    timeseries('Request thread utilisation', 'Busy share of the request thread pool.', [['cvhome:tomcat_threads:utilisation', '{{service_name}}']], {unit: 'percentunit', thresholds: [0.6, 0.8]}),
    timeseries('Connections', 'Open connections on the HTTP connector against its maximum.',
      [[`max by (service_name) (tomcat_connections_current{${SVC}})`, '{{service_name}} current'], [`max by (service_name) (tomcat_connections_config_max{${SVC}})`, '{{service_name}} max']], {unit: 'short'}),
    timeseries('Executor pools', 'Async and scheduler executors: active threads and queued tasks. A growing queue is work arriving faster than it is done.',
      [[`sum by (service_name, name) (executor_active_threads{${SVC}})`, '{{service_name}} {{name}} active'], [`sum by (service_name, name) (executor_queued_tasks{${SVC}})`, '{{service_name}} {{name}} queued']], {unit: 'short'}),
    row('Database pool'),
    timeseries('Waiting for a connection', 'Threads blocked waiting for a pooled connection. Any value above zero means the pool is the bottleneck.',
      [['cvhome:hikari_pending:max', '{{service_name}}']], {unit: 'short', thresholds: [1, 3]}),
    timeseries('Pool utilisation', 'Connections in use as a share of the pool (5 per service locally, 10 on Fargate).', [['cvhome:hikari_pool:utilisation', '{{service_name}}']], {unit: 'percentunit', thresholds: [0.6, 0.8]}),
    row('Caches'),
    timeseries('Cache hit ratio', 'Share of cache reads served from the cache, per cache (present once recordStats is on).',
      [[`sum by (service_name, cache) (rate(cache_gets_total{${SVC},result="hit"}[${RATE}])) / sum by (service_name, cache) (rate(cache_gets_total{${SVC}}[${RATE}]))`, '{{service_name}} {{cache}}']], {unit: 'percentunit'}),
    timeseries('Cache size and evictions', 'Entries held and evictions per second. Evictions with a low hit ratio mean the cache is too small.',
      [[`sum by (service_name, cache) (cache_size{${SVC}})`, '{{service_name}} {{cache}} size'], [`sum by (service_name, cache) (rate(cache_evictions_total{${SVC}}[${RATE}]))`, '{{service_name}} {{cache}} evictions/s']], {unit: 'short'}),
    row('Telemetry pipeline'),
    timeseries('Collector exporter', 'Spans and metrics the collector received vs exported. A gap is the collector dropping data (memory limiter).',
      [['sum by (exporter) (rate(otlp_exporter_seen_total[$__rate_interval]))', '{{exporter}} seen'], ['sum by (exporter) (rate(otlp_exporter_exported_total[$__rate_interval]))', '{{exporter}} exported']], {unit: 'ops'}),
    stat('Collector scrape', 'Whether Prometheus can reach the collector\'s metrics endpoint (1 = yes).', 'up{job="otel-collector"}', {unit: 'short', graph: false, thresholds: [0, 1], overrides: [{matcher: {id: 'byName', options: 'Value'}, properties: [{id: 'thresholds', value: {mode: 'absolute', steps: [{color: 'red', value: null}, {color: 'green', value: 1}]}}]}]}),
  ],
  {variables: [serviceVar], links: [dashLink('Overview', 'cvhome-platform-overview'), dashLink('Database & SQL', 'cvhome-database-sql', {service: '$service'}), dashLink('JVM & Runtime', 'cvhome-jvm-runtime', {service: '$service'}), dashLink('Load test vs app', 'cvhome-load-test-vs-app')]});

// ───────────────────────────────────────────────────────────────── data ──
const sql = dashboard('cvhome-database-sql', 'Database & SQL', 'data',
  'The database side of every service: the connection pool, how many statements each request costs, and how slow each statement family is. Built from Hikari meters and the JDBC client spans.',
  [
    row('Connection pool'),
    timeseries('Pool: active / idle / pending / max', 'Connections in use, spare, threads waiting, and the ceiling. Pending above zero is exhaustion.',
      [[`max by (service_name) (hikaricp_connections_active{${SVC}})`, '{{service_name}} active'], [`max by (service_name) (hikaricp_connections_idle{${SVC}})`, '{{service_name}} idle'],
        [`max by (service_name) (hikaricp_connections_pending{${SVC}})`, '{{service_name}} pending'], [`max by (service_name) (hikaricp_connections_max{${SVC}})`, '{{service_name}} max']], {unit: 'short'}),
    gauge('Pool utilisation', 'Connections in use as a share of the pool.', `cvhome:hikari_pool:utilisation{${SVC}}`, {thresholds: [0.6, 0.8]}),
    stat('Connection timeouts', 'Requests that gave up waiting for a connection in the selected range. Must be zero.',
      `sum(increase(hikaricp_connections_timeout_total{${SVC}}[$__range]))`, {unit: 'short', graph: false, w: 6, h: 6, thresholds: [1, 5]}),
    timeseries('Time to get a connection (p95)', 'How long a request waits for a pooled connection. Rises before pending does.',
      [['cvhome:hikari_acquire:p95_5m', '{{service_name}}']], {unit: 's', thresholds: [0.01, 0.1]}),
    timeseries('Time a connection is held (p95)', 'How long each borrowed connection is kept. Long holds with short statements mean long transactions or work done while holding a connection.',
      [[`histogram_quantile(0.95, sum by (service_name, le) (rate(hikaricp_connections_usage_seconds_bucket{${SVC}}[${RATE}])))`, '{{service_name}}']], {unit: 's', thresholds: [0.1, 1]}),
    row('Statements'),
    timeseries('Statements / s by operation and table', 'Database traffic per service, split by operation and table.',
      [[`sum by (db_operation, db_sql_table) (cvhome:sql:rate5m{${SVC}})`, '{{db_operation}} {{db_sql_table}}']], {unit: 'ops', stack: true}),
    timeseries('Statement p95 by family', 'Slow tail per statement family ("SELECT catalog.product"). Target: under 100 ms.',
      [[`cvhome:sql:p95_5m{${SVC}}`, '{{service_name}} {{span_name}}']], {unit: 's', thresholds: [0.1, 0.5], links: [tempoLink('Slow statements', '{resource.service.name=~"$service" && span.db.system="postgresql" && duration > 100ms}')]}),
    heatmap('Statement latency distribution', 'Where statements land in time.', `sum by (le) (rate(traces_span_metrics_duration_seconds_bucket{${SVC},span_kind="SPAN_KIND_CLIENT",db_system="postgresql"}[${RATE}]))`),
    timeseries('Statements per request', 'Average number of statements each incoming request costs. Above 10 is almost always an N+1 loop.',
      [[`cvhome:sql_per_request:ratio5m{${SVC}}`, '{{service_name}}']], {unit: 'short', thresholds: [5, 10]}),
    table('Top statements', 'Statement families by rate, with their p95 and error rate. Click a name to see the traces behind it.',
      [[`topk(20, sum by (service_name, span_name) (rate(traces_span_metrics_calls_total{${SVC},span_kind="SPAN_KIND_CLIENT",db_system="postgresql"}[5m])))`, 'calls/s'],
        [`cvhome:sql:p95_5m{${SVC}}`, 'p95 (s)'], [`cvhome:sql_errors:rate5m{${SVC}}`, 'errors/s']],
      {sortBy: 'calls/s', h: 11, overrides: [
        {matcher: {id: 'byName', options: 'p95 (s)'}, properties: [{id: 'unit', value: 's'}, {id: 'custom.cellOptions', value: {type: 'color-background'}}, {id: 'thresholds', value: {mode: 'absolute', steps: [{color: 'green', value: null}, {color: 'orange', value: 0.1}, {color: 'red', value: 0.5}]}}]},
        {matcher: {id: 'byName', options: 'calls/s'}, properties: [{id: 'unit', value: 'ops'}, {id: 'decimals', value: 2}]},
        {matcher: {id: 'byName', options: 'span_name'}, properties: [{id: 'links', value: [tempoLink('Traces with this statement', '{resource.service.name="${__data.fields.service_name}" && name="${__data.fields.span_name}"}')]}]}]}),
    traceql('N+1 suspects', 'Requests that ran more than 20 statements in one trace.', '{resource.service.name=~"$service" && span.db.system="postgresql"} | count() > 20', {w: 12, h: 9}),
    table('Schema changes at runtime', 'DDL statements (CREATE/ALTER) after start-up. schema.sql runs at boot; anything later is ddl-auto: update doing what the DDL file should.',
      [[`sum by (service_name, span_name) (increase(traces_span_metrics_calls_total{${SVC},db_operation=~"CREATE|ALTER|DROP"}[$__range])) > 0`, 'count']], {w: 12, h: 9}),
    timeseries('JDBC connections (DataSource view)', 'The same pool seen through the JDBC meters; a mismatch with the Hikari view is a second DataSource.',
      [[`max by (service_name) (jdbc_connections_active{${SVC}})`, '{{service_name}} active'], [`max by (service_name) (jdbc_connections_max{${SVC}})`, '{{service_name}} max']], {unit: 'short'}),
  ],
  {variables: [serviceVar], links: [dashLink('Bottlenecks', 'cvhome-bottlenecks', {service: '$service'}), dashLink('Traces', 'cvhome-traces')]});

const outbox = dashboard('cvhome-outbox-events', 'Outbox & Events', 'data',
  'The transactional outbox that carries domain events between services: is it keeping up, is anything stuck or failed, how long does processing take.',
  [
    timeseries('Outbox records by status', 'Records waiting, processing, done and failed per service (present once the outbox meter ships). A growing NEW count is a consumer falling behind.',
      [[`max by (service_name, status) (cvhome_outbox_records{${SVC}})`, '{{service_name}} {{status}}']], {unit: 'short', stack: true}),
    timeseries('Oldest pending record', 'Age of the oldest record still waiting. The lag a downstream service sees.',
      [[`max by (service_name) (cvhome_outbox_oldest_pending_seconds{${SVC}})`, '{{service_name}}']], {unit: 's', thresholds: [60, 300]}),
    timeseries('Outbox polling / s', 'How often each service touches its outbox tables (the poller reads outbox_partition/outbox_instance every 2 s, and each shipped record is an UPDATE). Zero means the scheduler is not running.',
      [[`sum by (service_name) (rate(traces_span_metrics_calls_total{${SVC},span_kind="SPAN_KIND_CLIENT",db_sql_table=~"outbox_.*"}[${RATE}]))`, '{{service_name}}']], {unit: 'ops'}),
    timeseries('Outbox statement p95', 'Slow tail of the outbox table statements; a poll slower than its 2 s interval is the backlog growing.',
      [[`histogram_quantile(0.95, sum by (service_name, le) (rate(traces_span_metrics_duration_seconds_bucket{${SVC},span_kind="SPAN_KIND_CLIENT",db_sql_table=~"outbox_.*"}[${RATE}])))`, '{{service_name}}']], {unit: 's', thresholds: [0.5, 2]}),
    timeseries('Outbox statement errors / s', 'Outbox table statements that failed.',
      [[`sum by (service_name, span_name) (rate(traces_span_metrics_calls_total{${SVC},span_kind="SPAN_KIND_CLIENT",db_sql_table=~"outbox_.*",status_code="STATUS_CODE_ERROR"}[${RATE}]))`, '{{service_name}} {{span_name}}']], {unit: 'ops', thresholds: [0.01, 0.1]}),
    timeseries('Outbox table statements / s', 'Database traffic on the outbox tables.',
      [[`sum by (service_name, db_operation) (rate(traces_span_metrics_calls_total{${SVC},db_sql_table=~".*outbox.*"}[${RATE}]))`, '{{service_name}} {{db_operation}}']], {unit: 'ops', stack: true}),
    traceql('Failed background work', 'Scheduled and internal work (outbox handlers, partition rebalance, expiry and recovery jobs) that failed, latest first.', '{resource.service.name=~"$service" && span:kind=internal && status=error}', {w: 12, h: 9}),
    logs('Outbox log lines', 'Everything the services log about the outbox, warnings and errors first.', '{service_name=~"$service"} |~ "(?i)outbox" | detected_level=~"error|warn"', {w: 12, h: 9}),
  ],
  {variables: [serviceVar], links: [dashLink('Database & SQL', 'cvhome-database-sql', {service: '$service'})]});

// ───────────────────────────────────────────────────────────────── edge ──
const edge = dashboard('cvhome-edge', 'Edge: spg & landing-ui', 'edge',
  'The shopper-facing edge: the pod gateway (spg) per route and the storefront (landing-ui) page renders and their upstream calls. Built from the spans, since neither runs Micrometer.',
  [
    row('spg (pod gateway)'),
    timeseries('spg requests / s by route', 'Traffic through the pod gateway per routed service.',
      [[`sum by (span_name) (rate(traces_span_metrics_calls_total{service_name="spg",span_kind="SPAN_KIND_SERVER"}[${RATE}]))`, '{{span_name}}']], {unit: 'reqps', stack: true}),
    timeseries('spg p95 by route', 'Slow tail per routed service as the gateway sees it (includes the upstream).',
      [[`histogram_quantile(0.95, sum by (span_name, le) (rate(traces_span_metrics_duration_seconds_bucket{service_name="spg",span_kind="SPAN_KIND_SERVER"}[${RATE}])))`, '{{span_name}}']], {unit: 's', thresholds: [0.5, 2]}),
    timeseries('spg responses / s by status', 'Status codes the gateway returned.',
      [[`sum by (http_response_status_code) (rate(traces_span_metrics_calls_total{service_name="spg",span_kind="SPAN_KIND_SERVER"}[${RATE}]))`, '{{http_response_status_code}}']], {unit: 'reqps', stack: true}),
    timeseries('spg errors / s by route', 'Gateway spans that ended in error, per route.',
      [[`sum by (span_name) (rate(traces_span_metrics_calls_total{service_name="spg",span_kind="SPAN_KIND_SERVER",status_code="STATUS_CODE_ERROR"}[${RATE}]))`, '{{span_name}}']], {unit: 'reqps'}),
    row('landing-ui (storefront)'),
    timeseries('Page renders / s', 'Server-side renders per page pattern.',
      [[`sum by (span_name) (rate(traces_span_metrics_calls_total{service_name="landing-ui",span_kind="SPAN_KIND_SERVER"}[${RATE}]))`, '{{span_name}}']], {unit: 'reqps', stack: true}),
    timeseries('Page render p95', 'Slow tail of a server-side render, per page pattern. Storefront page SLO 3 s (dev server locally).',
      [[`histogram_quantile(0.95, sum by (span_name, le) (rate(traces_span_metrics_duration_seconds_bucket{service_name="landing-ui",span_kind="SPAN_KIND_SERVER"}[${RATE}])))`, '{{span_name}}']], {unit: 's', thresholds: [1, 3]}),
    timeseries('Upstream fetch p95 by call', 'How long the storefront waits for each backend call it makes while rendering.',
      [[`histogram_quantile(0.95, sum by (span_name, le) (rate(traces_span_metrics_duration_seconds_bucket{service_name="landing-ui",span_kind="SPAN_KIND_CLIENT",span_name=~"fetch .*"}[${RATE}])))`, '{{span_name}}']], {unit: 's', thresholds: [0.5, 2]}),
    timeseries('Upstream fetch errors / s', 'Backend calls from the storefront that failed.',
      [[`sum by (span_name) (rate(traces_span_metrics_calls_total{service_name="landing-ui",span_kind="SPAN_KIND_CLIENT",span_name=~"fetch .*",status_code="STATUS_CODE_ERROR"}[${RATE}]))`, '{{span_name}}']], {unit: 'reqps'}),
    stat('Distinct span names (landing-ui)', 'Cardinality guard: how many different span names the storefront emits. Above 200 means URLs are leaking into names again.',
      'count(count by (span_name) (traces_span_metrics_calls_total{service_name="landing-ui"}))', {unit: 'short', graph: false, w: 6, thresholds: [100, 200]}),
    row('Browser (k6 web vitals, last run)'),
    stat('LCP p75', 'Largest Contentful Paint as measured by k6 browser runs. Target under 4 s locally.', 'max(max_over_time(k6_browser_web_vital_lcp_p75[$__range]))', {unit: 's', graph: false, w: 4, thresholds: [2.5, 4]}),
    stat('CLS p75', 'Cumulative Layout Shift. Target under 0.1.', 'max(max_over_time(k6_browser_web_vital_cls_p75[$__range]))', {unit: 'short', graph: false, w: 4, thresholds: [0.1, 0.25]}),
    stat('INP p75', 'Interaction to Next Paint. Target under 200 ms.', 'max(max_over_time(k6_browser_web_vital_inp_p75[$__range]))', {unit: 's', graph: false, w: 4, thresholds: [0.2, 0.5]}),
    stat('TTFB p75', 'Time To First Byte. Target under 1.5 s locally.', 'max(max_over_time(k6_browser_web_vital_ttfb_p75[$__range]))', {unit: 's', graph: false, w: 4, thresholds: [0.8, 1.5]}),
  ],
  {links: [dashLink('Overview', 'cvhome-platform-overview'), dashLink('Load test vs app', 'cvhome-load-test-vs-app')]});

const auth = dashboard('cvhome-auth', 'Auth', 'edge',
  'Identity and access: the two authorization servers (uaa for staff, cua for shoppers), the gateway sign-in, and where 401/403 come from across the platform.',
  [
    row('Rejections'),
    timeseries('401 / 403 by service', 'Auth rejections per service. 401 = no valid token, 403 = valid token without the permission.',
      [['cvhome:http_server_auth_rejections:rate5m', '{{service_name}} {{status}}']], {unit: 'reqps', stack: true}),
    timeseries('Bare 401s (no route)', '401s decided by the JWT filter before routing: they carry no body and no route. A burst here is an expired or wrong-issuer token in a client.',
      [[`sum by (service_name) (rate(http_server_requests_seconds_count{status="401",uri="UNKNOWN"}[${RATE}]))`, '{{service_name}}']], {unit: 'reqps'}),
    timeseries('Rejections by reason', 'Where each rejection was decided and why (present once the cvhome_auth_rejections meter ships).',
      [[`sum by (service_name, status, reason, source) (rate(cvhome_auth_rejections_total[${RATE}]))`, '{{service_name}} {{status}} {{reason}} ({{source}})']], {unit: 'reqps'}),
    timeseries('429 rate limited', 'The login rate limiter and public-POST limiter engaging.',
      [[`sum by (service_name, uri) (rate(http_server_requests_seconds_count{status="429"}[${RATE}]))`, '{{service_name}} {{uri}}']], {unit: 'reqps'}),
    row('Authorization servers'),
    timeseries('Token / authorize / login requests / s', 'Traffic on the OAuth2 endpoints of uaa and cua.',
      [[`sum by (service_name, uri, status) (rate(http_server_requests_seconds_count{service_name=~"uaa|cua",uri=~"/oauth2/.*|/login.*|/api/v1/public/registration"}[${RATE}]))`, '{{service_name}} {{uri}} {{status}}']], {unit: 'reqps', stack: true}),
    timeseries('Token endpoint p95', 'How long issuing a token takes. Login SLO 2.5 s end to end.',
      [[`histogram_quantile(0.95, sum by (service_name, uri, le) (rate(http_server_requests_seconds_bucket{service_name=~"uaa|cua",uri=~"/oauth2/token|/oauth2/authorize|/login.*"}[${RATE}])))`, '{{service_name}} {{uri}}']], {unit: 's', thresholds: [1, 2.5]}),
    timeseries('JWKS fetches by clients', 'Resource servers fetching signing keys. A steady stream instead of a trickle means key caching is broken.',
      [[`sum by (service_name, server_address) (rate(http_client_request_duration_seconds_count{server_address=~"uaa.*|cua.*|.*gateway.com"}[${RATE}]))`, '{{service_name}} → {{server_address}}']], {unit: 'reqps'}),
    row('Gateway'),
    timeseries('Gateway sign-in and session', 'Seller sign-in traffic through store-core-gateway, and its in-memory session count (present once the session gauge ships).',
      [[`sum by (uri, status) (rate(http_server_requests_seconds_count{service_name="store-core-gateway",uri=~"/login.*|/oauth2/.*"}[${RATE}]))`, '{{uri}} {{status}}'], ['max(cvhome_gateway_sessions)', 'sessions']], {unit: 'reqps', overrides: [{matcher: {id: 'byName', options: 'sessions'}, properties: [{id: 'unit', value: 'short'}, {id: 'custom.axisPlacement', value: 'right'}]}]}),
    timeseries('Billing guard (402) and relay failures at the gateway', 'Requests the gateway refused for a lapsed subscription (402) or could not relay (5xx).',
      [[`sum by (status) (rate(http_server_requests_seconds_count{service_name="store-core-gateway",status=~"402|5.."}[${RATE}]))`, '{{status}}']], {unit: 'reqps'}),
    logs('Authentication failures (log)', 'Failed sign-ins and token problems as logged by uaa, cua and the gateway.',
      '{service_name=~"uaa|cua|store-core-gateway"} |~ "(?i)authentication failed|bad credentials|invalid_grant|invalid_token|access denied|rate.?limit"', {h: 10}),
  ],
  {links: [dashLink('Service RED', 'cvhome-service-red'), dashLink('Logs & Errors', 'cvhome-logs-errors')]});

// ──────────────────────────────────────────────────────── observability ──
const logsDash = dashboard('cvhome-logs-errors', 'Logs & Errors', 'observability',
  'What the services are saying: error volume per service, the most frequent error messages and exception classes, and a searchable log view where every line links to its trace.',
  [
    lokiSeries('Log lines / s by level', 'Volume per level. A jump in error or warn is the first sign of trouble even before a metric moves.',
      [['sum by (detected_level) (count_over_time({service_name=~"$lsvc"} | detected_level=~"$level" [$__auto]))', '{{detected_level}}']], {unit: 'short'}),
    lokiSeries('Error lines / s by service', 'Which service is producing the errors.',
      [['sum by (service_name) (count_over_time({service_name=~"$lsvc"} | detected_level="error" [$__auto]))', '{{service_name}}']], {unit: 'short'}),
    lokiTable('Top error messages', 'The most frequent error messages (first 80 characters) in the selected range.',
      'topk(20, sum by (service_name, msg) (count_over_time({service_name=~"$lsvc"} | detected_level="error" | regexp "^(?P<msg>.{0,80})" [$__range])))', {h: 10}),
    lokiTable('Exception classes', 'Exception class names found in error and warning lines, most frequent first.',
      'topk(20, sum by (service_name, ex) (count_over_time({service_name=~"$lsvc"} | detected_level=~"error|warn" | regexp "(?P<ex>[A-Za-z0-9_.$]+(Exception|Error))" [$__range])))', {h: 10}),
    lokiTable('Error codes returned to callers', 'The error codes the @ControllerAdvice logged ("CATALOG.PRODUCT.NOT_FOUND [traceId=…]"), most frequent first.',
      'topk(20, sum by (service_name, code) (count_over_time({service_name=~"$lsvc"} |~ "\\\\[traceId=" | regexp "^(?P<code>[0-9]{3} [A-Z_]+|[A-Z][A-Z_.]+) \\\\[traceId=" [$__range])))', {h: 10}),
    lokiTable('Remote and provider failures', 'Calls to a peer service (RemoteServiceException) or a third party (ExternalProviderException) that failed.',
      'sum by (service_name, ex) (count_over_time({service_name=~"$lsvc"} | regexp "(?P<ex>RemoteServiceException|ExternalProviderException|[A-Za-z]+ApiUnavailableException)" [$__range]))', {h: 10}),
    lokiStat('Observation scope-leak warnings', 'Count of the "Observation … is not the same as the one set as this scope\'s parent" warning. It must be zero; it was firing on every scheduled refresh of the gateway before the fix.',
      'sum(count_over_time({service_name=~".+"} |= "ObservationThreadLocalAccessor" [$__range]))', {unit: 'short', w: 6, thresholds: [1, 10]}),
    logs('Logs', 'The log view. Filter by service, level and free text; expand a line and click "View trace" to open its trace in Tempo.',
      '{service_name=~"$lsvc"} | detected_level=~"$level" |~ "$search"', {h: 16}),
  ],
  {variables: [lokiSvcVar, custom('level', 'Level', ['error|warn|info|debug', 'error', 'error|warn', 'info', 'debug'], 'error|warn|info|debug'), textbox('search', 'Contains', '')],
    links: [dashLink('Traces', 'cvhome-traces'), dashLink('Service RED', 'cvhome-service-red')]});

const traces = dashboard('cvhome-traces', 'Traces', 'observability',
  'Ready-made trace searches: the slowest requests, the failed ones, the failed service-to-service calls, the slow SQL. Each row opens the full trace, with its log lines one click away.',
  [
    traceql('Slow requests (> 500 ms)', 'Server spans slower than the storefront SLO, slowest first.', '{resource.service.name=~"$tsvc" && span:kind=server && duration > 500ms}', {limit: 30}),
    traceql('Failed requests', 'Server spans that ended in error.', '{resource.service.name=~"$tsvc" && span:kind=server && status=error}', {limit: 30}),
    traceql('5xx responses', 'Requests answered with a server error.', '{resource.service.name=~"$tsvc" && span:kind=server && span.http.response.status_code >= 500}'),
    traceql('403 and 404 responses', 'Requests refused for permission or an unknown resource.', '{resource.service.name=~"$tsvc" && span:kind=server && (span.http.response.status_code = 403 || span.http.response.status_code = 404)}'),
    traceql('Failed service-to-service calls', 'Client spans (one service calling another) that failed, with the destination.', '{resource.service.name=~"$tsvc" && span:kind=client && status=error && span.db.system = nil}'),
    traceql('Slow SQL (> 100 ms)', 'Individual statements slower than 100 ms.', '{resource.service.name=~"$tsvc" && span.db.system="postgresql" && duration > 100ms}'),
    traceql('Statement-heavy requests', 'Traces with more than 20 statements: N+1 candidates.', '{resource.service.name=~"$tsvc" && span.db.system="postgresql"} | count() > 20'),
    traceql('Failed background work', 'Scheduled and internal work (outbox handlers, jobs) that failed.', '{resource.service.name=~"$tsvc" && span:kind=internal && status=error}'),
    table('Busiest server spans', 'Span names by rate with their error share, from the span metrics. Click a name to search its traces.',
      [[`topk(25, sum by (service_name, span_name) (rate(traces_span_metrics_calls_total{service_name=~"$tsvc",span_kind="SPAN_KIND_SERVER"}[5m])))`, 'calls/s'],
        [`sum by (service_name, span_name) (rate(traces_span_metrics_calls_total{service_name=~"$tsvc",span_kind="SPAN_KIND_SERVER",status_code="STATUS_CODE_ERROR"}[5m])) / sum by (service_name, span_name) (rate(traces_span_metrics_calls_total{service_name=~"$tsvc",span_kind="SPAN_KIND_SERVER"}[5m]))`, 'error share']],
      {sortBy: 'calls/s', h: 11, overrides: [
        {matcher: {id: 'byName', options: 'error share'}, properties: [{id: 'unit', value: 'percentunit'}, {id: 'custom.cellOptions', value: {type: 'color-background'}}, {id: 'thresholds', value: {mode: 'absolute', steps: [{color: 'green', value: null}, {color: 'orange', value: 0.001}, {color: 'red', value: 0.01}]}}]},
        {matcher: {id: 'byName', options: 'span_name'}, properties: [{id: 'links', value: [tempoLink('Search these spans', '{resource.service.name="${__data.fields.service_name}" && name="${__data.fields.span_name}"}')]}]}]}),
  ],
  {variables: [tempoSvcVar], links: [dashLink('Logs & Errors', 'cvhome-logs-errors'), dashLink('Service-to-Service', 'cvhome-service-to-service')]});

// ───────────────────────────────────────────────────────── load testing ──
const k6 = 'testid="$testid"';
const loadTest = dashboard('cvhome-load-test-vs-app', 'Load test vs app', 'load-testing',
  'One k6 run (pick the testid) next to what the application did during it, on the same time axis: where the load went, where latency broke, which resource ran out first.',
  [
    row('The run'),
    stat('Peak VUs', 'Highest number of virtual users in the run.', `max(max_over_time(k6_vus{${k6}}[$__range]))`, {unit: 'short', graph: false, w: 4}),
    stat('Requests', 'Requests k6 sent.', `sum(increase(k6_http_reqs_total{${k6}}[$__range]))`, {unit: 'short', graph: false, w: 4}),
    stat('Failed share', 'Share of requests k6 counted as failed (unexpected status), from the request counters over the whole run. SLO: under 1 %.', `(sum(max_over_time(k6_http_reqs_total{${k6},expected_response="false"}[$__range])) or vector(0)) / sum(max_over_time(k6_http_reqs_total{${k6}}[$__range]))`, {unit: 'percentunit', graph: false, w: 4, thresholds: [0.01, 0.05]}),
    stat('Dropped iterations', 'Iterations an open-model scenario could not start because every VU was busy: the load generator, not the app, hit its limit.', `sum(max_over_time(k6_dropped_iterations_total{${k6}}[$__range])) or vector(0)`, {unit: 'short', graph: false, w: 4, thresholds: [1, 10]}),
    stat('Orders placed', 'Orders the run created.', `max(max_over_time(k6_orders_placed_total{${k6}}[$__range])) or vector(0)`, {unit: 'short', graph: false, w: 4}),
    stat('Journey errors', 'Share of user journeys that failed at any step (average of k6\'s per-flush rate over the run).', `avg(avg_over_time(k6_journey_errors_rate{${k6}}[$__range]))`, {unit: 'percentunit', graph: false, w: 4, thresholds: [0.02, 0.05]}),
    row('Load and latency, k6 side'),
    timeseries('VUs and requests / s (k6)', 'The load shape: virtual users and the request rate they achieved. Rate flattening while VUs climb is the system saturating.',
      [[`max(k6_vus{${k6}})`, 'VUs'], [`sum(rate(k6_http_reqs_total{${k6}}[30s]))`, 'req/s']], {unit: 'reqps', overrides: [{matcher: {id: 'byName', options: 'VUs'}, properties: [{id: 'unit', value: 'short'}, {id: 'custom.axisPlacement', value: 'right'}]}]}),
    timeseries('k6 p95 by endpoint', 'Latency as the user saw it per endpoint name. Thresholds per name live in load-testing/k6/config/thresholds.js (product 0.5 s, search 0.8 s, checkout 2 s, pages 3 s).',
      [[`max by (name) (k6_http_req_duration_p95{${k6},expected_response="true",name=~"$name"})`, '{{name}}']], {unit: 's', thresholds: [0.5, 2]}),
    timeseries('k6 failures / s by endpoint and status', 'Requests with an unexpected status. 429 = the limiter, 402 = the billing guard, 5xx = the platform.',
      [[`sum by (name, status) (rate(k6_http_reqs_total{${k6},expected_response="false"}[30s]))`, '{{name}} {{status}}']], {unit: 'reqps', stack: true}),
    timeseries('Journeys p95', 'End-to-end time of each user journey (home, product, purchase, …).',
      [[`max by (journey) (k6_journey_duration_ms_p95{${k6}})`, '{{journey}}']], {unit: 's', thresholds: [3, 5]}),
    row('What the application did'),
    timeseries('App requests / s by service', 'Server-side traffic per service during the run.',
      [[`sum by (service_name) (rate(http_server_requests_seconds_count{${SVC},${NOISE}}[30s]))`, '{{service_name}}']], {unit: 'reqps', stack: true}),
    timeseries('App p95 by service', 'Server-side latency per service (30 s windows).',
      [[`histogram_quantile(0.95, sum by (service_name, le) (rate(http_server_requests_seconds_bucket{${SVC},${NOISE}}[30s])))`, '{{service_name}}']], {unit: 's', thresholds: [0.5, 2]}),
    timeseries('App 5xx / s by service', 'Server errors during the run.',
      [[`sum by (service_name) (rate(http_server_requests_seconds_count{${SVC},status=~"5.."}[30s]))`, '{{service_name}}']], {unit: 'reqps'}),
    timeseries('Service-to-service failure share', 'Edges that started failing under load.', [['cvhome:s2s_failed:ratio_rate5m', '{{client}} → {{server}}']], {unit: 'percentunit', thresholds: [0.005, 0.05]}),
    row('What ran out'),
    timeseries('Saturation: threads, pool, cpu, gc', 'Every limit as a share, on one axis. The first line to reach 0.8 is the bottleneck of this run.',
      [['cvhome:tomcat_threads:utilisation', '{{service_name}} threads'], ['cvhome:hikari_pool:utilisation', '{{service_name}} pool'], ['cvhome:jvm_cpu:ratio', '{{service_name}} cpu'], ['cvhome:jvm_gc_pause:ratio5m', '{{service_name}} gc']],
      {unit: 'percentunit', thresholds: [0.6, 0.8], w: 24, h: 9, max: 1}),
    timeseries('Waiting for a database connection', 'Threads blocked on the pool. Above zero the pool is the bottleneck.', [['cvhome:hikari_pending:max', '{{service_name}}']], {unit: 'short', thresholds: [1, 3]}),
    timeseries('Statements per request and SQL p99', 'Query cost per request, and the slow tail of SQL, during the run.',
      [['cvhome:sql_per_request:ratio5m', '{{service_name}} sql/req'], ['cvhome:sql:p99_5m', '{{service_name}} sql p99']], {unit: 'short', overrides: [{matcher: {id: 'byRegexp', options: '.* sql p99'}, properties: [{id: 'unit', value: 's'}, {id: 'custom.axisPlacement', value: 'right'}]}]}),
    timeseries('Heap after GC', 'Live heap share during a soak: a rising floor is a leak.', [['cvhome:jvm_heap_after_gc:ratio', '{{service_name}}']], {unit: 'percentunit', thresholds: [0.7, 0.85]}),
    logs('Application errors during the run', 'Error lines from the selected services while the run was going.', '{service_name=~"$service"} | detected_level="error"', {h: 10}),
  ],
  {variables: [variable('testid', 'Test run', 'label_values(k6_http_reqs_total, testid)', {all: false, multi: false, sort: 2}),
    variable('name', 'Endpoint', 'label_values(k6_http_reqs_total{testid="$testid"}, name)'), serviceVar],
    annotations: [tagAnnotations('k6 runs', ['k6'])], time: 'now-3h', refresh: '30s',
    links: [dashLink('Bottlenecks', 'cvhome-bottlenecks'), dashLink('Service RED', 'cvhome-service-red'), dashLink('Database & SQL', 'cvhome-database-sql')]});

export default [overview, red, s2s, jvm, bottlenecks, sql, outbox, edge, auth, logsDash, traces, loadTest];
