#!/usr/bin/env node
// Validates every dashboard JSON under ../grafana/dashboards and documents it in docs/monitoring/dashboards.md — one section
// per dashboard, one row per panel: what it answers, its type, its query, unit and thresholds. The documentation is
// the provider-neutral description of every graph: anyone can rebuild a panel from its row.
//   node dashboard-docs.mjs          write docs/monitoring/dashboards.md
//   node dashboard-docs.mjs --check  validate and fail if docs/monitoring/dashboards.md is out of date (CI)
import {readdirSync, readFileSync, writeFileSync, existsSync, statSync} from 'node:fs';
import {dirname, join, relative} from 'node:path';
import {fileURLToPath} from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..', 'grafana', 'dashboards');
const docFile = join(here, '..', '..', '..', 'docs', 'monitoring', 'dashboards.md');
const check = process.argv.includes('--check');
const KNOWN_DS = new Set(['prometheus', 'loki', 'tempo', 'grafana', '-- Grafana --']);

const files = [];
(function walk(dir) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p); else if (name.endsWith('.json')) files.push(p);
  }
})(root);
files.sort();

const problems = [];
const uids = new Set();
const dashboards = files.map((file) => {
  const rel = relative(root, file);
  let d;
  try { d = JSON.parse(readFileSync(file, 'utf8')); } catch (e) { problems.push(`${rel}: not JSON (${e.message})`); return null; }
  if (d.id !== null) problems.push(`${rel}: "id" must be null`);
  if (!d.uid) problems.push(`${rel}: missing uid`);
  if (uids.has(d.uid)) problems.push(`${rel}: duplicate uid ${d.uid}`);
  uids.add(d.uid);
  if (!d.title) problems.push(`${rel}: missing title`);
  if (d.editable !== false) problems.push(`${rel}: must be editable: false (git is the source)`);
  if (JSON.stringify(d).includes('${DS_')) problems.push(`${rel}: contains a ${'${DS_'}...} input; reference datasources by uid`);
  const panels = (d.panels ?? []).flatMap((p) => [p, ...(p.panels ?? [])]);
  for (const p of panels) {
    if (p.type === 'row') continue;
    if (!p.title) problems.push(`${rel}: panel ${p.id} has no title`);
    if (!p.description) problems.push(`${rel}: panel "${p.title}" has no description (what question does it answer?)`);
    if (!p.datasource?.uid || !KNOWN_DS.has(p.datasource.uid)) problems.push(`${rel}: panel "${p.title}" datasource uid ${p.datasource?.uid}`);
    for (const t of p.targets ?? []) if (t.datasource?.uid && !KNOWN_DS.has(t.datasource.uid)) problems.push(`${rel}: panel "${p.title}" target datasource ${t.datasource.uid}`);
    if (!(p.targets ?? []).length) problems.push(`${rel}: panel "${p.title}" has no query`);
  }
  return {rel, d, panels};
}).filter(Boolean);

if (problems.length) { console.error(problems.join('\n')); process.exit(1); }

const q = (t) => {
  const text = t.expr ?? t.query ?? (t.queryType === 'serviceMap' ? 'serviceMap (Tempo → traces_service_graph_* in Prometheus)' : '');
  const kind = t.datasource?.uid === 'loki' ? 'LogQL' : t.datasource?.uid === 'tempo' ? (t.queryType === 'serviceMap' ? 'Tempo' : 'TraceQL') : 'PromQL';
  return `${kind}: \`${text.replace(/`/g, "'").replace(/\|/g, '\\|').replace(/\n/g, ' ')}\``;
};
const thresholds = (p) => {
  const steps = p.fieldConfig?.defaults?.thresholds?.steps ?? [];
  const named = steps.filter((s) => s.value !== null && s.value !== undefined).map((s) => `${s.color} ≥ ${s.value}`);
  return named.length ? named.join(', ') : '—';
};
const typeName = {timeseries: 'time series', stat: 'single value', gauge: 'gauge', table: 'table', heatmap: 'heatmap', logs: 'log view', nodeGraph: 'node graph'};

let md = `# Dashboards, panel by panel\n\n<!-- Generated by stack/monitoring/scripts/dashboard-docs.mjs from stack/monitoring/grafana/dashboards — do not edit by hand. -->\n\n`;
md += `Every panel of every dashboard: the question it answers, how it is drawn, the exact query, its unit and the colour\nthresholds. Grafana is one rendering of these rows; the query column plus [signals.md](signals.md) is enough to rebuild a\npanel on any provider (see [porting.md](porting.md)). Plain-language definitions of the KPIs behind the panels:\n[kpis.md](kpis.md).\n\n`;
md += `| dashboard | folder | panels | purpose |\n|---|---|---|---|\n`;
for (const {d, panels} of dashboards) md += `| [${d.title}](#${d.uid}) | ${d.tags?.[1] ?? ''} | ${panels.filter((p) => p.type !== 'row').length} | ${d.description} |\n`;
for (const {rel, d, panels} of dashboards) {
  md += `\n## ${d.title}\n\n<a id="${d.uid}"></a>\n\n`;
  md += `- **uid** \`${d.uid}\` · **file** \`stack/monitoring/grafana/dashboards/${rel}\` · **default range** ${d.time.from} · **refresh** ${d.refresh}\n`;
  md += `- **Purpose:** ${d.description}\n`;
  const vars = d.templating?.list ?? [];
  if (vars.length) md += `- **Variables:** ${vars.map((v) => `\`${v.name}\` (${v.label}${v.definition ? `: \`${v.definition}\`` : ''})`).join(' · ')}\n`;
  if (d.links?.length) md += `- **Links to:** ${d.links.map((l) => l.title).join(', ')}\n`;
  md += `\n| panel | answers | type | query | unit | thresholds |\n|---|---|---|---|---|---|\n`;
  let section = '';
  for (const p of panels) {
    if (p.type === 'row') { section = p.title; continue; }
    const queries = (p.targets ?? []).map(q).join('<br>');
    md += `| ${section ? `*${section}* — ` : ''}**${p.title}** | ${p.description} | ${typeName[p.type] ?? p.type} | ${queries} | ${p.fieldConfig?.defaults?.unit ?? '—'} | ${thresholds(p)} |\n`;
  }
}

if (check) {
  const current = existsSync(docFile) ? readFileSync(docFile, 'utf8') : '';
  if (current !== md) { console.error(`${docFile} is out of date: run node stack/monitoring/scripts/dashboard-docs.mjs`); process.exit(1); }
  console.log(`${dashboards.length} dashboards valid, docs up to date`);
} else {
  writeFileSync(docFile, md);
  console.log(`${dashboards.length} dashboards valid, wrote ${docFile}`);
}
