// Generated by grafana-k6 on 2026-09-05T07:48:16Z
/**
 * API-side removal of k6- stores: what a seller could do from the console. Rows the API cannot delete (orders,
 * carts, shoppers, orgs) are left for scripts/cleanup.sql.
 */
import { config } from '../core/env.js';
import { login } from '../core/session.js';
import { platformEdge } from '../core/edges.js';
import { TenancyClient } from '../clients/index.js';

export function cleanupStores(account) {
  const session = login(account || config.accounts.superAdmin);
  if (!session) throw new Error('cleanup: cannot log in');
  const tenancy = new TenancyClient(platformEdge(session));
  const list = tenancy.listStores({ name: 'k6-' }, 0, 200);
  const rows = list.body ? (list.body.content || list.body) : [];
  let removed = 0;
  (Array.isArray(rows) ? rows : []).forEach((s) => {
    if (!s.name || !s.name.startsWith('k6-') || s.status === 'DELETED') return;
    const id = String(s.id && s.id.id ? s.id.id : s.id);
    if (s.status !== 'ARCHIVED') tenancy.archiveStore(id);
    if (tenancy.deleteStore(id).ok) removed += 1;
  });
  console.log(`cleanup: ${removed} k6- stores deleted`);
  return removed;
}
