// Generated by grafana-k6 on 2026-09-05T07:48:16Z
/**
 * Test data the write-side scripts need, provisioned once in setup() and handed to every VU as `data.fixtures`.
 *
 *   needs: ['sessions']   seller sessions for the seeded accounts (SESSION_POOL of them)
 *   needs: ['store']      a k6-<RUN_ID> org + store, provisioned through the public signup and the console API,
 *                         polled until it is operable on its pod and answers on its own storefront host
 *   needs: ['catalog']    FIXTURE_CATEGORIES categories and FIXTURE_PRODUCTS products with FIXTURE_STOCK stock (implies store)
 *   needs: ['content']    two content pages on the fixture store (implies store)
 *   needs: ['shoppers']   SHOPPERS registered shoppers on the fixture store (if any) or the selected seeded store
 *
 * Idempotent by RUN_ID: a second run with the same RUN_ID finds its org, store and catalogue and reuses them,
 * so local iteration costs nothing after the first run. `make clean` removes everything named k6-.
 */
import { env, config, storeUrl } from '../core/env.js';
import { login, sessionPool } from '../core/session.js';
import { platformEdge, sellerEdge, storefrontEdge } from '../core/edges.js';
import { pollUntil } from '../core/wait.js';
import { fixtureProvisionDuration, storesCreated, productsCreated, shoppersRegistered } from '../core/metrics.js';
import { TenancyClient, MerchantClient, CatalogClient, InventoryClient, ContentClient, CuaClient, PaymentClient, BillingClient } from '../clients/index.js';
import * as faker from '../../data/faker.js';

const PREFIX = 'k6';

function fixtureNames(suffix) {
  const base = `${PREFIX}-${env.RUN_ID}`.toLowerCase().replace(/[^a-z0-9-]/g, '-');
  const name = suffix > 1 ? `${base}-${suffix}` : base;
  return { org: name, store: name, email: `${name}@load.test`, password: env.FIXTURE_PASSWORD };
}

function expand(needs) {
  const set = new Set(needs || []);
  if (set.has('catalog') || set.has('content')) set.add('store');
  return set;
}

// ── org + store ──────────────────────────────────────────────────────────────
//
// One writable store per org: the org's trial is granted to its first store, and any later store is PENDING
// (unpaid) and refused every write with 402 BILLING.STORE.SUSPENDED. A deleted store also keeps its name. So the
// fixture is an (org, store) pair named k6-<RUN_ID>[-n]: reuse the pair whose store is live, otherwise move to
// the next n and sign a fresh org up.

function orgSession(names) {
  const tenancy = new TenancyClient(platformEdge(null));
  const signup = tenancy.signup(faker.signupUser(names.org, names.email, names.password), [200, 201, 409]);
  if (!signup.ok) throw new Error(`fixtures: signup for ${names.email} failed with ${signup.status}`);
  const session = login({ username: names.email, password: names.password, role: 'ORG_ADMIN' });
  if (!session) throw new Error(`fixtures: cannot log in as ${names.email}`);
  return session;
}

function ownStores(tenancy) {
  const list = tenancy.listStores({}, 0, 100);
  const rows = list.body ? (list.body.content || list.body) : [];
  return (Array.isArray(rows) ? rows : []).map((s) => ({
    name: s.name, status: s.status, id: String(s.id && s.id.id ? s.id.id : s.id),
  }));
}

/** Can this store take writes? The gateway refuses non-GET on /spg with 402 while billing says it is blocked. */
function writable(session, storeId) {
  // entitlement snapshot: { status: TRIALING|ACTIVE|PENDING|…, operable: bool, entitlements: { MAX_PRODUCTS: {limitValue} … } }
  const ent = new BillingClient(platformEdge(session)).entitlement(storeId);
  return ent.status === 200 && !!ent.body && ent.body.operable === true;
}

function freeStoreName(tenancy, base) {
  let name = base;
  for (let i = 2; (tenancy.storeNameExists(name).body || {}).exists; i += 1) name = `${base}-s${i}`;
  return name;
}

function ensureOrgAndStore() {
  for (let n = 1; n <= 20; n += 1) {
    const names = fixtureNames(n);
    const session = orgSession(names);
    const tenancy = new TenancyClient(platformEdge(session));
    const stores = ownStores(tenancy);
    const live = stores.find((s) => s.status !== 'DELETED' && s.status !== 'ARCHIVED' && writable(session, s.id));
    if (live) return { session, names, storeId: live.id, storeName: live.name };
    if (stores.length > 0) continue; // this org's trial went to a store that is gone or blocked: next org
    const storeName = freeStoreName(tenancy, names.store); // store names are global, and a deleted one keeps its name
    const created = tenancy.createStore(faker.storeDefinition(storeName, names.email));
    if (!created.ok || !created.storeId) throw new Error(`fixtures: store create failed with ${created.status}: ${JSON.stringify(created.body)}`);
    storesCreated.add(1);
    return { session, names, storeId: String(created.storeId), storeName };
  }
  throw new Error('fixtures: no free k6- org/store name in 20 attempts; run make clean');
}

function ensureStore() {
  const found = ensureOrgAndStore();
  const { session, storeId, storeName } = found;
  const tenancy = new TenancyClient(platformEdge(session));
  const store = { name: storeName, id: storeId, url: storeUrl(storeName), podId: config.podId, requireLogin: false, defaultLang: 'en', fixture: true };

  const operable = pollUntil(() => tenancy.storePod(storeId, [200, 422, 404]).status === 200, { timeout: 120, interval: 3, label: 'store operable on its pod' });
  if (!operable) throw new Error(`fixtures: store ${storeId} never became operable`);
  const merchant = new MerchantClient(sellerEdge(session, store));
  pollUntil(() => merchant.privateStore([200, 403, 404, 502]).status === 200, { timeout: 60, interval: 3, label: 'merchant store on the pod' });
  const onHost = pollUntil(() => new MerchantClient(storefrontEdge(store)).store(storeId).status === 200, { timeout: 60, interval: 3, label: 'storefront host resolves' });
  if (!onHost) throw new Error(`fixtures: ${store.url} does not resolve to the store (spg domain lookup)`);
  store.session = session;
  store.names = found.names;
  return store;
}

// ── catalogue ────────────────────────────────────────────────────────────────

function ensureCatalog(session, store, limits) {
  const edge = sellerEdge(session, store);
  // stay under MAX_PRODUCTS with room for journeys that create a product of their own
  const cap = limits && limits.MAX_PRODUCTS ? Math.max(1, limits.MAX_PRODUCTS - 5) : env.FIXTURE_PRODUCTS;
  const count = Math.min(env.FIXTURE_PRODUCTS, cap);
  const catalog = new CatalogClient(edge);
  const inventory = new InventoryClient(edge);
  const products = [];
  const categories = [];

  for (let c = 1; c <= env.FIXTURE_CATEGORIES; c += 1) {
    const code = `k6-cat-${c}`;
    const exists = catalog.categoryCodeExists(code);
    if (!(exists.body && exists.body.exists)) {
      catalog.createCategory(faker.categoryDefinition(code, `K6 category ${c}`, c));
    }
  }
  const tree = catalog.privateCategoryHierarchy(200);
  const rows = tree.body ? (tree.body.content || tree.body.categories || tree.body) : [];
  (Array.isArray(rows) ? rows : []).forEach((cat) => {
    if (cat.code && cat.code.startsWith('k6-cat-')) categories.push({ id: cat.id, code: cat.code, slug: cat.code });
  });

  const entries = [];
  for (let p = 1; p <= count; p += 1) {
    const sku = `K6-SKU-${String(p).padStart(4, '0')}`;
    const slug = `k6-p-${p}`;
    const exists = catalog.skuExists(sku);
    let productId = null;
    if (exists.body && exists.body.exists) {
      const found = catalog.listing({ sku, count: 1 });
      const list = found.body ? (found.body.products || found.body.content || []) : [];
      productId = list.length > 0 ? list[0].id : null;
    }
    if (!productId) {
      // 422 CATALOG.*.MAX_PRODUCTS: the store's entitlement caps the catalogue (25 on a trial); stop there
      const created = catalog.createProduct(faker.productDefinition(sku, `K6 product ${p}`, slug), [201, 422]);
      if (created.status === 422) break;
      productId = created.body ? created.body.id : null;
      if (productId) productsCreated.add(1);
    }
    if (!productId) continue;
    if (categories.length > 0) catalog.attachCategory(productId, categories[p % categories.length].id);
    entries.push({ sku, inventory: faker.inventoryEntry(productId, env.FIXTURE_STOCK, 10 + (p % 40)) });
    products.push({ id: productId, sku, slug });
  }
  for (let i = 0; i < entries.length; i += 25) {
    inventory.bulk(entries.slice(i, i + 25));
  }
  products.forEach((p) => catalog.patchProduct(p.id, true, true));
  return { categories, products };
}

function ensureContent(session, store) {
  const content = new ContentClient(sellerEdge(session, store));
  const pages = [];
  ['k6-about', 'k6-shipping'].forEach((slug, i) => {
    // 409: the slug exists from an earlier run — the page is there, which is all that matters here
    const created = content.createPage(faker.contentPageDefinition(slug, `K6 page ${i + 1}`), [200, 201, 409]);
    if (created.body && created.body.id) {
      content.publishPage(created.body.id, {});
      pages.push({ id: created.body.id, slug });
    } else {
      pages.push({ id: null, slug });
    }
  });
  return pages;
}

function supportedTypes(store) {
  const types = new PaymentClient(storefrontEdge(store)).supportedPaymentTypes(store.id);
  const list = Array.isArray(types.body) ? types.body : [];
  return list.map((t) => (typeof t === 'string' ? t : t.code || t.paymentType || t.type)).filter(Boolean);
}

/** A new store has no payment configuration; enable the two provider-less types so orders can be placed. */
function ensurePayments(session, store) {
  let types = supportedTypes(store);
  const wanted = ['COD', 'MANUAL_TRANSFER'].filter((t) => !types.includes(t));
  if (wanted.length > 0) {
    const payment = new PaymentClient(sellerEdge(session, store));
    wanted.forEach((paymentType) => payment.saveConfiguration({ paymentType, enabled: true }));
    types = supportedTypes(store);
  }
  return types;
}

/** The plan's limits (MAX_PRODUCTS, MAX_ORDERS_MONTH, …) so a script can size itself or warn. */
function entitlementLimits(store) {
  const ent = new BillingClient(platformEdge(store.session)).entitlement(store.id);
  const limits = {};
  const map = ent.body && ent.body.entitlements ? ent.body.entitlements : {};
  Object.keys(map).forEach((k) => { if (map[k] && map[k].limitValue !== null && map[k].limitValue !== undefined) limits[k] = map[k].limitValue; });
  return limits;
}

// ── shoppers ─────────────────────────────────────────────────────────────────

/** Registers SHOPPERS accounts per store. A store may refuse self-registration (403); it is then skipped. */
function ensureShoppers(stores) {
  const shoppers = [];
  stores.forEach((store) => {
    const cua = new CuaClient(storefrontEdge(store));
    for (let i = 1; i <= env.SHOPPERS; i += 1) {
      const username = `k6-${env.RUN_ID}-${i}`.toLowerCase();
      const r = cua.register({ username, email: `${username}@load.test`, password: env.FIXTURE_PASSWORD, firstName: 'K6', lastName: `Shopper ${i}` }, [201, 403, 409]);
      if (r.status === 403) {
        console.warn(`fixtures: ${store.name} does not accept new accounts; no shoppers registered there`);
        break;
      }
      if (r.status === 201) shoppersRegistered.add(1);
      if (r.ok) shoppers.push({ store: store.name, username, password: env.FIXTURE_PASSWORD });
    }
  });
  return shoppers;
}

// ── entry points ─────────────────────────────────────────────────────────────

export function provision(needs) {
  const started = Date.now();
  const set = expand(needs);
  const fixtures = { runId: env.RUN_ID };

  if (set.has('sessions')) {
    const accounts = ['orgAdmin', 'storeAdmin', 'superAdmin', 'storeModerator'].map((k) => config.accounts[k]).filter(Boolean);
    fixtures.sessions = sessionPool(accounts, env.SESSION_POOL);
  }
  if (set.has('store')) {
    fixtures.store = ensureStore();
    fixtures.names = fixtures.store.names;
    fixtures.paymentTypes = ensurePayments(fixtures.store.session, fixtures.store);
    fixtures.entitlements = entitlementLimits(fixtures.store);
  }
  if (set.has('catalog')) {
    Object.assign(fixtures, ensureCatalog(fixtures.store.session, fixtures.store, fixtures.entitlements));
  }
  if (set.has('content')) {
    fixtures.pages = ensureContent(fixtures.store.session, fixtures.store);
  }
  if (set.has('shoppers')) {
    // the seeded stores always; the fixture store too when it accepts registrations
    fixtures.shoppers = ensureShoppers(fixtures.store ? config.stores.concat([fixtures.store]) : config.stores);
  }
  fixtureProvisionDuration.add(Date.now() - started);
  console.log(`fixtures ready in ${Date.now() - started} ms: ${JSON.stringify(summary(fixtures))}`);
  return fixtures;
}

function summary(f) {
  return {
    runId: f.runId,
    store: f.store ? { id: f.store.id, url: f.store.url } : undefined,
    categories: f.categories ? f.categories.length : undefined,
    products: f.products ? f.products.length : undefined,
    paymentTypes: f.paymentTypes,
    entitlements: f.entitlements,
    sessions: f.sessions ? f.sessions.map((s) => s.username) : undefined,
    shoppers: f.shoppers ? f.shoppers.length : undefined,
  };
}

export function teardown(fixtures) {
  if (env.KEEP_FIXTURES || !fixtures || !fixtures.store) return;
  const tenancy = new TenancyClient(platformEdge(fixtures.store.session));
  tenancy.archiveStore(fixtures.store.id);
  tenancy.deleteStore(fixtures.store.id);
}

/** setup/teardown pair for a script: `export const { setup, teardown } = withFixtures(options)` */
export function withFixtures(options) {
  const needs = options && options.ext && options.ext.fixtures ? options.ext.fixtures.needs : [];
  return {
    setup: () => ({ fixtures: provision(needs) }),
    teardown: (data) => teardown(data && data.fixtures),
  };
}
