// Generated by grafana-k6 on 2026-09-05T07:51:46Z
/**
 * Ramps the offered rate on the product page's two calls (definition by slug + availability) until an SLO
 * breaks; thresholds abort the run and the summary shows the rate it broke at.   PROFILE is forced to breakpoint.
 */
import execution from 'k6/execution';
import { storeFor } from '../../lib/core/env.js';
import { build, scenario } from '../../config/profiles.js';
import { storefrontEdge } from '../../lib/core/edges.js';
import { CatalogClient, InventoryClient } from '../../lib/clients/index.js';
import { catalogFor, randomOf } from '../../lib/journeys/shopper/data.js';

export const options = build({ layer: 'storefront', script: 'storefront-breakpoint', scenarios: { ramp: scenario('rate', 'ramp') } });
export { handleSummary } from '../../lib/core/metrics.js';

export function ramp() {
  const store = storeFor(execution.vu.idInTest);
  const edge = storefrontEdge(store);
  const p = new CatalogClient(edge).productBySlug(randomOf(catalogFor(store).productSlugs));
  if (p.body && p.body.sku) new InventoryClient(edge).availability([p.body.sku]);
}
