// Generated by grafana-k6 on 2026-09-05T07:51:46Z
/**
 * Shoppers browsing the seeded stores: home → category → product (→ search). Closed model with think time. At
 * PROFILE=spike a steady home-page probe runs beside the spike and must be back inside the page SLO once it ends.
 */
import execution from 'k6/execution';
import { env, storeFor } from '../../lib/core/env.js';
import { build, scenario, recoveryProbe } from '../../config/profiles.js';
import { recoveryThresholds } from '../../config/thresholds.js';
import { catalogFor } from '../../lib/journeys/shopper/data.js';
import { browseVisit } from '../../lib/journeys/shopper/browse.js';
import { pageView } from '../../lib/journeys/shopper/pages.js';

export const options = build({ layer: 'storefront', script: 'storefront-browse',
  scenarios: Object.assign({ shoppers: scenario('vus', 'shoppers') }, recoveryProbe('probe')),
  thresholds: recoveryThresholds(env.PROFILE) });
export { handleSummary } from '../../lib/core/metrics.js';

export function probe() {
  const store = storeFor(1);
  pageView(store, catalogFor(store), 'home');
}

export function shoppers() {
  const store = storeFor(execution.vu.idInTest);
  browseVisit(store, catalogFor(store));
}
