// Generated by grafana-k6 on 2026-09-05T07:51:46Z
/** Shoppers browsing the seeded stores: home → category → product (→ search). Closed model with think time. */
import { sleep } from 'k6';
import execution from 'k6/execution';
import { storeFor } from '../../lib/core/env.js';
import { build, scenario } from '../../config/profiles.js';
import { catalogFor } from '../../lib/journeys/shopper/data.js';
import { browseHome, browseCategory, browseProduct } from '../../lib/journeys/shopper/browse.js';
import { searchJourney } from '../../lib/journeys/shopper/search.js';

export const options = build({ layer: 'storefront', script: 'storefront-browse', scenarios: { shoppers: scenario('vus', 'shoppers') } });
export { handleSummary } from '../../lib/core/metrics.js';

export function shoppers() {
  const store = storeFor(execution.vu.idInTest);
  const data = catalogFor(store);
  browseHome(store, data);
  sleep(1 + Math.random() * 2);
  browseCategory(store, data);
  sleep(1 + Math.random() * 2);
  browseProduct(store, data);
  sleep(1 + Math.random() * 3);
  if (Math.random() < 0.3) {
    searchJourney(store, data);
    sleep(1 + Math.random());
  }
}
