// Generated by grafana-k6 on 2026-09-05T07:51:46Z
/** Content reads every page makes: site, menus, banners, policies, faq, posts, layout, CMS pages. */
import execution from 'k6/execution';
import { storeFor } from '../../lib/core/env.js';
import { build, scenario } from '../../config/profiles.js';
import { catalogFor } from '../../lib/journeys/shopper/data.js';
import { browseContent } from '../../lib/journeys/shopper/browse.js';
import { ContentClient } from '../../lib/clients/index.js';
import { storefrontEdge } from '../../lib/core/edges.js';

export const options = build({ layer: 'storefront', script: 'storefront-content', scenarios: { reads: scenario('rate', 'reads') } });
export { handleSummary } from '../../lib/core/metrics.js';

export function reads() {
  const store = storeFor(execution.vu.idInTest);
  browseContent(store, catalogFor(store));
  new ContentClient(storefrontEdge(store)).layout('HOME');
}
