// Generated by grafana-k6 on 2026-09-05T07:51:46Z
/** Search traffic at a fixed rate: suggest, full-text with facets, sorted pages. */
import execution from 'k6/execution';
import { storeFor } from '../../lib/core/env.js';
import { build, scenario } from '../../config/profiles.js';
import { catalogFor } from '../../lib/journeys/shopper/data.js';
import { searchJourney } from '../../lib/journeys/shopper/search.js';

export const options = build({ layer: 'storefront', script: 'storefront-search', scenarios: { searches: scenario('rate', 'searches') } });
export { handleSummary } from '../../lib/core/metrics.js';

export function searches() {
  const store = storeFor(execution.vu.idInTest);
  searchJourney(store, catalogFor(store));
}
