// Generated by grafana-k6 on 2026-09-05T07:51:46Z
/** A steady shopper population for a long time: what a 10-minute run cannot show (leaks, pools, caches). */
import { sleep } from 'k6';
import execution from 'k6/execution';
import { storeFor } from '../../lib/core/env.js';
import { build, scenario } from '../../config/profiles.js';
import { catalogFor } from '../../lib/journeys/shopper/data.js';
import { browseHome, browseCategory, browseProduct, browseContent } from '../../lib/journeys/shopper/browse.js';
import { searchJourney } from '../../lib/journeys/shopper/search.js';

export const options = build({ layer: 'storefront', script: 'storefront-soak', scenarios: { steady: scenario('vus', 'steady') } });
export { handleSummary } from '../../lib/core/metrics.js';

export function steady() {
  const store = storeFor(execution.vu.idInTest);
  const data = catalogFor(store);
  browseHome(store, data);
  sleep(2 + Math.random() * 3);
  browseCategory(store, data);
  sleep(2 + Math.random() * 3);
  browseProduct(store, data);
  sleep(2 + Math.random() * 3);
  if (Math.random() < 0.3) browseContent(store, data);
  if (Math.random() < 0.25) searchJourney(store, data);
  sleep(1 + Math.random() * 2);
}
