// Generated by grafana-k6 on 2026-09-05T07:51:46Z
/** API pass of `make clean`: archive and delete every k6- store as a seller would. */
import { build, scenario } from '../config/profiles.js';
import { cleanupStores } from '../lib/fixtures/cleanup.js';

export const options = build({ layer: 'all', script: 'cleanup', scenarios: { cleanup: scenario('once', 'cleanup') }, thresholds: { checks: ['rate>0'] } });
export { handleSummary } from '../lib/core/metrics.js';

export function cleanup() {
  cleanupStores();
}
