// Generated by grafana-k6 on 2026-09-05T07:51:46Z
/** Provision (or find) the k6- org, store, catalogue, content and shoppers, print them, keep them.  make fixtures */
import { build, scenario } from '../config/profiles.js';
import { withFixtures } from '../lib/fixtures/provision.js';

export const options = build({ layer: 'all', script: 'fixtures', needs: ['store', 'catalog', 'content', 'shoppers'],
  scenarios: { noop: scenario('once', 'noop') }, thresholds: { checks: ['rate>0'] } });
export const { setup } = withFixtures(options);
export { handleSummary } from '../lib/core/metrics.js';

export function noop(data) {
  console.log(JSON.stringify(data.fixtures, null, 2));
}
