// Generated by grafana-k6 on 2026-09-05T07:51:05Z
/**
 * Functional test of the suite itself: every client method once against the target, asserted with expect.soft().
 * Read-only on the seeded store except a cart, a shopper registration and the session it logs in with.
 * Run before anything else on a new target or after touching a client:  make selftest
 */
import { expect } from 'https://jslib.k6.io/k6-testing/0.6.1/index.js';
import { config } from '../lib/core/env.js';
import { build, scenario } from '../config/profiles.js';
import { storefrontEdge, sellerEdge, platformEdge, gatewayEdge, uaaEdge } from '../lib/core/edges.js';
import { login } from '../lib/core/session.js';
import { challenge, loginShopper, bearer } from '../lib/core/pkce.js';
import { withQuery } from '../lib/core/http.js';
import * as seed from '../data/seed.js';
import * as C from '../lib/clients/index.js';

export const options = build({ layer: 'all', script: 'selftest', scenarios: { selftest: scenario('once', 'selftest') }, thresholds: { checks: ['rate>0.9'] } });
export { handleSummary } from '../lib/core/metrics.js';

function pure() {
  expect.soft(withQuery('http://x/a', { store: '1', lang: 'en', empty: '', none: null })).toEqual('http://x/a?store=1&lang=en');
  // RFC 7636 appendix B test vector
  expect.soft(challenge('dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk')).toEqual('E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM');
}

function storefront(store) {
  const edge = storefrontEdge(store);
  const pages = new C.StorefrontPagesClient(edge);
  const catalog = new C.CatalogClient(edge);
  const inventory = new C.InventoryClient(edge);
  const content = new C.ContentClient(edge);
  const merchant = new C.MerchantClient(edge);
  const checkout = new C.CheckoutClient(edge);
  const payment = new C.PaymentClient(edge);
  const cua = new C.CuaClient(edge);

  expect.soft(pages.home().status).toEqual(200);
  expect.soft(pages.category(seed.categories[0]).status).toEqual(200);
  expect.soft(pages.product(seed.productSlugs[0]).status).toEqual(200);
  expect.soft(pages.search('nike').status).toEqual(200);
  expect.soft(pages.checkout().status).toEqual(200);
  expect.soft(pages.login().status).toEqual(200);
  expect.soft(pages.register().status).toEqual(200);

  expect.soft(catalog.categoryHierarchy().status).toEqual(200);
  const cat = catalog.category(seed.categories[0]);
  expect.soft(cat.status).toEqual(200);
  const catId = cat.body ? cat.body.id : 0;
  expect.soft(catalog.categoryManufacturers(catId).status).toEqual(200);
  expect.soft(catalog.productsInCategory(catId).status).toEqual(200);
  expect.soft(catalog.productGroup(seed.productGroups[0]).ok).toBeTruthy();
  const product = catalog.productBySlug(seed.productSlugs[0]);
  expect.soft(product.status).toEqual(200);
  expect.soft(catalog.related(product.body ? product.body.id : 0).ok).toBeTruthy();
  expect.soft(catalog.listing({ sku: 'NK' }).status).toEqual(200);
  expect.soft(catalog.search('nike').status).toEqual(200);
  expect.soft(catalog.suggest('nik').status).toEqual(200);

  expect.soft(inventory.availability(seed.skus.slice(0, 3)).status).toEqual(200);
  expect.soft(inventory.availabilityQuery(seed.skus.slice(0, 3)).status).toEqual(200);

  expect.soft(content.site().status).toEqual(200);
  expect.soft(content.layout('HOME').status).toEqual(200);
  expect.soft(content.menu('MAIN').status).toEqual(200);
  expect.soft(content.banners().status).toEqual(200);
  expect.soft(content.policy('TERMS').ok).toBeTruthy();
  expect.soft(content.faq().status).toEqual(200);
  expect.soft(content.posts().status).toEqual(200);
  expect.soft(content.sitemap().status).toEqual(200);

  expect.soft(merchant.store(store.id).status).toEqual(200);
  expect.soft(merchant.currentStore().status).toEqual(200);
  expect.soft(merchant.languages().status).toEqual(200);
  expect.soft(content.page(seed.contentPages[0], [200, 404]).ok).toBeTruthy();

  const cart = checkout.createCart(seed.skus[0], 1);
  expect.soft(cart.ok).toBeTruthy();
  expect.soft(cart.cartId).toBeTruthy();
  if (cart.cartId) {
    expect.soft(checkout.getCart(cart.cartId).status).toEqual(200);
    expect.soft(checkout.updateCart(cart.cartId, seed.skus[1], 2).ok).toBeTruthy();
    expect.soft(checkout.removeLine(cart.cartId, seed.skus[1]).ok).toBeTruthy();
  }
  expect.soft(checkout.countries().status).toEqual(200);
  expect.soft(payment.supportedPaymentTypes(store.id).status).toEqual(200);

  expect.soft(cua.socialLogins().status).toEqual(200);
  expect.soft(cua.jwks().status).toEqual(200);
  const username = `k6-selftest-${Date.now()}`;
  expect.soft(cua.register({ username, email: `${username}@load.test`, password: 'K6-load-test-1', firstName: 'K6', lastName: 'Self' }).status).toEqual(201);

  const shopper = config.accounts.shopper;
  const tokens = loginShopper(store, shopper.username, shopper.password);
  expect.soft(tokens).toBeTruthy();
  if (tokens) {
    const auth = bearer(tokens);
    expect.soft(cua.me(auth).status).toEqual(200);
    expect.soft(checkout.customerInfo(auth).status).toEqual(200);
    expect.soft(checkout.myOrders(auth).status).toEqual(200);
  }
}

function seller(store) {
  const session = login(config.accounts.orgAdmin);
  expect(session).toBeTruthy();
  const platform = platformEdge(session);
  const pod = sellerEdge(session, store);
  const tenancy = new C.TenancyClient(platform);
  const billing = new C.BillingClient(platform);
  const pods = new C.PodRegistryClient(platform);
  const uaa = new C.UaaClient(platform);
  const gateway = new C.GatewayClient(gatewayEdge(session));

  expect.soft(gateway.console().status).toEqual(200);   // console-ui's dev server; not load-bearing for the APIs
  expect.soft(gateway.signIn().status).toEqual(200);
  expect.soft(gateway.health().status).toEqual(200);
  expect.soft(uaa.me().status).toEqual(200);
  expect.soft(uaa.account().status).toEqual(200);
  expect.soft(uaa.adminUsers().ok).toBeTruthy();
  expect.soft(uaa.adminRoles().ok).toBeTruthy();

  expect.soft(tenancy.currentUser().ok).toBeTruthy();
  expect.soft(tenancy.saasProperties().status).toEqual(200);
  expect.soft(tenancy.themes().status).toEqual(200);
  expect.soft(tenancy.colorThemes().status).toEqual(200);
  expect.soft(tenancy.listStores({}).status).toEqual(200);
  expect.soft(tenancy.stores().status).toEqual(200);
  expect.soft(tenancy.storeInfo(store.id).status).toEqual(200);
  expect.soft(tenancy.store(store.id).status).toEqual(200);
  expect.soft(tenancy.storeNameExists(store.name).status).toEqual(200);
  expect.soft(tenancy.storePod(store.id).status).toEqual(200);
  expect.soft(tenancy.members().status).toEqual(200);
  expect.soft(tenancy.userAccounts(store.id).status).toEqual(200);
  expect.soft(tenancy.storeStatistic('2020-01-01T00:00:00Z', '2030-01-01T00:00:00Z').ok).toBeTruthy();

  expect.soft(billing.plans().status).toEqual(200);
  expect.soft(billing.currentSubscription(store.id).ok).toBeTruthy();
  expect.soft(billing.invoices(store.id).status).toEqual(200);
  expect.soft(billing.entitlement(store.id).ok).toBeTruthy();
  expect.soft(pods.list().ok).toBeTruthy();
  expect.soft(pods.get(config.podId).ok).toBeTruthy();

  const catalog = new C.CatalogClient(pod);
  const inventory = new C.InventoryClient(pod);
  const content = new C.ContentClient(pod);
  const merchant = new C.MerchantClient(pod);
  const checkout = new C.CheckoutClient(pod);
  expect.soft(merchant.privateStore().status).toEqual(200);
  expect.soft(merchant.allocates().status).toEqual(200);
  expect.soft(catalog.listing({ count: 5 }).status).toEqual(200);
  expect.soft(catalog.privateCategoryHierarchy().status).toEqual(200);
  expect.soft(catalog.skuExists('K6-NOPE').status).toEqual(200);
  expect.soft(catalog.categoryCodeExists('k6-nope').status).toEqual(200);
  const product = catalog.productBySlug(seed.productSlugs[0]);
  expect.soft(catalog.getProductDefinition(product.body ? product.body.id : 0).status).toEqual(200);
  expect.soft(inventory.availability([seed.skus[0]]).status).toEqual(200);
  expect.soft(content.listPages().status).toEqual(200);
  expect.soft(content.getLayout('HOME').status).toEqual(200);
  expect.soft(content.summary().status).toEqual(200);
  expect.soft(checkout.orders().status).toEqual(200);
  expect.soft(new C.PaymentClient(pod).transactions().status).toEqual(200);
  expect.soft(new C.CuaClient(pod).shoppers().ok).toBeTruthy();
}

function publicUaa() {
  const uaa = new C.UaaClient(uaaEdge());
  expect.soft(uaa.loginSettings().status).toEqual(200);
  expect.soft(uaa.idps().status).toEqual(200);
  expect.soft(uaa.jwks().status).toEqual(200);
  expect.soft(uaa.openidConfiguration().status).toEqual(200);
}

export function selftest() {
  const store = config.stores[0];
  pure();
  publicUaa();
  storefront(store);
  seller(store);
}
