// Generated by grafana-k6 on 2026-09-05T07:51:46Z
/**
 * One pass over every journey of every HTTP layer, on the seeded store and the k6- fixture store.
 * Green here means every contract still holds; it says nothing about performance.   make smoke
 */
import { config, storeFor } from '../lib/core/env.js';
import { build, scenario } from '../config/profiles.js';
import { withFixtures } from '../lib/fixtures/provision.js';
import { sessionFor } from '../lib/core/session.js';
import { catalogFor } from '../lib/journeys/shopper/data.js';
import { browseHome, browseCategory, browseProduct, browseContent } from '../lib/journeys/shopper/browse.js';
import { searchJourney } from '../lib/journeys/shopper/search.js';
import { cartJourney } from '../lib/journeys/shopper/cart.js';
import { guestCheckout } from '../lib/journeys/shopper/guestCheckout.js';
import { shopperAccount } from '../lib/journeys/shopper/account.js';
import { registerShopper } from '../lib/journeys/shopper/registration.js';
import { storeReads } from '../lib/journeys/admin/storeReads.js';
import { catalogEdit } from '../lib/journeys/admin/catalogManagement.js';
import { contentEdit } from '../lib/journeys/admin/contentManagement.js';
import { ordersList } from '../lib/journeys/admin/ordersList.js';
import { platformReads } from '../lib/journeys/admin/platformReads.js';
import { gatewayLogin } from '../lib/journeys/platform/gatewayLogin.js';
import { uaaPublic } from '../lib/journeys/platform/uaaPublic.js';
import { domainLookup, hostsUnderTest } from '../lib/journeys/platform/spgDomainLookup.js';

export const options = build({
  layer: 'all', script: 'smoke', needs: ['sessions', 'store', 'catalog', 'content', 'shoppers'],
  scenarios: { smoke: scenario('once', 'smoke') },
});
export const { setup, teardown } = withFixtures(options);
export { handleSummary } from '../lib/core/metrics.js';

export function smoke(data) {
  const f = data.fixtures;
  const seeded = storeFor(1);
  const fixture = f.store;

  [seeded, fixture].forEach((store) => {
    const cat = catalogFor(store, f);
    browseHome(store, cat);
    browseCategory(store, cat);
    browseProduct(store, cat);
    browseContent(store, cat);
    searchJourney(store, cat);
    cartJourney(store, cat);
  });
  guestCheckout(fixture, catalogFor(fixture, f));
  const fixtureShopper = (f.shoppers || []).find((s) => s.store === fixture.name);
  if (fixtureShopper) shopperAccount(fixture, catalogFor(fixture, f), fixtureShopper);
  shopperAccount(seeded, catalogFor(seeded, f), config.accounts.shopper);
  registerShopper(seeded); // a fresh store refuses self-registration until its realm settings allow it

  const session = sessionFor(f.sessions, 1);
  storeReads(session, seeded);
  catalogEdit(fixture.session, fixture);
  contentEdit(fixture.session, fixture);
  ordersList(fixture.session, fixture);
  platformReads(f.sessions.find((s) => s.role === 'SUPER_ADMIN') || session);

  gatewayLogin(config.accounts.orgAdmin);
  uaaPublic(seeded);
  hostsUnderTest(fixture, 2).forEach(domainLookup);
}
