// Generated by grafana-k6 on 2026-09-05T07:59:57Z
/** Read-only browsing in a real browser: home, a search, a category, a product. Web Vitals per page. */
import { withPage, think } from './context.js';
import { Storefront } from './pages/storefront.js';
import { randomOf } from '../shopper/data.js';

export async function browserBrowse(store, data) {
  return withPage('browser-browse', async (page) => {
    const sf = new Storefront(page, store);
    await sf.home();
    await think(page, 500, 1500);
    await sf.search(randomOf(data.searchTerms));
    await think(page, 500, 1500);
    await sf.category(randomOf(data.categories));
    await think(page, 500, 1500);
    await sf.product(randomOf(data.productSlugs));
    return true;
  });
}
