// Generated by grafana-k6 on 2026-09-05T07:59:57Z
/**
 * One fresh browser context per iteration: no cart in localStorage, no tokens in sessionStorage, so an
 * iteration never inherits a stale cart (CHECKOUT.CART.NOT_FOUND after a restart). Pages and contexts are
 * always closed, even when an assertion throws. Failures land in the `browser_errors` counter instead of
 * aborting the run, so one flaky iteration cannot end a long hybrid test.
 */
import { browser } from 'k6/browser';
import { expect } from 'https://jslib.k6.io/k6-testing/0.6.1/index.js';
import { env } from '../../core/env.js';
import { browserErrors, recordJourney } from '../../core/metrics.js';

// A failed expect() aborts the whole test in hard mode. Page objects use the soft form of this configured
// instance: with softMode 'throw' a soft failure throws, withPage() catches it, counts it and ends the iteration
// — the run goes on. The timeout is generous because locally the storefront runs on `next dev` and compiles a
// page on its first hit. expect.configure() returns a new instance; it does not change the imported one.
export const assert = expect.configure({ softMode: 'throw', timeout: 20000 });

export async function withPage(name, fn) {
  const t0 = Date.now();
  const context = await browser.newContext({ locale: 'en-US', viewport: { width: 1366, height: 900 } });
  const page = await context.newPage();
  let ok = false;
  try {
    if (env.BROWSER_BLOCK_IMAGES) {
      await page.route(/\.(png|jpe?g|webp|gif|svg)(\?.*)?$/i, (route) => route.abort());
    }
    ok = (await fn(page)) === true;
  } catch (e) {
    browserErrors.add(1, { journey: name });
    console.warn(`browser journey ${name} failed at ${page.url()}: ${String(e && e.message ? e.message : e).split('\n')[0]}`);
    try {
      await page.screenshot({ path: `results/browser-${name}-${Date.now()}.png` });
    } catch (ignored) {
      // a closed page cannot be captured; the counter above is the record
    }
  } finally {
    await page.close();
    await context.close();
  }
  recordJourney(name, t0, ok);
  return ok;
}

/** think time between pages; sleep() would block the event loop */
export async function think(page, minMs, maxMs) {
  await page.waitForTimeout(minMs + Math.random() * ((maxMs || minMs) - minMs));
}
