// Generated by grafana-k6 on 2026-09-05T07:59:57Z
/**
 * Every selector the browser journeys use, in one place. landing-ui ships no data-testid, so these are the
 * ids, roles and accessible names of the theme components (themes/basic mirrors every other theme):
 *   BuyBox.tsx, ProductCard.tsx, CartDrawer.tsx, HeaderActions.tsx, CheckoutForm.tsx, LoginForm.tsx, SearchBox.tsx
 */
export const sel = {
  header: {
    cart: { role: 'button', name: /^Cart, / },   // "Cart, empty" · "Cart, 1 item" · "Cart, 3 items"
  },
  product: {
    addToCart: { role: 'button', name: /add to cart/i },
    outOfStock: { role: 'button', name: /out of stock|not available/i },
    increaseQty: { label: 'Increase quantity' },
  },
  listing: {
    addToCart: { role: 'button', name: /add to cart/i },
    viewDetails: { role: 'link', name: /view details/i },
  },
  cartDrawer: {
    dialog: { role: 'dialog' },
    checkout: { role: 'link', name: /checkout/i },
  },
  checkout: {
    firstName: '#firstName',
    lastName: '#lastName',
    email: '#emailAddress',
    phone: '#phone',
    country: '#country',
    city: '#city',
    postalCode: '#postalCode',
    address: '#address',
    paymentType: '#paymentType',
    agree: '#isAgree',
    placeOrder: { role: 'button', name: /place order/i },
    success: { role: 'alertdialog' },
    successText: /order placed successfully/i,
  },
  login: {
    username: '#username',
    password: '#password',
    submit: { role: 'button', name: /sign in/i },
  },
  register: {
    submit: { role: 'button', name: /register|sign up|create account|submit/i },
  },
  search: {
    box: { role: 'combobox' },
  },
};

export function byRole(page, spec) {
  return page.getByRole(spec.role, { name: spec.name });
}
