// Generated by grafana-k6 on 2026-09-05T07:59:57Z
/** Register a shopper in the browser, then sign in through cua's hand-off and land on the account page. */
import { withPage, think } from './context.js';
import { Storefront } from './pages/storefront.js';
import { shoppersRegistered } from '../../core/metrics.js';

export async function browserRegisterAndLogin(store, user) {
  return withPage('browser-auth', async (page) => {
    const sf = new Storefront(page, store);
    await sf.register(user);
    shoppersRegistered.add(1, { store: store.name });
    await think(page, 300, 800);
    await sf.login(user.username, user.password);
    return true;
  });
}

export async function browserLogin(store, user) {
  return withPage('browser-login', async (page) => {
    const sf = new Storefront(page, store);
    await sf.login(user.username, user.password);
    return true;
  });
}
