// Generated by grafana-k6 on 2026-09-05T07:59:57Z
/** Home → category → product → add to cart → drawer → checkout form → "Order placed". */
import { withPage, think } from './context.js';
import { Storefront } from './pages/storefront.js';
import { ordersPlaced } from '../../core/metrics.js';
import { randomOf } from '../shopper/data.js';

export async function browserCheckout(store, data, opts) {
  // the country must be one the store ships to (the checkout's country list); Egypt matches faker's billing block
  const o = Object.assign({ countryName: 'Egypt', paymentName: 'Cash on Delivery' }, opts || {});
  return withPage('browser-checkout', async (page) => {
    const sf = new Storefront(page, store);
    await sf.home();
    await think(page, 500, 1500);
    await sf.category(randomOf(data.categories));
    await think(page, 500, 1500);
    await sf.product(randomOf(data.productSlugs));
    await think(page, 300, 800);
    await sf.addToCart();
    await sf.openCartAndCheckout();
    await sf.fillCheckout({
      firstName: 'K6', lastName: 'Browser', email: `k6-browser-${Date.now()}@load.test`, phone: '0100000000',
      city: 'Berlin', postalCode: '10115', address: 'k6 street 1', countryName: o.countryName, paymentName: o.paymentName,
    });
    const orderId = await sf.placeOrder();
    if (orderId) ordersPlaced.add(1, { store: store.name });
    return orderId !== null;
  });
}
