// Generated by grafana-k6 on 2026-09-14T06:36:37Z
/**
 * One shopper's visit in a real browser, the unit a browser spike measures (scripts/browser/storefront-spike.js). A
 * fresh context is a first visit: a campaign's shoppers arrive with nothing cached, so every static file comes from the
 * CDN (MinIO on the load stack, CloudFront on AWS) and the document from landing-ui. One page of the page mix, what a
 * shopper waits for on it, and on the home page a term typed into the search box: catalog called from the browser. The
 * think time before the page closes lets late Web Vitals land, and weighs a browser like an HTTP shopper. The journey is
 * `visit-<page>`, so every metric of the visit reads per kind of page.
 */
import { withPage, think } from './context.js';
import { Storefront } from './pages/storefront.js';
import { randomOf } from '../shopper/data.js';

export async function browserVisit(store, data, page) {
  return withPage(`visit-${page}`, async (p) => {
    const sf = new Storefront(p, store);
    if (page === 'home') {
      await sf.home();
      await sf.suggest(randomOf(data.searchTerms));
    } else if (page === 'category') {
      await sf.category(randomOf(data.categories));
    } else if (page === 'product') {
      await sf.product(randomOf(data.productSlugs));
    } else {
      await sf.search(randomOf(data.searchTerms));
    }
    await think(p, 1000, 3000);
    return true;
  });
}
