// Generated by grafana-k6 on 2026-09-05T07:52:37Z
/** Sellers signing in at a controlled rate: session store growth, the /login limiter, the XSRF hop. */
import { config } from '../../lib/core/env.js';
import { build, scenario } from '../../config/profiles.js';
import { gatewayLogin } from '../../lib/journeys/platform/gatewayLogin.js';

const rate = config.rateLimitProfile === 'test-stores' ? 30 : 8;
export const options = build({ layer: 'platform', script: 'platform-gateway-login', scenarios: { logins: scenario('rate', 'logins', { rate, unit: '1m' }) } });
export { handleSummary } from '../../lib/core/metrics.js';

export function logins() {
  gatewayLogin(config.accounts.orgAdmin);
}
