// Generated by grafana-k6 on 2026-09-05T07:52:37Z
/** uaa and cua public endpoints under a burst: sign-in settings, idps, jwks, discovery, authorize. */
import execution from 'k6/execution';
import { storeFor } from '../../lib/core/env.js';
import { build, scenario } from '../../config/profiles.js';
import { uaaPublic } from '../../lib/journeys/platform/uaaPublic.js';

export const options = build({ layer: 'platform', script: 'platform-uaa-public', scenarios: { readers: scenario('rate', 'readers', { rate: 60, unit: '1m' }) } });
export { handleSummary } from '../../lib/core/metrics.js';

export function readers() {
  uaaPublic(storeFor(execution.vu.idInTest));
}
