// Generated by grafana-k6 on 2026-09-05T08:00:25Z
/**
 * A normal day, all at once: shopper reads, searches, carts and orders on the fixture store, admins reading
 * and editing through the gateway, and a few real browsers — concurrently, so cross-service interference and
 * the shared database show up. Ratios live in k6/config/mix.js; RATE scales them together.
 *   make mixed-production-mix PROFILE=load RATE=60 DURATION=10m
 */
import execution from 'k6/execution';
import { storeFor } from '../../lib/core/env.js';
import { build, scenario, browserScenario } from '../../config/profiles.js';
import { mix } from '../../config/mix.js';
import { withFixtures } from '../../lib/fixtures/provision.js';
import { sessionFor } from '../../lib/core/session.js';
import { catalogFor } from '../../lib/journeys/shopper/data.js';
import { browseHome, browseCategory, browseProduct } from '../../lib/journeys/shopper/browse.js';
import { searchJourney } from '../../lib/journeys/shopper/search.js';
import { cartJourney } from '../../lib/journeys/shopper/cart.js';
import { guestCheckout } from '../../lib/journeys/shopper/guestCheckout.js';
import { storeReads } from '../../lib/journeys/admin/storeReads.js';
import { ordersList } from '../../lib/journeys/admin/ordersList.js';
import { catalogEdit } from '../../lib/journeys/admin/catalogManagement.js';
import { browserBrowse } from '../../lib/journeys/browser/browse.js';

export const options = build({ layer: 'mixed', script: 'production-mix', needs: ['store', 'catalog', 'sessions'],
  scenarios: {
    browse: scenario('rate', 'browse', mix.browse),
    search: scenario('rate', 'search', mix.search),
    cart: scenario('rate', 'cart', mix.cart),
    purchase: scenario('rate', 'purchase', mix.purchase),
    adminReads: scenario('rate', 'adminReads', mix.adminReads),
    adminWrites: scenario('rate', 'adminWrites', mix.adminWrites),
    browsers: browserScenario('browsers'),
  },
  thresholds: {
    'http_req_failed{layer:storefront}': ['rate<0.02'],
    'http_req_failed{layer:shopper}': ['rate<0.02'],
    'http_req_failed{layer:admin}': ['rate<0.02'],
    'journey_errors{journey:purchase}': ['rate<0.05'],
    dropped_iterations: ['count<50'],
    orders_placed: ['count>0'],
  } });
export const { setup, teardown } = withFixtures(options);
export { handleSummary } from '../../lib/core/metrics.js';

function fixtureData(data) {
  return { store: data.fixtures.store, catalog: catalogFor(data.fixtures.store, data.fixtures) };
}

export function browse(data) {
  const seeded = storeFor(execution.vu.idInTest);
  const target = Math.random() < 0.5 ? { store: seeded, catalog: catalogFor(seeded) } : fixtureData(data);
  const pick = Math.random();
  if (pick < 0.4) browseHome(target.store, target.catalog);
  else if (pick < 0.7) browseCategory(target.store, target.catalog);
  else browseProduct(target.store, target.catalog);
}
export function search(data) { const t = fixtureData(data); searchJourney(t.store, t.catalog); }
export function cart(data) { const t = fixtureData(data); cartJourney(t.store, t.catalog); }
export function purchase(data) { const t = fixtureData(data); guestCheckout(t.store, t.catalog); }
export function adminReads(data) {
  const session = sessionFor(data.fixtures.sessions, execution.vu.idInTest);
  if (Math.random() < 0.6) storeReads(session, storeFor(execution.vu.idInTest));
  else ordersList(data.fixtures.store.session, data.fixtures.store);
}
export function adminWrites(data) {
  const f = data.fixtures;
  catalogEdit(f.store.session, f.store, { categoryId: f.categories.length > 0 ? f.categories[0].id : null });
}
export async function browsers(data) {
  const t = fixtureData(data);
  await browserBrowse(t.store, t.catalog);
}
