// Generated by grafana-k6 on 2026-09-05T07:49:32Z
/**
 * A signed-in shopper: PKCE login, identity, a purchase with the bearer token (the only way on a store that
 * requires login), then the account pages: my orders, one order, its history, customer info.
 */
import { storefrontEdge, withHeaders } from '../../core/edges.js';
import { journey, ordersPlaced } from '../../core/metrics.js';
import { loginShopper, bearer } from '../../core/pkce.js';
import { CheckoutClient, CuaClient } from '../../clients/index.js';
import { randomOf } from './data.js';
import { guestOrder } from '../../../data/faker.js';

export function shopperAccount(store, data, shopper) {
  return journey('account', () => {
    const tokens = loginShopper(store, shopper.username, shopper.password);
    if (!tokens) return false;
    const auth = bearer(tokens);
    const edge = withHeaders(storefrontEdge(store), auth);
    const checkout = new CheckoutClient(edge);
    let ok = new CuaClient(edge).me().ok;

    const cart = checkout.createCart(randomOf(data.skus), 1);
    if (cart.ok && cart.cartId) {
      const order = checkout.checkout(cart.cartId, guestOrder('COD', `${shopper.username}@load.test`));
      ok = order.ok && ok;
      if (order.ok) ordersPlaced.add(1, { store: store.name });
    } else {
      ok = false;
    }

    ok = checkout.customerInfo().ok && ok;
    const orders = checkout.myOrders(undefined, 0, 10);
    ok = orders.ok && ok;
    const list = orders.body ? (orders.body.orders || orders.body.content || []) : [];
    if (list.length > 0) {
      const id = list[0].id;
      ok = checkout.myOrder(id).ok && ok;
      ok = checkout.myOrderHistory(id).ok && ok;
    }
    return ok;
  });
}
