// Generated by grafana-k6 on 2026-09-05T07:49:32Z
/**
 * The read path a shopper takes: each journey is the SSR page plus the API reads landing-ui makes for it.
 */
import { storefrontEdge } from '../../core/edges.js';
import { journey } from '../../core/metrics.js';
import { CatalogClient, InventoryClient, ContentClient, MerchantClient, StorefrontPagesClient } from '../../clients/index.js';
import { randomOf } from './data.js';

function skusOf(body, max) {
  if (!body) return [];
  const list = Array.isArray(body) ? body : (body.products || body.content || []);
  return list.map((p) => p.sku).filter(Boolean).slice(0, max || 15);
}

export function browseHome(store, data) {
  return journey('home', () => {
    const edge = storefrontEdge(store);
    const pages = new StorefrontPagesClient(edge);
    const catalog = new CatalogClient(edge);
    const content = new ContentClient(edge);
    const inventory = new InventoryClient(edge);
    let ok = pages.home().ok;
    ok = content.layout('HOME').ok && ok;
    ok = content.menu('MAIN').ok && ok;
    ok = catalog.categoryHierarchy(20).ok && ok;
    const seen = [];
    data.productGroups.forEach((g) => {
      const r = catalog.productGroup(g);
      ok = r.ok && ok;
      seen.push(...skusOf(r.body, 10));
    });
    const skus = seen.length > 0 ? seen.slice(0, 20) : data.skus.slice(0, 5);
    ok = inventory.availability(skus).ok && ok;
    return ok;
  });
}

export function browseCategory(store, data, slug) {
  return journey('category', () => {
    const edge = storefrontEdge(store);
    const s = slug || randomOf(data.categories);
    const catalog = new CatalogClient(edge);
    let ok = new StorefrontPagesClient(edge).category(s).ok;
    const cat = catalog.category(s);
    ok = cat.ok && ok;
    if (cat.body && cat.body.id !== undefined) {
      const list = catalog.productsInCategory(cat.body.id, 0, 15);
      ok = list.ok && ok;
      ok = catalog.categoryManufacturers(cat.body.id).ok && ok;
      const skus = skusOf(list.body);
      if (skus.length > 0) ok = new InventoryClient(edge).availability(skus).ok && ok;
    }
    return ok;
  });
}

export function browseProduct(store, data, slug) {
  return journey('product', () => {
    const edge = storefrontEdge(store);
    const s = slug || randomOf(data.productSlugs);
    const catalog = new CatalogClient(edge);
    let ok = new StorefrontPagesClient(edge).product(s).ok;
    const p = catalog.productBySlug(s);
    ok = p.ok && ok;
    if (p.body) {
      if (p.body.sku) ok = new InventoryClient(edge).availability([p.body.sku]).ok && ok;
      if (p.body.id !== undefined) ok = catalog.related(p.body.id).ok && ok;
    }
    return ok;
  });
}

export function browseContent(store, data) {
  return journey('content', () => {
    const edge = storefrontEdge(store);
    const content = new ContentClient(edge);
    let ok = content.site().ok;
    ok = content.menu('FOOTER').ok && ok;
    ok = content.banners().ok && ok;
    ok = content.policy('TERMS').ok && ok;
    ok = content.faq().ok && ok;
    ok = content.posts(0, 5).ok && ok;
    ok = new MerchantClient(edge).store(store.id).ok && ok;
    if (data.contentPages.length > 0) ok = content.page(randomOf(data.contentPages), [200, 404]).ok && ok;
    return ok;
  });
}
