// Generated by grafana-k6 on 2026-09-05T07:49:32Z
/** A cart that does not convert: add two lines, read it back, change a quantity, remove a line. */
import { storefrontEdge } from '../../core/edges.js';
import { journey } from '../../core/metrics.js';
import { CheckoutClient } from '../../clients/index.js';
import { randomOf } from './data.js';

export function cartJourney(store, data) {
  return journey('cart', () => {
    const checkout = new CheckoutClient(storefrontEdge(store));
    const first = randomOf(data.skus);
    let second = randomOf(data.skus);
    if (second === first) second = data.skus[(data.skus.indexOf(first) + 1) % data.skus.length];
    const cart = checkout.createCart(first, 1);
    if (!cart.ok || !cart.cartId) return false;
    let ok = checkout.updateCart(cart.cartId, second, 2).ok;
    ok = checkout.getCart(cart.cartId).ok && ok;
    ok = checkout.updateCart(cart.cartId, first, 3, [200, 201, 422]).ok && ok;
    ok = checkout.removeLine(cart.cartId, second).ok && ok;
    ok = checkout.getCart(cart.cartId).ok && ok;
    return ok;
  });
}
