// Generated by grafana-k6 on 2026-09-05T07:49:32Z
/**
 * Many shoppers buying the same sku at once. Every order reserves stock on one inventory row under a lock,
 * so this is where row-lock waits and deadlock retries show up. Needs a sku that cannot run out (fixture).
 */
import { guestCheckout } from './guestCheckout.js';

export function contendSku(store, data, sku) {
  return guestCheckout(store, data, { sku: sku || data.skus[0], quantity: 1 });
}
