// Generated by grafana-k6 on 2026-09-05T07:49:32Z
/**
 * What a shopper journey can browse on a given store: the seeded demo catalogue for seeded stores, the
 * provisioned one for the k6- fixture store. Journeys never know which; they ask catalogFor().
 */
import * as seed from '../../../data/seed.js';

export function catalogFor(store, fixtures) {
  if (store.fixture && fixtures && fixtures.products) {
    return {
      categories: fixtures.categories.map((c) => c.slug),
      productSlugs: fixtures.products.map((p) => p.slug),
      skus: fixtures.products.map((p) => p.sku),
      productGroups: seed.productGroups,
      searchTerms: ['k6', 'product', 'K6 product 1'],
      contentPages: (fixtures.pages || []).map((p) => p.slug),
    };
  }
  const s = seed.forStore(store.name);
  return {
    categories: s.categories,
    productSlugs: s.productSlugs,
    skus: s.skus,
    productGroups: s.productGroups,
    searchTerms: s.searchTerms,
    contentPages: s.contentPages,
  };
}

export const randomOf = seed.randomOf;
