// Generated by grafana-k6 on 2026-09-05T07:49:32Z
/**
 * A guest purchase on a store that allows it: the checkout page's reads, a cart, the order, its status.
 * Writes an order every time it succeeds. paymentType COD or MANUAL_TRANSFER never redirects to a provider.
 */
import { storefrontEdge } from '../../core/edges.js';
import { journey, ordersPlaced } from '../../core/metrics.js';
import { CatalogClient, CheckoutClient, PaymentClient, StorefrontPagesClient } from '../../clients/index.js';
import { randomOf } from './data.js';
import { guestOrder, email } from '../../../data/faker.js';

export function guestCheckout(store, data, opts) {
  const o = Object.assign({ paymentType: 'COD', quantity: 1, sku: null, headers: undefined }, opts || {});
  return journey('purchase', () => {
    const edge = storefrontEdge(store);
    const checkout = new CheckoutClient(edge);
    if (data.skus.length === 0) return false; // nothing to buy: the catalogue was not provisioned
    const sku = o.sku || randomOf(data.skus);
    let ok = new CatalogClient(edge).productBySlug(randomOf(data.productSlugs)).ok;
    const cart = checkout.createCart(sku, o.quantity);
    if (!cart.ok || !cart.cartId) return false;
    ok = new StorefrontPagesClient(edge).checkout().ok && ok;
    ok = checkout.countries().ok && ok;
    ok = new PaymentClient(edge).supportedPaymentTypes(store.id).ok && ok;
    const order = checkout.checkout(cart.cartId, guestOrder(o.paymentType, email('guest')), o.headers);
    ok = order.ok && ok;
    if (order.ok) {
      ordersPlaced.add(1, { store: store.name });
      if (order.body && order.body.id !== undefined) ok = checkout.orderStatus(order.body.id, o.headers).ok && ok;
    }
    return ok;
  });
}
