// Generated by grafana-k6 on 2026-09-14T02:30:00Z
/**
 * Page views alone: what a shopper's browser asks landing-ui for, without the API reads the browse journeys send
 * beside each page. landing-ui makes those reads itself while it renders, so one page view here is one render — the
 * unit landing-ui's capacity is counted in.
 */
import { storefrontEdge } from '../../core/edges.js';
import { journey } from '../../core/metrics.js';
import { StorefrontPagesClient } from '../../clients/index.js';
import { randomOf } from './data.js';

/** One page of the mix: [['home', 0.25], ...] from k6/config/mix.js. */
export function pickPage(mix) {
  let r = Math.random();
  for (const [page, share] of mix) {
    if (r < share) return page;
    r -= share;
  }
  return mix[mix.length - 1][0];
}

/** One server-rendered page view of `page` (home | category | product | search) on the store. */
export function pageView(store, data, page) {
  return journey('page-view', () => {
    const pages = new StorefrontPagesClient(storefrontEdge(store));
    if (page === 'home') return pages.home().ok;
    if (page === 'category') return pages.category(randomOf(data.categories)).ok;
    if (page === 'product') return pages.product(randomOf(data.productSlugs)).ok;
    return pages.search(randomOf(data.searchTerms)).ok;
  });
}
