// Generated by grafana-k6 on 2026-09-05T07:49:32Z
/** Self-registration on a store, then the register page the form lives on. */
import { storefrontEdge } from '../../core/edges.js';
import { journey, shoppersRegistered } from '../../core/metrics.js';
import { CuaClient, StorefrontPagesClient } from '../../clients/index.js';
import { slug } from '../../../data/faker.js';

export function registerShopper(store) {
  return journey('registration', () => {
    const edge = storefrontEdge(store);
    const username = slug('k6-reg');
    let ok = new StorefrontPagesClient(edge).register().ok;
    const r = new CuaClient(edge).register({ username, email: `${username}@load.test`, password: 'K6-load-test-1', firstName: 'K6', lastName: 'Reg' });
    if (r.ok) shoppersRegistered.add(1, { store: store.name });
    return r.ok && ok;
  });
}
