// Generated by grafana-k6 on 2026-09-05T07:49:32Z
/** Typing in the search box (suggest), submitting (search API + results page), refining (facets, sort). */
import { storefrontEdge } from '../../core/edges.js';
import { journey } from '../../core/metrics.js';
import { CatalogClient, StorefrontPagesClient } from '../../clients/index.js';
import { randomOf } from './data.js';

// search takes a named sort (upper-case); the listing takes a Pageable column and only direct Product columns are safe
const SEARCH_SORTS = ['RELEVANCE', 'NEWEST', 'OLDEST'];
const LISTING_SORT = 'dateAvailable,desc';

export function searchJourney(store, data, term) {
  return journey('search', () => {
    const edge = storefrontEdge(store);
    const catalog = new CatalogClient(edge);
    const q = term || randomOf(data.searchTerms);
    let ok = catalog.suggest(q.slice(0, 3), 8).ok;
    ok = catalog.search(q).ok && ok;
    ok = new StorefrontPagesClient(edge).search(q).ok && ok;
    ok = catalog.search(q, { sort: randomOf(SEARCH_SORTS), page: 1 }).ok && ok;
    ok = catalog.listing({ sort: LISTING_SORT, count: 15 }).ok && ok;
    return ok;
  });
}
