// Generated by grafana-k6 on 2026-09-14T02:10:00Z
/**
 * The resource half of a run's pass/fail. thresholds.js says what a user may wait; this file says what a run may use
 * of the containers it ran on, what a unit of work may cost in CPU, and what a page may ship. The numbers live here and
 * nowhere else. Pure data with no imports: scripts/verdict.mjs and scripts/page-budget.mjs read it from Node, outside
 * k6, and a script may import it too.
 */

/** Per container of the load stack, over a run's window: `make verdict`, and the end of every bin/k6run. */
export const CONTAINER = {
  cpuRatio: 0.9, // CPU at this share of the container's cap or more ...
  cpuSustainedSeconds: 60, // ... for longer than this, in one stretch, fails the run
  memoryRatio: 0.85, // peak working set against the memory limit
  oomKills: 0, // any OOM kill fails
  restarts: 0, // any restart fails
  // PROFILE=soak only: growth of the working set after warm-up, as a share of the limit per hour. A working set that
  // keeps rising once caches are warm is a leak. Judged when at least memoryGrowthWindowSeconds follow the warm-up (the
  // default 30-minute soak); a shorter soak reports it, since a few minutes of a GC's sawtooth read as growth.
  memoryGrowthPerHour: 0.1,
  soakWarmupSeconds: 300,
  memoryGrowthWindowSeconds: 1200,
};

/**
 * CPU one unit of work may cost, in milliseconds of a Fargate vCPU: the CPU measured here divided by LOAD_CPU_FACTOR,
 * so the number reads like dev's CloudWatch arithmetic (utilisation × vCPU × seconds ÷ units). `budgetMs: null` is
 * reported, not judged.
 *   landing-ui per page view: dev measured ~95 ms on 2026-09-13 and ~206 ms the day before the render fixes; 130 ms
 *     leaves room for noise and fails a return to the old cost.
 *   uaa per seller sign-in: a bcrypt check plus the authorize and code hops; reported until a baseline exists.
 */
export const CPU_PER_UNIT = {
  'landing-ui': { per: 'page view', budgetMs: 130 },
  uaa: { per: 'sign-in', budgetMs: null },
};

/**
 * What a server-rendered page may ship, per theme and key page: `make page-budget` (scripts/page-budget.mjs). Sizes are
 * uncompressed KiB, as served. `themes` mirrors cvhome's store-pod/landing-ui/themes/ (a new theme is one entry);
 * `null` is reported, not judged. The two weekend findings fail here: every theme's CSS and JS on every page
 * (otherThemeFiles: 13 stylesheets and 31 scripts, 22 of them another theme's) and all CSS inlined twice (the HTML at
 * 866 KiB, duplicateInlineCssKiB).
 */
export const PAGE = {
  themes: ['basic', 'beauty', 'cosmetics', 'fashion', 'furniture', 'glasses', 'grocery', 'hunger', 'jewellery', 'pink', 'sports', 'starter'],
  pages: ['home', 'category', 'product', 'search'],
  otherThemeFiles: 0, // a page loads no stylesheet or script that carries another theme
  duplicateInlineCssKiB: 0, // no inline stylesheet appears twice in the HTML (as <style> and again in the RSC payload)
  htmlKiB: 400,
  cssFiles: 4,
  cssKiB: 160,
  jsFiles: 24,
  jsKiB: 1450,
  rscNavKiB: null, // the payload of a client-side navigation to the page
};
