// Generated by grafana-k6 on 2026-09-05T07:43:06Z
/**
 * Traffic ratios of mixed/production-mix.js, as iterations per minute at PROFILE=load (scaled by RATE/30), and the
 * page mix of page views (storefront/page-breakpoint.js, the spike's recovery probe aside). Change the shape of
 * "a normal day" here, nowhere else.
 */
import { env } from '../lib/core/env.js';

const scale = env.RATE / 30;

export const mix = {
  browse:      { rate: Math.ceil(120 * scale), unit: '1m' },  // shopper reads
  search:      { rate: Math.ceil(30 * scale),  unit: '1m' },
  cart:        { rate: Math.ceil(20 * scale),  unit: '1m' },  // carts that do not convert
  purchase:    { rate: Math.ceil(10 * scale),  unit: '1m' },  // guest orders
  adminReads:  { rate: Math.ceil(15 * scale),  unit: '1m' },
  adminWrites: { rate: Math.ceil(5 * scale),   unit: '1m' },
};

// Which page a page view asks for, as shares: a shopper lands, lists a category, opens products, sometimes searches.
export const pageMix = [['home', 0.25], ['category', 0.25], ['product', 0.35], ['search', 0.15]];
