// Generated by grafana-k6 on 2026-09-05T07:43:06Z
/**
 * Traffic ratios of mixed/production-mix.js, as iterations per minute at PROFILE=load (scaled by RATE/30).
 * Change the shape of "a normal day" here, nowhere else.
 */
import { env } from '../lib/core/env.js';

const scale = env.RATE / 30;

export const mix = {
  browse:      { rate: Math.ceil(120 * scale), unit: '1m' },  // shopper reads
  search:      { rate: Math.ceil(30 * scale),  unit: '1m' },
  cart:        { rate: Math.ceil(20 * scale),  unit: '1m' },  // carts that do not convert
  purchase:    { rate: Math.ceil(10 * scale),  unit: '1m' },  // guest orders
  adminReads:  { rate: Math.ceil(15 * scale),  unit: '1m' },
  adminWrites: { rate: Math.ceil(5 * scale),   unit: '1m' },
};
