// Generated by grafana-k6 on 2026-09-05T07:43:06Z
/**
 * Load shapes. A script declares *what* runs (exec function, kind of model) and this file decides *how much*
 * from PROFILE and the knobs in core/env.js. build() then assembles the whole k6 options object so a script is
 * a handful of lines.
 *
 *   scenario('vus',  'browse', { peak: 20 })         closed model: real users with think time
 *   scenario('rate', 'orders', { rate: 30, unit: '1m' })  open model: offered load independent of latency
 *   scenario('once', 'smoke')                        one VU, one iteration
 */
import { env } from '../lib/core/env.js';
import { config } from '../lib/core/env.js';
import { globalTags } from '../lib/core/tags.js';
import { sloFor } from './thresholds.js';

function closed(exec, peak, profile) {
  switch (profile) {
    case 'smoke':
      return { executor: 'per-vu-iterations', vus: 1, iterations: 1, maxDuration: '5m', exec };
    case 'load':
      return { executor: 'ramping-vus', startVUs: 0, exec, gracefulRampDown: '30s',
        stages: [{ duration: '2m', target: peak }, { duration: env.DURATION, target: peak }, { duration: '1m', target: 0 }] };
    case 'stress':
      return { executor: 'ramping-vus', startVUs: 0, exec, gracefulRampDown: '30s',
        stages: [{ duration: '2m', target: peak }, { duration: '3m', target: peak * 2 }, { duration: '10m', target: peak * 2 }, { duration: '1m', target: 0 }] };
    case 'spike':
      return { executor: 'ramping-vus', startVUs: Math.max(1, Math.ceil(peak / 4)), exec, gracefulRampDown: '15s',
        stages: [{ duration: '30s', target: Math.ceil(peak / 4) }, { duration: '10s', target: peak * 10 }, { duration: '1m', target: peak * 10 }, { duration: '10s', target: Math.ceil(peak / 4) }, { duration: '1m', target: Math.ceil(peak / 4) }] };
    case 'soak':
      return { executor: 'constant-vus', vus: peak, duration: env.DURATION, exec };
    case 'breakpoint':
      // closed models hide the knee (VUs slow down with the system); express breakpoints as a rate instead
      return open(exec, Math.max(1, Math.ceil(peak / 2)), '1s', 'breakpoint');
    default:
      throw new Error(`unknown PROFILE ${profile}`);
  }
}

function open(exec, rate, unit, profile) {
  const perSecond = unit === '1s' ? rate : rate / 60;
  const pre = Math.max(5, Math.ceil(perSecond * 5));
  switch (profile) {
    case 'smoke':
      return { executor: 'per-vu-iterations', vus: 1, iterations: 1, maxDuration: '5m', exec };
    case 'load':
      return { executor: 'constant-arrival-rate', rate, timeUnit: unit, duration: env.DURATION, preAllocatedVUs: pre, maxVUs: pre * 6, exec };
    case 'stress':
      return { executor: 'constant-arrival-rate', rate: rate * 3, timeUnit: unit, duration: env.DURATION, preAllocatedVUs: pre * 3, maxVUs: pre * 15, exec };
    case 'spike':
      return { executor: 'ramping-arrival-rate', startRate: rate, timeUnit: unit, preAllocatedVUs: pre * 4, maxVUs: pre * 30, exec,
        stages: [{ duration: '30s', target: rate }, { duration: '10s', target: rate * 10 }, { duration: '1m', target: rate * 10 }, { duration: '10s', target: rate }, { duration: '1m', target: rate }] };
    case 'soak':
      return { executor: 'constant-arrival-rate', rate, timeUnit: unit, duration: env.DURATION, preAllocatedVUs: pre, maxVUs: pre * 6, exec };
    case 'breakpoint':
      return { executor: 'ramping-arrival-rate', startRate: 1, timeUnit: '1s', preAllocatedVUs: 50, maxVUs: Math.max(200, env.MAX_RPS * 2), exec,
        stages: [{ duration: env.RAMP, target: env.MAX_RPS }, { duration: '1m', target: env.MAX_RPS }] };
    default:
      throw new Error(`unknown PROFILE ${profile}`);
  }
}

export function scenario(kind, exec, knobs) {
  const k = knobs || {};
  const profile = env.PROFILE;
  if (kind === 'once') return { executor: 'per-vu-iterations', vus: k.vus || 1, iterations: k.iterations || 1, maxDuration: k.maxDuration || '10m', exec };
  if (kind === 'vus') return closed(exec, k.peak || env.PEAK_VUS, profile);
  if (kind === 'rate') return open(exec, k.rate || env.RATE, k.unit || env.RATE_UNIT, profile);
  throw new Error(`unknown scenario kind ${kind}`);
}

/** A browser scenario: few Chromium VUs, iteration count from the profile. */
export function browserScenario(exec, knobs) {
  const k = knobs || {};
  const vus = env.PROFILE === 'smoke' ? 1 : env.BROWSER_VUS;
  const perProfile = { smoke: 1, load: 10, stress: 20, spike: 10, soak: 60, breakpoint: 10 };
  const iterations = env.BROWSER_ITERATIONS || (perProfile[env.PROFILE] || 5) * vus;
  return { executor: 'shared-iterations', vus, iterations, maxDuration: k.maxDuration || '30m', exec,
    options: { browser: { type: 'chromium' } } };
}

/**
 * build({ layer, script, scenarios, thresholds, needs, options })
 *   layer      tags + SLO table
 *   script     testid prefix (defaults to the layer)
 *   scenarios  from scenario()/browserScenario()
 *   thresholds extra lines merged over sloFor(layer)
 *   needs      fixtures this script provisions in setup(): ['store','catalog','sessions','shoppers']
 */
export function build(spec) {
  const opts = Object.assign({
    scenarios: spec.scenarios,
    thresholds: Object.assign({}, sloFor(spec.layer, env.PROFILE), spec.thresholds || {}),
    tags: globalTags(spec.layer, spec.script),
    hosts: config.hosts,
    setupTimeout: '10m',
    teardownTimeout: '5m',
    summaryTrendStats: ['avg', 'min', 'med', 'p(90)', 'p(95)', 'p(99)', 'max'],
    ext: { fixtures: { needs: spec.needs || [] } },
  }, spec.options || {});
  return opts;
}
