// Generated by grafana-k6 on 2026-09-05T07:43:06Z
/**
 * The only place SLO numbers live. sloFor(layer, profile) returns a k6 thresholds map; scripts add
 * journey-specific lines on top. Starting values are for the local stack (dev servers, one JVM per service);
 * tighten per target once a baseline exists. Multipliers loosen everything under stress/spike/breakpoint.
 */
const MULTIPLIER = { smoke: 1, load: 1, soak: 1, stress: 2, spike: 3, breakpoint: 3 };

function p95(ms, m) { return [`p(95)<${ms * m}`]; }

const LAYERS = {
  storefront: (m) => ({
    'http_req_failed{layer:storefront}': ['rate<0.01'],
    'http_req_duration{name:page:home}': p95(3000, m),
    'http_req_duration{name:page:category}': p95(3000, m),
    'http_req_duration{name:page:product}': p95(3000, m),
    'http_req_duration{name:catalog:product}': p95(500, m),
    'http_req_duration{name:catalog:search}': p95(800, m),
    'http_req_duration{name:catalog:products-by-category}': p95(600, m),
    'http_req_duration{name:inventory:availability}': p95(400, m),
    'http_req_duration{name:content:layout}': p95(500, m),
    'journey_errors{journey:home}': ['rate<0.02'],
    'journey_errors{journey:product}': ['rate<0.02'],
  }),
  shopper: (m) => ({
    'http_req_failed{layer:shopper}': ['rate<0.01'],
    'http_req_failed{layer:storefront}': ['rate<0.02'],
    'http_req_duration{name:checkout:cart-create}': p95(800, m),
    'http_req_duration{name:checkout:cart-update}': p95(800, m),
    'http_req_duration{name:checkout:checkout}': p95(2000, m),
    'journey_duration_ms{journey:purchase}': p95(5000, m),
    'journey_errors{journey:purchase}': ['rate<0.02'],
    shopper_auth_ms: p95(3000, m),
  }),
  admin: (m) => ({
    'http_req_failed{layer:admin}': ['rate<0.01'],
    'http_req_duration{layer:admin,method:GET}': p95(1000, m),
    'http_req_duration{layer:admin,method:POST}': p95(2500, m),
    'http_req_duration{layer:admin,method:PUT}': p95(2500, m),
    'journey_errors{journey:store-lifecycle}': ['rate<0.05'],
    'journey_errors{journey:catalog-edit}': ['rate<0.02'],
  }),
  platform: (m) => ({
    'http_req_failed{layer:platform}': ['rate<0.02'],
    seller_login_ms: p95(2500, m),
    'http_req_duration{name:spg:domain-lookup}': p95(800, m),
  }),
  browser: () => ({
    browser_web_vital_lcp: ['p(75)<4000'],
    browser_web_vital_cls: ['p(75)<0.1'],
    browser_web_vital_inp: ['p(75)<200'],
    browser_web_vital_ttfb: ['p(75)<1500'],
    browser_http_req_failed: ['rate<0.05'],
    browser_errors: ['count<5'],
  }),
};

const OPEN_MODEL = { dropped_iterations: ['count<10'] };

export function sloFor(layer, profile) {
  const m = MULTIPLIER[profile] || 1;
  const base = LAYERS[layer] ? LAYERS[layer](m) : {};
  const out = Object.assign({ checks: ['rate>0.95'] }, base, OPEN_MODEL);
  if (profile === 'smoke') {
    // a smoke run proves contracts, not latency: keep only failure-shaped lines
    Object.keys(out).forEach((k) => {
      if (!(k.startsWith('http_req_failed') || k.startsWith('journey_errors') || k === 'checks' || k === 'browser_errors')) delete out[k];
    });
  }
  if (profile === 'breakpoint') {
    // stop the run at the first breached SLO and report where it broke
    Object.keys(out).forEach((k) => {
      out[k] = out[k].map((t) => ({ threshold: t, abortOnFail: true, delayAbortEval: '30s' }));
    });
  }
  return out;
}
