// Generated by grafana-k6 on 2026-09-05T07:59:57Z
/**
 * Page objects of the storefront. Each method drives one screen and asserts what a shopper would see,
 * with expect() from k6-testing (auto-retrying on locators). Locators wait on their own before an action.
 */
import { assert } from '../context.js';
import { sel, byRole } from '../selectors.js';

export class Storefront {
  constructor(page, store, lang) {
    this.page = page;
    this.store = store;
    this.lang = lang || 'en';
  }

  url(path) {
    return `${this.store.url}/${this.lang}${path || ''}`;
  }

  /** k6-testing has no toHaveURL: poll the page URL ourselves, throw like a failed assertion would. */
  async expectUrl(re, timeoutMs) {
    const deadline = Date.now() + (timeoutMs || 20000);
    while (Date.now() < deadline) {
      if (re.test(this.page.url())) return;
      await this.page.waitForTimeout(250);
    }
    throw new Error(`expected URL matching ${re}, got ${this.page.url()}`);
  }

  async home() {
    await this.page.goto(this.url('/'));
    await assert.soft(this.page.locator('main')).toBeVisible();
  }

  async category(slug) {
    await this.page.goto(this.url(`/category/${slug}`));
    await assert.soft(this.page.locator('main')).toBeVisible();
  }

  async product(slug) {
    await this.page.goto(this.url(`/product/${slug}`));
    await assert.soft(byRole(this.page, sel.product.addToCart)).toBeVisible();
  }

  async search(term) {
    await this.page.goto(this.url(`/search?q=${encodeURIComponent(term)}`));
    await this.expectUrl(/\/search\?q=/);
    await assert.soft(this.page.locator('body')).toBeVisible();
  }

  async addToCart() {
    const button = byRole(this.page, sel.product.addToCart);
    await assert.soft(button).toBeEnabled();
    await button.click();
    await assert.soft(byRole(this.page, sel.header.cart)).toBeVisible();
  }

  async openCartAndCheckout() {
    await byRole(this.page, sel.header.cart).click();
    const dialog = this.page.getByRole('dialog');
    await assert.soft(dialog).toBeVisible();
    await dialog.getByRole('link', { name: sel.cartDrawer.checkout.name }).click();
    await assert.soft(this.page.locator(sel.checkout.email)).toBeVisible();
  }

  async fillCheckout(customer) {
    const p = this.page;
    await p.locator(sel.checkout.firstName).fill(customer.firstName);
    await p.locator(sel.checkout.lastName).fill(customer.lastName);
    await p.locator(sel.checkout.email).fill(customer.email);
    await p.locator(sel.checkout.phone).fill(customer.phone);
    await p.locator(sel.checkout.city).fill(customer.city);
    await p.locator(sel.checkout.postalCode).fill(customer.postalCode);
    await p.locator(sel.checkout.address).fill(customer.address);
    // Radix selects: open the trigger, pick the option by its visible text
    await p.locator(sel.checkout.country).click();
    await p.getByRole('option', { name: customer.countryName }).click();
    if (customer.paymentName) {
      await p.locator(sel.checkout.paymentType).click();
      await p.getByRole('option', { name: customer.paymentName }).click();
    }
    // the agreement box only exists when the store has a live TERMS policy
    const agree = p.locator(sel.checkout.agree);
    if ((await agree.count()) > 0 && (await agree.isVisible())) await agree.click();
  }

  async placeOrder() {
    // the themed label varies; the form's submit button is the invariant
    const named = byRole(this.page, sel.checkout.placeOrder);
    const submit = (await named.count()) > 0 ? named : this.page.locator('form button[type=submit]').first();
    await submit.click();
    const dialog = this.page.getByRole('alertdialog');
    await assert.soft(dialog).toBeVisible();
    await assert.soft(dialog).toContainText(sel.checkout.successText);
    const text = await dialog.textContent();
    const m = /Order Id:\s*([\w-]+)/i.exec(text || '');
    return m ? m[1] : null;
  }

  /**
   * The forms post through React; typing before hydration submits the bare HTML form and reloads the page.
   * Wait for the document to finish loading (on `next dev` the chunks arrive late), then a hydration margin.
   */
  async settle() {
    const deadline = Date.now() + 20000;
    while (Date.now() < deadline && (await this.page.evaluate(() => document.readyState)) !== 'complete') {
      await this.page.waitForTimeout(250);
    }
    await this.page.waitForTimeout(3000);
  }

  async login(username, password) {
    await this.page.goto(this.url('/login?auth=1'));
    await this.settle();
    await this.page.locator(sel.login.username).fill(username);
    await this.page.locator(sel.login.password).fill(password);
    await byRole(this.page, sel.login.submit).click();
    await this.expectUrl(new RegExp(`/${this.lang}/(customer|callback)`));
  }

  async register(user) {
    await this.page.goto(this.url('/register'));
    await this.settle();
    const p = this.page;
    await p.locator('#username').fill(user.username);
    await p.locator('#email').fill(user.email);
    await p.locator('#password').fill(user.password);
    const first = p.locator('#firstName');
    if (await first.isVisible()) await first.fill(user.firstName);
    const last = p.locator('#lastName');
    if (await last.isVisible()) await last.fill(user.lastName);
    await byRole(p, sel.register.submit).click();
    try {
      await this.expectUrl(new RegExp(`/${this.lang}/(login|customer|callback|$)`), 10000);
    } catch (e) {
      const alerts = await p.evaluate(() => Array.from(document.querySelectorAll('[role=alert]')).map((a) => a.textContent.trim()).join(' | '));
      throw new Error(`register did not leave the form${alerts ? `: ${alerts}` : ''}`);
    }
  }
}
