// Generated by grafana-k6 on 2026-09-05T07:51:05Z
/** One seller signing in through the gateway (two hops: authorize redirect, form post), then proving the session. */
import { login, alive } from '../../core/session.js';
import { journey } from '../../core/metrics.js';

export function gatewayLogin(account) {
  return journey('gateway-login', () => {
    const session = login(account);
    if (!session) return false;
    return alive(session);
  });
}
