// Generated by grafana-k6 on 2026-09-05T07:51:05Z
/**
 * Drives POSTs at the two rate-limited public families until the limiter answers 429, proving it engages
 * (and never 5xx). /api/v1/public/idps/discover is harmless: it only says how an e-mail should sign in.
 */
import { uaaEdge } from '../../core/edges.js';
import { post } from '../../core/http.js';
import { journey } from '../../core/metrics.js';

export function probePublicApi(emailAddress) {
  return journey('rate-limit-probe', () => {
    const r = post(uaaEdge(), '', '/api/v1/public/idps/discover', {
      name: 'uaa:idps-discover', body: { email: emailAddress || 'probe@load.test' }, expect: [200, 400, 404, 429],
    });
    return r.ok;
  });
}
