// Generated by grafana-k6 on 2026-09-05T07:51:05Z
/**
 * spg maps every storefront host to a store through merchant's lookup-by-domain, cached per host for
 * DOMAIN_LOOKUP_TTL. Many distinct hosts — known and unknown — turn that cache into a stream of synchronous
 * calls to merchant, which is the hidden dependency of storefront throughput.
 */
import http from 'k6/http';
import { check } from 'k6';
import { config } from '../../core/env.js';
import { journey, domainLookups } from '../../core/metrics.js';
import { storefrontEdge } from '../../core/edges.js';
import { MerchantClient } from '../../clients/index.js';

export function hostsUnderTest(fixtureStore, unknownCount) {
  const known = config.allStores.map((s) => ({ host: s.url.replace(/^https?:\/\//, ''), known: true }));
  if (fixtureStore) known.push({ host: fixtureStore.url.replace(/^https?:\/\//, ''), known: true });
  const unknown = [];
  for (let i = 1; i <= (unknownCount || 20); i += 1) unknown.push({ host: `k6-unknown-${i}.${config.podDomain}`, known: false });
  return known.concat(unknown);
}

export function domainLookup(entry) {
  return journey('domain-lookup', () => {
    // an unknown host is refused as a 404, or sent to the storefront's store-not-found page (307); both are "no store"
    const expected = entry.known ? [200] : [307, 404];
    const res = http.get(`http://${entry.host}/${config.lang}`, {
      redirects: 0,
      tags: { name: 'spg:domain-lookup', layer: 'platform', store: entry.known ? 'known' : 'unknown' },
      responseCallback: http.expectedStatuses(200, 307, 404),
    });
    domainLookups.add(1, { known: String(entry.known) });
    const ok = check(res, { [`spg:domain-lookup ${expected.join('|')}`]: (r) => expected.includes(r.status) });
    const direct = new MerchantClient(storefrontEdge(config.stores[0])).lookupByDomain(entry.host);
    return ok && direct.ok;
  });
}
