// Generated by grafana-k6 on 2026-09-05T07:51:05Z
/** What every sign-in page and token verifier reads from uaa and cua without a session. */
import http from 'k6/http';
import { check } from 'k6';
import { uaaEdge, storefrontEdge } from '../../core/edges.js';
import { journey } from '../../core/metrics.js';
import { withQuery } from '../../core/http.js';
import { challenge, verifier } from '../../core/pkce.js';
import { config } from '../../core/env.js';
import { UaaClient, CuaClient } from '../../clients/index.js';

export function uaaPublic(store) {
  return journey('uaa-public', () => {
    const uaa = new UaaClient(uaaEdge());
    let ok = uaa.loginSettings().ok;
    ok = uaa.idps().ok && ok;
    ok = uaa.jwks().ok && ok;
    ok = uaa.openidConfiguration().ok && ok;
    const s = store || config.stores[0];
    ok = new CuaClient(storefrontEdge(s)).jwks().ok && ok;
    const authorize = http.get(withQuery(`${s.url}/cua/oauth2/authorize`, {
      response_type: 'code', client_id: s.id, redirect_uri: `${s.url}/${config.lang}/callback`, scope: 'openid',
      code_challenge: challenge(verifier()), code_challenge_method: 'S256', store: s.id, lang: config.lang,
    }), { redirects: 0, tags: { name: 'cua:authorize', layer: 'platform', store: s.name }, responseCallback: http.expectedStatuses(302) });
    ok = check(authorize, { 'cua:authorize 302': (r) => r.status === 302 }) && ok;
    return ok;
  });
}
