// Generated by grafana-k6 on 2026-09-05T07:52:36Z
/**
 * Signed-in shoppers on the store that requires login (org1-store1): PKCE sign-in, a purchase with the token,
 * my orders. Low rate on purpose — the token endpoint is rate-limited on deployed targets. Writes orders.
 */
import execution from 'k6/execution';
import { storeFor } from '../../lib/core/env.js';
import { build, scenario } from '../../config/profiles.js';
import { withFixtures } from '../../lib/fixtures/provision.js';
import { catalogFor } from '../../lib/journeys/shopper/data.js';
import { shopperAccount } from '../../lib/journeys/shopper/account.js';

export const options = build({ layer: 'shopper', script: 'shopper-account', needs: ['shoppers'],
  scenarios: { accounts: scenario('rate', 'accounts', { rate: 10, unit: '1m' }) } });
export const { setup, teardown } = withFixtures(options);
export { handleSummary } from '../../lib/core/metrics.js';

export function accounts(data) {
  const store = storeFor(execution.vu.idInTest);
  const mine = data.fixtures.shoppers.filter((s) => s.store === store.name);
  const shopper = mine[execution.vu.idInTest % mine.length];
  shopperAccount(store, catalogFor(store), shopper);
}
