// Generated by grafana-k6 on 2026-09-05T07:52:36Z
/** Carts at a fixed rate on the fixture store: create, add, read, change, remove. Writes carts. */
import { build, scenario } from '../../config/profiles.js';
import { withFixtures } from '../../lib/fixtures/provision.js';
import { catalogFor } from '../../lib/journeys/shopper/data.js';
import { cartJourney } from '../../lib/journeys/shopper/cart.js';

export const options = build({ layer: 'shopper', script: 'shopper-cart', needs: ['store', 'catalog'], scenarios: { carts: scenario('rate', 'carts') } });
export const { setup, teardown } = withFixtures(options);
export { handleSummary } from '../../lib/core/metrics.js';

export function carts(data) {
  cartJourney(data.fixtures.store, catalogFor(data.fixtures.store, data.fixtures));
}
