// Generated by grafana-k6 on 2026-09-05T07:52:37Z
/**
 * Registration bursts on the seeded stores (a freshly created store refuses self-registration until its realm
 * settings allow it): cua's registration path and its public-API limiter. Writes users.
 */
import execution from 'k6/execution';
import { storeFor } from '../../lib/core/env.js';
import { build, scenario } from '../../config/profiles.js';
import { registerShopper } from '../../lib/journeys/shopper/registration.js';

export const options = build({ layer: 'shopper', script: 'shopper-registration',
  scenarios: { registrations: scenario('rate', 'registrations', { rate: 15, unit: '1m' }) } });
export { handleSummary } from '../../lib/core/metrics.js';

export function registrations() {
  registerShopper(storeFor(execution.vu.idInTest));
}
