// Generated by grafana-k6 on 2026-09-05T07:46:09Z
/**
 * billing through store-core-gateway. Source: store-core/billing/billing-service/http/*.http.
 */
import { get, post } from '../core/http.js';

const S = 'billing';

export class BillingClient {
  constructor(edge) { this.edge = edge; }

  plans(currency) { return get(this.edge, S, '/api/v1/plan/public/plans', { name: 'billing:plans', params: currency ? { currency } : {} }); }
  currentSubscription(storeId, expect) {
    return get(this.edge, S, '/api/v1/subscription/current', { name: 'billing:subscription-current', params: { store: storeId }, expect: expect || [200, 404] });
  }
  invoices(storeId) { return get(this.edge, S, '/api/v1/invoice/list', { name: 'billing:invoices', params: { store: storeId } }); }
  /** 404 BILLING.SUBSCRIPTION.NOT_FOUND for a store that never subscribed (the seeded ones) */
  entitlement(storeId) { return get(this.edge, S, '/api/v1/entitlement/private/snapshot', { name: 'billing:entitlement', params: { store: storeId }, expect: [200, 404] }); }
  platformSubscriptions(filter, page, count) {
    return post(this.edge, S, '/api/v1/platform/subscriptions', { name: 'billing:platform-subscriptions', body: filter || { org: null, status: null, planCode: null, term: null, blockedOnly: false }, params: { page: page || 0, count: count || 20 }, expect: [200, 403] });
  }
  platformInvoices(filter, page, count) {
    return post(this.edge, S, '/api/v1/platform/invoices', { name: 'billing:platform-invoices', body: filter || {}, params: { page: page || 0, count: count || 20 }, expect: [200, 403] });
  }
  health() { return get(this.edge, S, '/api/v2/private/billing-health', { name: 'billing:health', expect: [200, 403] }); }
}
