// Generated by grafana-k6 on 2026-09-05T07:44:33Z
/**
 * catalog service. Public reads work on any edge; `private` methods need a seller edge.
 * Source: store-pod/catalog/catalog-service/http/{product,category}-api.http and landing-ui's catalog services.
 */
import { get, post, put, patch, del } from '../core/http.js';

const S = 'catalog';

export class CatalogClient {
  constructor(edge) { this.edge = edge; }

  // ── public ────────────────────────────────────────────────────────────────
  categoryHierarchy(count, page) {
    return get(this.edge, S, '/api/v1/category-hierarchy', { name: 'catalog:category-hierarchy', params: { page: page || 0, count: count || 20 } });
  }
  category(slug, expect) {
    return get(this.edge, S, `/api/v1/category/${slug}`, { name: 'catalog:category', expect: expect || [200] });
  }
  categoryManufacturers(categoryId) {
    return get(this.edge, S, `/api/v1/category/${categoryId}/manufacturer`, { name: 'catalog:category-manufacturers' });
  }
  /** the category page's listing: the v2 listing filtered by categoryIds, as landing-ui calls it */
  productsInCategory(categoryId, page, count) {
    return get(this.edge, S, '/api/v2/products', { name: 'catalog:products-by-category', params: { categoryIds: categoryId, page: page || 0, count: count || 15 } });
  }
  productGroup(code) {
    return get(this.edge, S, `/api/v1/products/groups/${code}`, { name: 'catalog:product-group', expect: [200, 404] });
  }
  productBySlug(slug, expect) {
    return get(this.edge, S, `/api/v2/product/name/${slug}`, { name: 'catalog:product', expect: expect || [200] });
  }
  /** products related to this one (the PDP strip); 404 when the product has none */
  related(productId) {
    return get(this.edge, S, `/api/v1/products/${productId}/relationship`, { name: 'catalog:related', expect: [200, 404] });
  }
  listing(params) {
    return get(this.edge, S, '/api/v2/products', { name: 'catalog:listing', params: Object.assign({ page: 0, count: 15 }, params || {}) });
  }
  search(q, params) {
    return get(this.edge, S, '/api/v2/products/search', { name: 'catalog:search', params: Object.assign({ q, facets: true, page: 0, count: 15 }, params || {}) });
  }
  suggest(q, limit) {
    return get(this.edge, S, '/api/v2/products/suggest', { name: 'catalog:suggest', params: { q, limit: limit || 8 } });
  }

  // ── private (seller edge) ─────────────────────────────────────────────────
  /** 201 {id}; 422 when the store's plan is at MAX_PRODUCTS */
  createProduct(body, expect) {
    return post(this.edge, S, '/api/v2/private/product', { name: 'catalog:product-create', body, expect: expect || [201] });
  }
  getProductDefinition(id) {
    return get(this.edge, S, `/api/v2/private/product/${id}`, { name: 'catalog:product-definition' });
  }
  updateProduct(id, body) {
    return put(this.edge, S, `/api/v2/private/product/${id}`, { name: 'catalog:product-update', body });
  }
  patchProduct(id, available, shipeable) {
    return patch(this.edge, S, `/api/v1/private/product/${id}`, { name: 'catalog:product-patch', body: { available, productShipeable: shipeable !== false } });
  }
  skuExists(code) {
    return get(this.edge, S, '/api/v1/private/product/unique', { name: 'catalog:sku-unique', params: { code } });
  }
  attachCategory(productId, categoryId) {
    return post(this.edge, S, `/api/v1/private/product/${productId}/category/${categoryId}`, { name: 'catalog:product-attach-category', expect: [201, 409] });
  }
  detachCategory(productId, categoryId) {
    return del(this.edge, S, `/api/v1/private/product/${productId}/category/${categoryId}`, { name: 'catalog:product-detach-category', expect: [200, 204] });
  }
  deleteProduct(id) {
    return del(this.edge, S, `/api/v1/private/product/${id}`, { name: 'catalog:product-delete', expect: [200, 204] });
  }
  createCategory(body) {
    return post(this.edge, S, '/api/v1/private/category', { name: 'catalog:category-create', body, expect: [201] });
  }
  privateCategoryHierarchy(count) {
    return get(this.edge, S, '/api/v1/private/category-hierarchy', { name: 'catalog:category-hierarchy-private', params: { count: count || 50 } });
  }
  categoryCodeExists(code) {
    return get(this.edge, S, '/api/v1/private/category/unique', { name: 'catalog:category-unique', params: { code } });
  }
  updateCategory(id, body) {
    return put(this.edge, S, `/api/v1/private/category/${id}`, { name: 'catalog:category-update', body });
  }
  setCategoryVisible(id, visible) {
    return patch(this.edge, S, `/api/v1/private/category/${id}/visible`, { name: 'catalog:category-visible', body: { visible } });
  }
  deleteCategory(id) {
    return del(this.edge, S, `/api/v1/private/category/${id}`, { name: 'catalog:category-delete', expect: [200, 204] });
  }
  rebuildSearchIndex() {
    return post(this.edge, S, '/api/v2/private/products/search-index/rebuild', { name: 'catalog:search-index-rebuild', expect: [202] });
  }
}
