// Generated by grafana-k6 on 2026-09-05T07:44:33Z
/**
 * checkout service: the shopper's cart and order placement, the shopper's own orders (bearer token), and the
 * merchant's order list (seller edge). Source: ShoppingCartApi, OrderApi, CustomerOrderApi, ReferencesApi
 * (checkout has no http/ folder) and landing-ui's cart-service.ts / customer-service.ts.
 */
import { get, post, put, del } from '../core/http.js';

const S = 'checkout';

export class CheckoutClient {
  constructor(edge) { this.edge = edge; }

  // ── cart ──────────────────────────────────────────────────────────────────
  createCart(sku, quantity) {
    const r = post(this.edge, S, '/api/v1/cart', { name: 'checkout:cart-create', body: { product: sku, quantity: quantity || 1 }, expect: [200, 201] });
    r.cartId = r.body && (r.body.code || r.body.id) ? String(r.body.code || r.body.id) : null;
    return r;
  }
  getCart(code) {
    return get(this.edge, S, `/api/v1/cart/${code}`, { name: 'checkout:cart-get' });
  }
  /** add-or-modify by sku */
  updateCart(code, sku, quantity, expect) {
    return put(this.edge, S, `/api/v1/cart/${code}`, { name: 'checkout:cart-update', body: { product: sku, quantity }, expect: expect || [200, 201] });
  }
  removeLine(code, sku) {
    return del(this.edge, S, `/api/v1/cart/${code}/product/${sku}`, { name: 'checkout:cart-remove-line', expect: [200, 204] });
  }

  // ── order placement ───────────────────────────────────────────────────────
  /** order = { payment: {paymentType, transactionType}, customer: {emailAddress, billing:{...}} }; headers carry a shopper bearer when required */
  checkout(code, order, headers, expect) {
    return post(this.edge, S, `/api/v1/cart/${code}/checkout`, { name: 'checkout:checkout', body: order, headers, expect: expect || [200, 201] });
  }
  orderStatus(orderId, headers) {
    return get(this.edge, S, `/api/v1/order/${orderId}/status`, { name: 'checkout:order-status', headers });
  }
  countries() {
    return get(this.edge, S, '/api/v1/country', { name: 'checkout:countries' });
  }
  zones(countryCode) {
    return get(this.edge, S, '/api/v1/zones', { name: 'checkout:zones', params: { code: countryCode } });
  }

  // ── the shopper's own account (bearer) ────────────────────────────────────
  customerInfo(headers) {
    return get(this.edge, S, '/api/v1/private/customer/info', { name: 'checkout:customer-info', headers });
  }
  myOrders(headers, page, count) {
    return get(this.edge, S, '/api/v1/private/customer/orders', { name: 'checkout:my-orders', headers, params: { page: page || 0, count: count || 10 } });
  }
  myOrder(id, headers) {
    return get(this.edge, S, `/api/v1/private/customer/${id}/order`, { name: 'checkout:my-order', headers });
  }
  myOrderHistory(id, headers) {
    return get(this.edge, S, `/api/v1/private/customer/${id}/order/history`, { name: 'checkout:my-order-history', headers });
  }

  // ── merchant (seller edge) ────────────────────────────────────────────────
  orders(params) {
    return get(this.edge, S, '/api/v1/private/orders', { name: 'checkout:orders', params: Object.assign({ page: 0, count: 20 }, params || {}) });
  }
  order(id) {
    return get(this.edge, S, `/api/v1/private/orders/${id}`, { name: 'checkout:order' });
  }
  orderHistory(id) {
    return get(this.edge, S, `/api/v1/private/orders/${id}/history`, { name: 'checkout:order-history' });
  }
}
