// Generated by grafana-k6 on 2026-09-05T07:45:16Z
/**
 * content service: the storefront's read API (site, layout, menus, banners, policies, faq, posts) and the
 * console's pages/layouts editors. Source: store-pod/content/content-service/http/{storefront,pages,layout}-api.http.
 */
import { get, post, put, del } from '../core/http.js';

const S = 'content';
const SF = '/api/v1/storefront';
const PV = '/api/v1/private/content';

export class ContentClient {
  constructor(edge) { this.edge = edge; }

  // ── storefront ────────────────────────────────────────────────────────────
  site() { return get(this.edge, S, `${SF}/site`, { name: 'content:site' }); }
  layout(page, params) { return get(this.edge, S, `${SF}/layout/${page || 'HOME'}`, { name: 'content:layout', params }); }
  menu(name) { return get(this.edge, S, `${SF}/menus/${name || 'MAIN'}`, { name: 'content:menu' }); }
  banners(placement) { return get(this.edge, S, `${SF}/banners`, { name: 'content:banners', params: placement ? { placement } : {} }); }
  policy(type) { return get(this.edge, S, `${SF}/policies/${type || 'TERMS'}`, { name: 'content:policy', expect: [200, 404] }); }
  faq() { return get(this.edge, S, `${SF}/faq`, { name: 'content:faq' }); }
  page(slug, expect) { return get(this.edge, S, `${SF}/pages/${slug}`, { name: 'content:page', expect: expect || [200] }); }
  posts(page, count) { return get(this.edge, S, `${SF}/posts`, { name: 'content:posts', params: { page: page || 0, count: count || 10 } }); }
  post(slug, expect) { return get(this.edge, S, `${SF}/posts/${slug}`, { name: 'content:post', expect: expect || [200] }); }
  sitemap() { return get(this.edge, S, `${SF}/sitemap`, { name: 'content:sitemap' }); }

  // ── console: pages ────────────────────────────────────────────────────────
  listPages(page, count) {
    return get(this.edge, S, `${PV}/pages`, { name: 'content:pages-list', params: { page: page || 0, count: count || 25, sort: 'updatedAt,desc' } });
  }
  createPage(body, expect) {
    return post(this.edge, S, `${PV}/pages`, { name: 'content:page-create', body, expect: expect || [200, 201] });
  }
  updatePage(id, body, expect) {
    return put(this.edge, S, `${PV}/pages/${id}`, { name: 'content:page-update', body, expect: expect || [200, 409] });
  }
  publishPage(id, body) {
    return post(this.edge, S, `${PV}/pages/${id}/publish`, { name: 'content:page-publish', body: body || {} });
  }
  bulkPages(ids, action) {
    return post(this.edge, S, `${PV}/pages/bulk`, { name: 'content:pages-bulk', body: { ids, action }, expect: [200, 207] });
  }
  deletePage(id, force) {
    return del(this.edge, S, `${PV}/pages/${id}`, { name: 'content:page-delete', params: { force: !!force }, expect: [200, 204, 409] });
  }

  // ── console: layouts ──────────────────────────────────────────────────────
  getLayout(page) {
    return get(this.edge, S, `${PV}/layouts/${page || 'HOME'}`, { name: 'content:layout-get' });
  }
  putLayout(page, baseVersion, document, expect) {
    return put(this.edge, S, `${PV}/layouts/${page || 'HOME'}`, { name: 'content:layout-put', body: { baseVersion, document }, expect: expect || [200, 409] });
  }
  publishLayout(page, baseVersion, expect) {
    return post(this.edge, S, `${PV}/layouts/${page || 'HOME'}/publish`, { name: 'content:layout-publish', body: { baseVersion }, expect: expect || [200, 409, 422] });
  }
  summary() {
    return get(this.edge, S, `${PV}/summary`, { name: 'content:summary' });
  }
}
