// Generated by grafana-k6 on 2026-09-05T07:45:16Z
/**
 * cua, the shopper identity server. Public registration and the token-holder's identity on the storefront
 * edge; the console's shopper list on the seller edge. The login flow itself is core/pkce.js.
 * Source: store-pod/cua/http/*.http.
 */
import { get, post } from '../core/http.js';

const S = 'cua';

export class CuaClient {
  constructor(edge) { this.edge = edge; }

  /** body = { username, email, password, firstName?, lastName? } → 201; 409 when taken */
  register(body, expect) {
    return post(this.edge, S, '/api/v1/public/registration', { name: 'cua:register', body, expect: expect || [201] });
  }
  socialLogins() {
    return get(this.edge, S, '/api/v1/public/social-logins', { name: 'cua:social-logins' });
  }
  me(headers) {
    return get(this.edge, S, '/api/v1/auth/me', { name: 'cua:me', headers });
  }
  jwks() {
    return get(this.edge, S, '/oauth2/jwks', { name: 'cua:jwks' });
  }
  /** console: shoppers of the store */
  shoppers(page, count) {
    return get(this.edge, S, '/api/v1/private/shoppers', { name: 'cua:shoppers', params: { page: page || 0, count: count || 20 }, expect: [200, 404] });
  }
}
