// Generated by grafana-k6 on 2026-09-05T07:46:09Z
/**
 * store-core-gateway itself: the console's SSR entry points and the health probe. Login is core/session.js.
 */
import { get } from '../core/http.js';

export class GatewayClient {
  constructor(edge) { this.edge = edge; }

  console() { return get(this.edge, '', '/', { name: 'gateway:console' }); }
  signIn() { return get(this.edge, '', '/sign-in', { name: 'gateway:sign-in' }); }
  health() { return get(this.edge, '', '/actuator/health', { name: 'gateway:health' }); }
}
