// Generated by grafana-k6 on 2026-09-05T07:44:33Z
/**
 * inventory service: public price/stock reads, private stock/price writes and reservations.
 * Source: store-pod/inventory/inventory-service/http/{inventory,reservation}-api.http.
 */
import { get, post, put, del } from '../core/http.js';

const S = 'inventory';

export class InventoryClient {
  constructor(edge) { this.edge = edge; }

  availability(skus) {
    return get(this.edge, S, '/api/v1/availability', { name: 'inventory:availability', params: { skus: skus.join(',') } });
  }
  availabilityQuery(skus) {
    return post(this.edge, S, '/api/v1/availability/query', { name: 'inventory:availability-query', body: { skus } });
  }

  /** inventory = { productId, quantity, available, price: { amount, specialAmount?, specialEndDate? } } */
  set(sku, inventory) {
    return put(this.edge, S, `/api/v1/private/inventory/${sku}`, { name: 'inventory:set', body: inventory });
  }
  /** entries = [{ sku, inventory }] — answers in request order */
  bulk(entries) {
    return put(this.edge, S, '/api/v1/private/inventory/bulk', { name: 'inventory:bulk', body: { entries } });
  }
  deleteBySku(sku) {
    return del(this.edge, S, `/api/v1/private/inventory/${sku}`, { name: 'inventory:delete', expect: [200, 204] });
  }
  reserve(ref, entries, expect) {
    return post(this.edge, S, `/api/v1/private/reserve/${ref}`, { name: 'inventory:reserve', body: { entries }, expect: expect || [200] });
  }
  commit(ref) {
    return post(this.edge, S, `/api/v1/private/commit/${ref}`, { name: 'inventory:commit' });
  }
  release(ref) {
    return post(this.edge, S, `/api/v1/private/release/${ref}`, { name: 'inventory:release' });
  }
}
