// Generated by grafana-k6 on 2026-09-05T07:45:16Z
/**
 * merchant service: the store itself (public read, private update) and the router endpoints spg calls to
 * map a host to a store. Source: store-pod/merchant/merchant-service/http/{merchant-store-api,router-controller}.http.
 */
import { get, put } from '../core/http.js';

const S = 'merchant';

export class MerchantClient {
  constructor(edge) { this.edge = edge; }

  store(storeId) {
    return get(this.edge, S, `/api/v1/store/${storeId}`, { name: 'merchant:store' });
  }
  currentStore() {
    return get(this.edge, S, '/api/v1/store', { name: 'merchant:store-current' });
  }
  languages() {
    return get(this.edge, S, '/api/v1/store/languages', { name: 'merchant:languages' });
  }

  privateStore(expect) {
    return get(this.edge, S, '/api/v1/private/store', { name: 'merchant:store-private', expect: expect || [200] });
  }
  updateStore(body) {
    return put(this.edge, S, '/api/v1/private/store', { name: 'merchant:store-update', body });
  }
  allocates() {
    return get(this.edge, S, '/api/v1/router/private/allocates', { name: 'merchant:allocates' });
  }
  /** the call spg's domain_lookup makes on a cache miss */
  lookupByDomain(domain, expect) {
    return get(this.edge, S, '/api/v1/router/public/lookup-by-domain', { name: 'merchant:lookup-by-domain', params: { domain }, expect: expect || [200, 404] });
  }
}
