// Generated by grafana-k6 on 2026-09-05T07:44:33Z
/**
 * payment service: what the storefront asks before rendering the checkout form, and the console's configuration.
 * Source: PublicPaymentConfigurationController, PaymentConfigurationController.
 */
import { get, post, put } from '../core/http.js';

const S = 'payment';

export class PaymentClient {
  constructor(edge) { this.edge = edge; }

  supportedPaymentTypes(storeId) {
    return get(this.edge, S, `/api/v1/public/payment-configuration/${storeId}/supported-payment-types`, { name: 'payment:supported-types' });
  }
  configurations() {
    return get(this.edge, S, '/api/v1/private/payment-configuration', { name: 'payment:configurations' });
  }
  /** config = { paymentType: 'COD'|'MANUAL_TRANSFER'|'STRIPE'|'PAYPAL', enabled, apiKey?, secretKey?, webhookSecret? } → 200, no body */
  saveConfiguration(config) {
    return post(this.edge, S, '/api/v1/private/payment-configuration', { name: 'payment:configuration-save', body: config, expect: [200, 201] });
  }
  updateConfiguration(paymentType, config) {
    return put(this.edge, S, `/api/v1/private/payment-configuration/${paymentType}`, { name: 'payment:configuration-update', body: config });
  }
  transactions(params) {
    return get(this.edge, S, '/api/v1/private/payment/transactions', { name: 'payment:transactions', params: Object.assign({ page: 0, count: 20 }, params || {}) });
  }
}
