// Generated by grafana-k6 on 2026-09-05T07:46:09Z
/**
 * pod-registry through store-core-gateway. Source: store-core/pod-registry/pod-registry-service/http/pod-api.http.
 */
import { get } from '../core/http.js';

const S = 'pod-registry';

export class PodRegistryClient {
  constructor(edge) { this.edge = edge; }

  list() { return get(this.edge, S, '/api/v1/pod/list', { name: 'pod-registry:list', expect: [200, 403] }); }
  get(podId, expect) { return get(this.edge, S, `/api/v1/pod/${podId}`, { name: 'pod-registry:get', expect: expect || [200, 403] }); }
}
