// Generated by grafana-k6 on 2026-09-05T07:46:09Z
/**
 * The Next.js storefront's server-rendered pages, through spg. The page is what a shopper waits for; the API
 * calls it makes server-side are measured separately by the service clients.
 */
import { get } from '../core/http.js';
import { config } from '../core/env.js';
import { storefrontPageCache } from '../core/metrics.js';

/** Counts what landing-ui's page cache did with the page (`x-storefront-cache`; `none` from a build without it). */
function counted(page) {
  storefrontPageCache.add(1, { name: page.res.request && page.res.request.tags ? page.res.request.tags.name : 'page',
    state: page.res.headers['X-Storefront-Cache'] || 'none' });
  return page;
}

export class StorefrontPagesClient {
  constructor(edge, lang) {
    // pages take no ?store/?lang: spg resolves the store from the host, the locale is in the path
    this.edge = Object.assign({}, edge, { params: {} });
    this.lang = lang || config.lang;
  }

  page(path, opts) { return counted(get(this.edge, '', `/${this.lang}${path}`, opts)); }

  home() { return this.page('', { name: 'page:home' }); }
  category(slug, expect) { return this.page(`/category/${slug}`, { name: 'page:category', expect }); }
  product(slug, expect) { return this.page(`/product/${slug}`, { name: 'page:product', expect }); }
  search(q) { return this.page('/search', { name: 'page:search', params: { q } }); }
  checkout() { return this.page('/checkout', { name: 'page:checkout' }); }
  login() { return this.page('/login', { name: 'page:login', params: { auth: 1 } }); }
  register() { return this.page('/register', { name: 'page:register' }); }
  content(slug, expect) { return this.page(`/content/${slug}`, { name: 'page:content', expect }); }
  blog() { return this.page('/blog', { name: 'page:blog' }); }
  help() { return this.page('/help', { name: 'page:help' }); }
}
