// Generated by grafana-k6 on 2026-09-05T07:46:09Z
/**
 * The Next.js storefront's server-rendered pages, through spg. The page is what a shopper waits for; the API
 * calls it makes server-side are measured separately by the service clients.
 */
import { get } from '../core/http.js';
import { config } from '../core/env.js';

export class StorefrontPagesClient {
  constructor(edge, lang) {
    // pages take no ?store/?lang: spg resolves the store from the host, the locale is in the path
    this.edge = Object.assign({}, edge, { params: {} });
    this.lang = lang || config.lang;
  }

  home() { return get(this.edge, '', `/${this.lang}`, { name: 'page:home' }); }
  category(slug, expect) { return get(this.edge, '', `/${this.lang}/category/${slug}`, { name: 'page:category', expect }); }
  product(slug, expect) { return get(this.edge, '', `/${this.lang}/product/${slug}`, { name: 'page:product', expect }); }
  search(q) { return get(this.edge, '', `/${this.lang}/search`, { name: 'page:search', params: { q } }); }
  checkout() { return get(this.edge, '', `/${this.lang}/checkout`, { name: 'page:checkout' }); }
  login() { return get(this.edge, '', `/${this.lang}/login`, { name: 'page:login', params: { auth: 1 } }); }
  register() { return get(this.edge, '', `/${this.lang}/register`, { name: 'page:register' }); }
  content(slug, expect) { return get(this.edge, '', `/${this.lang}/content/${slug}`, { name: 'page:content', expect }); }
  blog() { return get(this.edge, '', `/${this.lang}/blog`, { name: 'page:blog' }); }
  help() { return get(this.edge, '', `/${this.lang}/help`, { name: 'page:help' }); }
}
