// Generated by grafana-k6 on 2026-09-05T07:45:16Z
/**
 * tenancy, the platform's org/store registry, through store-core-gateway with a seller session.
 * Source: store-core/tenancy/tenancy-service/http/*.http and console-ui's manager-store.service.ts.
 * Paging is page + count everywhere (the platform renames `size`).
 */
import { get, post, del } from '../core/http.js';

const S = 'tenancy';
const SM = '/api/v1/store-manager';

export class TenancyClient {
  constructor(edge) { this.edge = edge; }

  // ── public ────────────────────────────────────────────────────────────────
  /** user = { firstName, lastName, emailAddress, organizationName, password, repeatPassword } */
  signup(user, expect) {
    return post(this.edge, S, '/api/v1/signup/public/create', { name: 'tenancy:signup', body: { user }, expect: expect || [200, 201] });
  }
  saasProperties() {
    return get(this.edge, S, '/api/v1/saas/public/saas-properties', { name: 'tenancy:saas-properties' });
  }
  themes() { return get(this.edge, S, `${SM}/public/themes`, { name: 'tenancy:themes' }); }
  colorThemes() { return get(this.edge, S, `${SM}/public/color-themes`, { name: 'tenancy:color-themes' }); }

  // ── stores ────────────────────────────────────────────────────────────────
  /** what the console's store list calls: query = {} or { pod: {id}, name } */
  listStores(query, page, count) {
    return post(this.edge, S, `${SM}/list`, { name: 'tenancy:store-list', body: query || {}, params: { page: page || 0, count: count || 20 } });
  }
  stores() {
    return get(this.edge, S, `${SM}/private/store`, { name: 'tenancy:stores' });
  }
  storeInfo(storeId, expect) {
    return get(this.edge, S, `${SM}/store-info`, { name: 'tenancy:store-info', params: { store: storeId }, expect: expect || [200] });
  }
  store(storeId, expect) {
    return get(this.edge, S, `${SM}/private/store/${storeId}`, { name: 'tenancy:store', expect: expect || [200] });
  }
  storeNameExists(name) {
    return get(this.edge, S, `${SM}/private/store/unique`, { name: 'tenancy:store-unique', params: { name } });
  }
  storesPerPod() {
    return get(this.edge, S, `${SM}/stores-per-pod`, { name: 'tenancy:stores-per-pod' });
  }
  /** full body — see store-manager-api.http; 422 BILLING.QUOTA.STORE_EXCEEDED after 3 unpaid stores per org */
  createStore(body, expect) {
    const r = post(this.edge, S, `${SM}/private/store`, { name: 'tenancy:store-create', body, expect: expect || [200, 201] });
    r.storeId = r.body && r.body.id ? (r.body.id.id || r.body.id) : null;
    return r;
  }
  suspendStore(storeId, reason) {
    return post(this.edge, S, `${SM}/private/store/suspend`, { name: 'tenancy:store-suspend', params: { store: storeId, reason: reason || 'k6' } });
  }
  resumeStore(storeId, expect) {
    return post(this.edge, S, `${SM}/private/store/resume`, { name: 'tenancy:store-resume', params: { store: storeId }, expect: expect || [200] });
  }
  archiveStore(storeId) {
    return post(this.edge, S, `${SM}/private/store/archive`, { name: 'tenancy:store-archive', params: { store: storeId } });
  }
  deleteStore(storeId) {
    return del(this.edge, S, `${SM}/private/store`, { name: 'tenancy:store-delete', params: { store: storeId }, expect: [200, 204] });
  }
  /** 200 once the store is operable on its pod; 422 while provisioning; 404 cross-tenant */
  storePod(storeId, expect) {
    return get(this.edge, S, '/api/v1/router/store-pod-by-store-id', { name: 'tenancy:store-pod', params: { store: storeId }, expect: expect || [200, 422] });
  }

  // ── org / users / stats ───────────────────────────────────────────────────
  /** answers 401 even with a valid session (AuthApi binds a Principal the JWT filter does not provide); kept for coverage */
  currentUser() { return get(this.edge, S, '/api/v1/auth/current', { name: 'tenancy:auth-current', expect: [200, 401] }); }
  orgs() { return get(this.edge, S, '/api/v1/org-manager/find-all', { name: 'tenancy:orgs' }); }
  orgStores(orgId) { return get(this.edge, S, '/api/v1/org-manager/stores', { name: 'tenancy:org-stores', params: { id: orgId } }); }
  members() { return get(this.edge, S, '/api/v1/org-member/list', { name: 'tenancy:members' }); }
  userAccounts(storeId) { return get(this.edge, S, '/api/v1/user-account/list', { name: 'tenancy:user-accounts', params: { store: storeId } }); }
  storeStatistic(fromDate, toDate) {
    return post(this.edge, S, '/api/v2/private/store-statistic', { name: 'tenancy:store-statistic', body: { fromDate, toDate }, expect: [200, 403] });
  }
  orgStatistic(fromDate, toDate) {
    return post(this.edge, S, '/api/v2/private/org-statistic', { name: 'tenancy:org-statistic', body: { fromDate, toDate }, expect: [200, 403] });
  }
}
