// Generated by grafana-k6 on 2026-09-05T07:46:09Z
/**
 * uaa, the staff identity server. Public endpoints on its own origin (uaaEdge) and the admin API through the
 * gateway's /uaa forward (platformEdge + session). Source: store-core/uaa/http/*.http.
 */
import { get } from '../core/http.js';

const S = 'uaa';

export class UaaClient {
  constructor(edge) { this.edge = edge; }

  // ── public (any edge; on the gateway the prefix is /uaa) ──────────────────
  loginSettings() { return get(this.edge, S, '/api/v1/public/login/settings', { name: 'uaa:login-settings' }); }
  loginContext() { return get(this.edge, S, '/api/v1/public/login/context', { name: 'uaa:login-context', expect: [200, 400] }); }
  idps() { return get(this.edge, S, '/api/v1/public/idps', { name: 'uaa:idps' }); }
  jwks() { return get(this.edge, S, '/oauth2/jwks', { name: 'uaa:jwks' }); }
  openidConfiguration() { return get(this.edge, S, '/.well-known/openid-configuration', { name: 'uaa:openid-configuration' }); }

  // ── session-bound ─────────────────────────────────────────────────────────
  me(expect) { return get(this.edge, S, '/api/v1/auth/me', { name: 'uaa:me', expect: expect || [200] }); }
  account() { return get(this.edge, S, '/api/v1/account/me', { name: 'uaa:account' }); }
  adminUsers(params) { return get(this.edge, S, '/api/v1/admin/users', { name: 'uaa:admin-users', params: Object.assign({ page: 0, count: 20 }, params || {}), expect: [200, 403] }); }
  adminRoles() { return get(this.edge, S, '/api/v1/admin/roles', { name: 'uaa:admin-roles', params: { page: 0, count: 20 }, expect: [200, 403] }); }
  adminDashboard(range) { return get(this.edge, S, '/api/v1/admin/dashboard', { name: 'uaa:admin-dashboard', params: { range: range || '24h' }, expect: [200, 403] }); }
}
